include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Elevate strictness beyond defaults
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_future: true
    cancel_subscriptions: true
    cascade_invocations: true
    close_sinks: true
    collection_methods_unrelated_type: true
    combinators_ordering: true
    conditional_uri_does_not_exist: true
    directives_ordering: true
    discarded_futures: true
    empty_statements: true
    exhaustive_cases: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    noop_primitive_operations: true
    only_throw_errors: true
    omit_local_variable_types: false
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    sized_box_shrink_expand: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: true
    unawaited_futures: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_build_context_synchronously: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_setters_to_change_properties: true
    use_string_buffers: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - build/**
    - ios/**
    - android/**
    - linux/**
    - macos/**
    - windows/**
    - web/**
    - test/**.mocks.dart
  errors:
    invalid_use_of_visible_for_testing_member: error
    missing_required_param: error
    missing_return: error
    dead_code: warning
    todo: ignore

# Additional custom lint rules for better code quality
# Note: dart_code_metrics is no longer maintained and requires a license
# Using very_good_analysis which provides comprehensive linting rules

