import 'package:gymaipro/ai/memory/memory_category.dart';
import 'package:gymaipro/ai/memory/memory_importance.dart';
import 'package:gymaipro/ai/memory/memory_source.dart';

/// Persistent coach memory item.
///
/// This model is standalone and is not connected to existing prompts, screens,
/// OpenAI calls, navigation, or workout generation behavior.
class CoachMemory {
  const CoachMemory({
    required this.key,
    required this.value,
    required this.category,
    required this.confidence,
    required this.importance,
    required this.source,
    required this.createdAt,
    required this.updatedAt,
    required this.editable,
    required this.userEditable,
    required this.aiGenerated,
    this.expiresAt,
  });

  /// Creates a memory from persisted JSON-like data.
  factory CoachMemory.fromJson(Map<String, Object?> json) {
    return CoachMemory(
      key: _stringValue(json['key']),
      value: _stringValue(json['value']),
      category: _enumValue(
        MemoryCategory.values,
        _stringValue(json['category']),
        MemoryCategory.other,
      ),
      confidence: _doubleValue(json['confidence'], fallback: 0.5),
      importance: _enumValue(
        MemoryImportance.values,
        _stringValue(json['importance']),
        MemoryImportance.medium,
      ),
      source: _enumValue(
        MemorySource.values,
        _stringValue(json['source']),
        MemorySource.system,
      ),
      createdAt: _dateTimeValue(json['createdAt']) ?? DateTime.now(),
      updatedAt: _dateTimeValue(json['updatedAt']) ?? DateTime.now(),
      expiresAt: _dateTimeValue(json['expiresAt']),
      editable: _boolValue(json['editable'], fallback: true),
      userEditable: _boolValue(json['userEditable'], fallback: true),
      aiGenerated: _boolValue(json['aiGenerated']),
    );
  }

  /// Stable memory key.
  final String key;

  /// Memory value stored as text to keep the first version serialization-safe.
  final String value;

  /// Memory category.
  final MemoryCategory category;

  /// Confidence score from 0 to 1.
  final double confidence;

  /// Importance used for merge and retention decisions.
  final MemoryImportance importance;

  /// Source of the memory.
  final MemorySource source;

  /// Creation timestamp.
  final DateTime createdAt;

  /// Last update timestamp.
  final DateTime updatedAt;

  /// Optional expiration timestamp. Null means permanent memory.
  final DateTime? expiresAt;

  /// Whether any system actor can edit this memory.
  final bool editable;

  /// Whether the user can edit this memory.
  final bool userEditable;

  /// Whether the memory was generated by an AI process.
  final bool aiGenerated;

  /// Whether this memory is temporary.
  bool get isTemporary =>
      expiresAt != null || category == MemoryCategory.temporary;

  /// Whether this memory is permanent.
  bool get isPermanent => !isTemporary;

  /// Whether the memory has expired at [now].
  bool isExpired([DateTime? now]) {
    final expiry = expiresAt;
    if (expiry == null) return false;
    return !expiry.isAfter(now ?? DateTime.now());
  }

  /// Serializes the memory to JSON-like data.
  Map<String, Object?> toJson() {
    return <String, Object?>{
      'key': key,
      'value': value,
      'category': category.name,
      'confidence': confidence,
      'importance': importance.name,
      'source': source.name,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
      'expiresAt': expiresAt?.toIso8601String(),
      'editable': editable,
      'userEditable': userEditable,
      'aiGenerated': aiGenerated,
    };
  }

  /// Returns a modified copy.
  CoachMemory copyWith({
    String? key,
    String? value,
    MemoryCategory? category,
    double? confidence,
    MemoryImportance? importance,
    MemorySource? source,
    DateTime? createdAt,
    DateTime? updatedAt,
    DateTime? expiresAt,
    bool clearExpiresAt = false,
    bool? editable,
    bool? userEditable,
    bool? aiGenerated,
  }) {
    return CoachMemory(
      key: key ?? this.key,
      value: value ?? this.value,
      category: category ?? this.category,
      confidence: confidence ?? this.confidence,
      importance: importance ?? this.importance,
      source: source ?? this.source,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      expiresAt: clearExpiresAt ? null : expiresAt ?? this.expiresAt,
      editable: editable ?? this.editable,
      userEditable: userEditable ?? this.userEditable,
      aiGenerated: aiGenerated ?? this.aiGenerated,
    );
  }

  static String _stringValue(Object? value) {
    if (value is String) return value;
    return '';
  }

  static double _doubleValue(Object? value, {double fallback = 0}) {
    if (value is num) return value.toDouble();
    if (value is String) return double.tryParse(value) ?? fallback;
    return fallback;
  }

  static bool _boolValue(Object? value, {bool fallback = false}) {
    if (value is bool) return value;
    return fallback;
  }

  static DateTime? _dateTimeValue(Object? value) {
    if (value is! String || value.isEmpty) return null;
    return DateTime.tryParse(value);
  }

  static T _enumValue<T extends Enum>(List<T> values, String name, T fallback) {
    for (final value in values) {
      if (value.name == name) return value;
    }
    return fallback;
  }
}
