# -*- coding: utf-8 -*-
"""Compact specs for batch 5 & 6 — (slug, title, en_name, main, sec, equip, diff, pattern, mech, force, posture, area, short, intro, combo_slug, combo_title, rank)"""

PROG = [
    ['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'],
    ['قدرت', '۴', '۵–۸', '۱۲۰ث'],
    ['استقامت', '۳', '۱۲–۱۵', '۴۵ث'],
]

# slug, title, en, main_muscle, sec_keys, equip_keys, diff, pattern, mech, force, posture, area, short, intro_tail, combo_slug, combo_title, rank_extra, targets
B5 = [
    ('اسکات-اسمیت', 'اسکات اسمیت', 'Smith Squat', 'quads', ['glutes', 'hamstrings', 'abs'], ['machine'], 'beginner', 'squat', 'compound', 'push', 'standing', 'پا', 'اسکات با دستگاه اسمیت برای پا با ثبات بالا.', 'اسکات با میله ثابت روی دستگاه اسمیت؛ در اکثر سالن‌های ایرانی برای یادگیری عمق اسکات و افزایش بار امن بسیار رایج است.', 'اسکات-گابلت', 'اسکات گابلت', 'ثبات بیشتر نسبت به اسکات آزاد.', {'quads': 90, 'glutes': 80, 'hamstrings': 45}),
    ('پرس-سینه-شیب-منفی', 'پرس سینه شیب منفی', 'Decline Bench Press', 'chest', ['triceps', 'shoulder_anterior'], ['barbell', 'bench'], 'intermediate', 'horizontal_push', 'compound', 'push', 'supine', 'سینه پایین', 'پرس سینه شیب منفی برای سینه پایین و پشت بازو.', 'فشار افقی روی نیمکت شیب منفی؛ در روز سینه برای تکمیل پرس تخت و شیب مثبت در بدنسازی ایران بسیار شناخته‌شده است.', 'پرس-سینه-با-هالتر', 'پرس سینه با هالتر', 'تمرکز روی سینه پایین.', {'chest_lower': 95, 'chest': 85, 'triceps': 50}),
    ('فلای-سیمکش', 'فلای سیمکش', 'Cable Fly', 'chest', ['shoulder_anterior'], ['cable'], 'beginner', 'horizontal_push', 'isolation', 'push', 'standing', 'سینه', 'فلای سیمکش برای کشش و انقباض سینه.', 'حرکت ایزوله سینه با سیم‌کش؛ کشش مداوم و کنترل تمپو آن را در سالن‌های ایرانی برای پمپ سینه محبوب کرده است.', 'کراس-سیمکش', 'کراس سیمکش', 'کشش مداوم کابل.', {'chest': 90, 'chest_middle': 85}),
    ('فلای-معکوس-سیمکش', 'فلای معکوس سیمکش', 'Reverse Cable Fly', 'shoulder_posterior', ['traps_middle', 'rhomboids'], ['cable'], 'beginner', 'horizontal_pull', 'isolation', 'pull', 'standing', 'سرشانه پشت', 'فلای معکوس برای سرشانه پشت و پشت میانی.', 'حرکت عقب‌انداز با سیم‌کش برای دلتوئید خلفی؛ اصلاح وضعیت شانه و تعادل شانه در برنامه‌های ایرانی ضروری است.', 'پاروی-صورت', 'پاروی صورت', 'سلامت شانه و پشت.', {'shoulder_posterior': 95, 'rhomboids': 50}),
    ('زیربغل-تی-بار', 'زیربغل تی‌بار', 'T-Bar Row', 'back_lat', ['biceps', 'rhomboids', 'traps_middle'], ['barbell', 'machine'], 'intermediate', 'horizontal_pull', 'compound', 'pull', 'bent_over', 'زیربغل', 'تی‌بار برای ضخامت وسط پشت.', 'کشش افقی با بار تی یا دستگاه؛ یکی از حرکات کلاسیک روز پشت در باشگاه‌های ایرانی برای ضخامت زیربغل است.', 'رویینگ-هالتر', 'رویینگ هالتر', 'ضخامت پشت.', {'back_lat': 90, 'rhomboids': 55, 'biceps': 45}),
    ('بارفیکس-کمکی', 'بارفیکس کمکی', 'Assisted Pull-Up', 'back_lat', ['biceps', 'rhomboids'], ['machine'], 'beginner', 'vertical_pull', 'compound', 'pull', 'standing', 'زیربغل', 'بارفیکس کمکی برای ساخت قدرت کشش عمودی.', 'بارفیکس با کمک وزنه دستگاه؛ بهترین گزینه مبتدی قبل از بارفیکس آزاد در سالن‌های ایرانی است.', 'بارفیکس', 'بارفیکس', 'مسیر یادگیری بارفیکس.', {'back_lat': 85, 'biceps': 50}),
    ('چین-آپ', 'چین آپ', 'Chin-Up', 'back_lat', ['biceps'], ['bodyweight', 'bar'], 'intermediate', 'vertical_pull', 'compound', 'pull', 'hanging', 'زیربغل و جلو بازو', 'چین آپ با دست معکوس برای زیربغل و جلو بازو.', 'کشش عمودی با کف دست رو به خود؛ در مقایسه با بارفیکس جلو بازو بیشتر درگیر می‌شود و در خانه و پارک ایران محبوب است.', 'بارفیکس', 'بارفیکس', 'جلوبازو و زیربغل با هم.', {'back_lat': 85, 'biceps': 70}),
    ('رویینگ-پندلی', 'رویینگ پندلی', 'Pendlay Row', 'back_lat', ['biceps', 'rhomboids', 'traps_middle'], ['barbell'], 'intermediate', 'horizontal_pull', 'compound', 'pull', 'bent_over', 'پشت', 'پندلی‌رو برای قدرت و ضخامت پشت.', 'رویینگ از زمین با تنه افقی؛ حرکت قدرتی پشت محبوب در تمرین‌های هالتر ایرانی.', 'ددلیفت', 'ددلیفت', 'قدرت کششی پشت.', {'back_lat': 88, 'rhomboids': 60, 'traps_middle': 45}),
    ('پرس-زمین-هالتر', 'پرس زمین هالتر', 'Floor Press', 'chest', ['triceps'], ['barbell'], 'intermediate', 'horizontal_push', 'compound', 'push', 'supine', 'سینه و پشت بازو', 'پرس زمین محدودیت دامنه برای شانه امن.', 'پرس هالتر روی زمین؛ برای قدرت قفل میانی و سینه بدون استرس شانه در سالن‌های ایرانی گزینه خوبی است.', 'پرس-سینه-با-هالتر', 'پرس سینه با هالتر', 'فشار میانی امن.', {'chest': 85, 'triceps': 55}),
    ('پرس-آرنولد', 'پرس آرنولد', 'Arnold Press', 'shoulder_anterior', ['shoulder_lateral', 'triceps'], ['dumbbell'], 'intermediate', 'vertical_push', 'compound', 'push', 'seated', 'سرشانه', 'پرس آرنولد برای حجم سرشانه از همه زوایا.', 'پرس دمبل با چرخش کف دست؛ حرکت کلاسیک آرنولد شوارتزنگگر و محبوب برای سرشانه در بدنسازی.', 'پرس-سرشانه-دمبل', 'پرس سرشانه با دمبل', 'حجم سرشانه ۳ بعدی.', {'shoulder_anterior': 90, 'shoulder_lateral': 75, 'triceps': 45}),
    ('نشر-جانب-هالتر', 'نشر جانب با هالتر', 'Barbell Lateral Raise', 'shoulder_lateral', ['traps_upper'], ['barbell'], 'intermediate', 'lateral_raise', 'isolation', 'push', 'standing', 'سرشانه جانب', 'نشر جانب هالتر برای عرض سرشانه.', 'بالا بردن هالتر به طرف برای دلتوئید میانی؛ کمتر رایج از دمبل ولی در برنامه‌های قدیمی سالن ایران دیده می‌شود.', 'نشر-جانب-سیمکش', 'نشر جانب سیمکش', 'عرض سرشانه.', {'shoulder_lateral': 95}),
    ('نشر-پشت-دمبل', 'نشر پشت با دمبل', 'Rear Delt Fly', 'shoulder_posterior', ['rhomboids'], ['dumbbell'], 'beginner', 'horizontal_pull', 'isolation', 'pull', 'bent_over', 'سرشانه پشت', 'نشر پشت دمبل برای دلتوئید خلفی.', 'فلای معکوس با دمبل خم شده؛ برای سلامت شانه و تعادل در کنار پرس‌های سنگین ضروری است.', 'فلای-معکوس-سیمکش', 'فلای معکوس سیمکش', 'تعادل شانه.', {'shoulder_posterior': 95, 'rhomboids': 40}),
    ('کیک-بک-باسن-سیمکش', 'کیک بک باسن سیمکش', 'Cable Glute Kickback', 'glutes', ['hamstrings'], ['cable'], 'beginner', 'hip_extension', 'isolation', 'push', 'standing', 'باسن', 'کیک بک سیمکش برای جداسازی باسن.', 'اکستنشن لگ با سیم‌کش؛ برای پمپ و فعال‌سازی گلوت در روز پا بسیار پرطرفدار است.', 'هیپ-تراست', 'هیپ تراست', 'جداسازی باسن.', {'glutes': 95}),
    ('استپ-آپ', 'استپ آپ', 'Step-Up', 'quads', ['glutes', 'hamstrings'], ['dumbbell', 'bench'], 'beginner', 'lunge', 'compound', 'push', 'standing', 'پا', 'استپ آپ برای پا تک‌طرفه و تعادل.', 'بالا رفتن روی باکس یا نیمکت با وزنه؛ حرکت عملکردی محبوب در تمرین خانگی و سالن.', 'لانج', 'لانج', 'تعادل و پا تک‌طرفه.', {'quads': 85, 'glutes': 75}),
    ('ساق-نشسته', 'ساق نشسته', 'Seated Calf Raise', 'calves', [], ['machine'], 'beginner', 'calf_raise', 'isolation', 'push', 'seated', 'ساق پا', 'ساق نشسته برای سولئوس.', 'ساق نشسته روی دستگاه؛ برای سولئوس (ساق پایین) در پایان روز پا در ایران استاندارد است.', 'ساق-ایستاده', 'ساق ایستاده', 'سولئوس عمیق.', {'calves': 95, 'calves_soleus': 90}),
    ('پرس-ساق', 'پرس ساق', 'Leg Press Calf Raise', 'calves', [], ['machine'], 'beginner', 'calf_raise', 'isolation', 'push', 'seated', 'ساق پا', 'پرس ساق روی دستگاه پرس پا.', 'ساق روی لگ پرس؛ برای بار سنگین‌تر روی گاستrocnemius محبوب است.', 'ساق-ایستاده', 'ساق ایستاده', 'بار سنگین ساق.', {'calves': 90}),
    ('گود-مورنینگ', 'گود مورنینگ', 'Good Morning', 'hamstrings', ['glutes', 'lower_back'], ['barbell'], 'advanced', 'hip_hinge', 'compound', 'pull', 'standing', 'پشت پا و کمر', 'گود مورنینگ برای هیپ‌هینج و پشت پا.', 'هیپ‌هینج با هالتر پشت گردن؛ حرکت پیشرفته برای همسترینگ و کمر در تمرین قدرتی.', 'ددلیفت', 'ددلیفت', 'هیپ‌هینج پیشرفته.', {'hamstrings': 85, 'glutes': 70, 'lower_back': 55}),
    ('چرخ-شکم', 'چرخ شکم', 'Ab Wheel Rollout', 'abs', ['shoulder_anterior', 'lats'], ['bodyweight'], 'intermediate', 'anti_extension', 'compound', 'pull', 'kneeling', 'شکم و Core', 'چرخ شکم برای Core قوی.', 'رول‌اوت با چرخ شکم؛ یکی از سخت‌ترین و مؤثرترین حرکات Core در خانه و سالن.', 'پلانک-plank', 'پلانک', 'Core عمیق.', {'abs': 90, 'abs_lower': 85}),
    ('کرانچ-دوچرخه', 'کرانچ دوچرخه', 'Bicycle Crunch', 'abs', ['obliques'], ['bodyweight'], 'beginner', 'rotation', 'compound', 'pull', 'supine', 'شکم و پهلو', 'کرانچ دوچرخه برای شکم و پهلو.', 'کرانچ چرخشی درازکش؛ برای تعریف شکم و پهلو در تمرین خانگی ایران بسیار رایج است.', 'کرانچ', 'کرانچ', 'شکم و پهلو.', {'abs': 85, 'obliques': 75}),
    ('سوپرمن', 'سوپرمن', 'Superman', 'lower_back', ['glutes', 'hamstrings'], ['bodyweight'], 'beginner', 'back_extension', 'isolation', 'pull', 'prone', 'کمر و باسن', 'سوپرمن برای تقویت کمر پایین.', 'بالا بردن همزمان دست و پا درازکش؛ حرکت اصلاحی و تقویتی کمر برای نشستن طولانی.', 'کوهنورد', 'کوهنورد', 'کمر اصلاحی.', {'lower_back': 85, 'glutes': 50}),
]

B6 = [
    ('شنا-با-زانو', 'شنا با زانو', 'Knee Push-Up', 'chest', ['triceps', 'shoulder_anterior'], ['bodyweight'], 'beginner', 'horizontal_push', 'compound', 'push', 'prone', 'سینه', 'شنا با زانو برای مبتدی.', 'شنا سوئدی با زانو روی زمین؛ نقطه شروع محبوب قبل از شنا کامل در خانه و سالن.', 'شنا-سوئدی', 'شنا سوئدی', 'مسیر یادگیری شنا.', {'chest': 80, 'triceps': 45}),
    ('پرس-سینه-اسمیت', 'پرس سینه اسمیت', 'Smith Machine Bench Press', 'chest', ['triceps', 'shoulder_anterior'], ['machine', 'bench'], 'beginner', 'horizontal_push', 'compound', 'push', 'supine', 'سینه', 'پرس سینه اسمیت با ثبات بالا.', 'پرس سینه روی اسمیت؛ برای مبتدی و تمرین تا ناتوانی امن‌تر از هالتر آزاد.', 'پرس-سینه-با-دمبل', 'پرس سینه با دمبل', 'ثبات و ایمنی.', {'chest': 90, 'triceps': 50}),
    ('لگ-پرس', 'لگ پرس', 'Leg Press', 'quads', ['glutes', 'hamstrings'], ['machine'], 'beginner', 'squat', 'compound', 'push', 'seated', 'پا', 'لگ پرس برای پا با بار بالا.', 'پرس پا روی دستگاه ۴۵ یا افقی؛ یکی از پرکاربردترین حرکات پا در سالن‌های ایرانی.', 'اسکات-گابلت', 'اسکات گابلت', 'بار سنگین پا.', {'quads': 90, 'glutes': 70}),
    ('جلو-بازو-اینکلاین-دمبل', 'جلو بازو اینکلاین دمبل', 'Incline Dumbbell Curl', 'biceps', ['forearms'], ['dumbbell', 'bench'], 'intermediate', 'elbow_flexion', 'isolation', 'pull', 'incline_seated', 'جلوبازو', 'جلو بازو اینکلاین برای کشش بیشتر.', 'جلو بازو روی نیمکت شیب مثبت؛ برای کشش طولانی دوبی و حجم بازو محبوب است.', 'جلو-بازو-دمبل', 'جلو بازو دمبل', 'کشش طولانی دوبی.', {'biceps': 95}),
    ('پشت-بازو-خرچنگ-سیمکش', 'پشت بازو خرچنگ سیمکش', 'Rope Tricep Pushdown', 'triceps', [], ['cable'], 'beginner', 'elbow_extension', 'isolation', 'push', 'standing', 'پشت بازو', 'فشار خرچنگ برای پمپ پشت بازو.', 'پشت بازو با طناب سیم‌کش؛ انقباض کامل در پایین محبوب‌ترین حرکت پشت بازو در سالن.', 'پشت-بازو-سیمکش', 'پشت بازو سیمکش', 'انقباض کامل.', {'triceps': 95}),
    ('فشار-پشت-بازو-هالتر', 'فشار پشت بازو هالتر', 'Skull Crusher', 'triceps', [], ['barbell', 'bench'], 'intermediate', 'elbow_extension', 'isolation', 'push', 'supine', 'پشت بازو', 'فشار پشت بازو هالتر خوابیده.', 'لایینگ تریسپس اکستنشن با هالتر EZ یا مستقیم؛ کلاسیک روز بازو.', 'پشت-بازو-دمبل-خوابیده', 'پشت بازو دمبل خوابیده', 'حجم پشت بازو.', {'triceps': 95}),
    ('کرانچ-سیمکش', 'کرانچ سیمکش', 'Cable Crunch', 'abs', ['obliques'], ['cable'], 'beginner', 'spinal_flexion', 'isolation', 'pull', 'kneeling', 'شکم', 'کرانچ سیمکش با مقاومت قابل تنظیم.', 'جمع شدن تنه با سیم‌کش زانو زده؛ جایگزین وزنه برای شکم در سالن.', 'کرانچ', 'کرانچ', 'مقاومت پیشرونده.', {'abs': 90}),
    ('زیربغل-تک-بازو-سیمکش', 'زیربغل تک بازو سیمکش', 'Single Arm Lat Pulldown', 'back_lat', ['biceps'], ['cable'], 'intermediate', 'vertical_pull', 'compound', 'pull', 'kneeling', 'زیربغل', 'پول‌داون تک‌بازو برای تعادل پشت.', 'کشش عمودی یک دست؛ رفع عدم تقارن زیربغل.', 'زیربغل-سیمکش', 'زیربغل سیمکش', 'تعادل چپ و راست.', {'back_lat': 90}),
    ('فلای-پک-دستگاه', 'فلای پک دستگاه', 'Pec Deck Fly', 'chest', ['shoulder_anterior'], ['machine'], 'beginner', 'horizontal_push', 'isolation', 'push', 'seated', 'سینه', 'فلای پک برای ایزوله سینه.', 'دستگاه پک دک؛ برای مبتدی و پمپ سینه بدون نیاز به تعادل دمبل.', 'فلای-دمبل', 'فلای دمبل', 'ایزوله امن سینه.', {'chest': 92}),
    ('دیپ-وزن-بدن', 'دیپ وزن بدن', 'Bodyweight Dip', 'triceps', ['chest', 'shoulder_anterior'], ['bodyweight', 'bench'], 'intermediate', 'vertical_push', 'compound', 'push', 'support', 'پشت بازو و سینه', 'دیپ بین دو نیمکت برای پشت بازو.', 'دیپ با وزن بدن روی نیمکت؛ در خانه و سالن بدون پارالل محبوب است.', 'دیپ-نیمکت', 'دیپ نیمکت', 'پشت بازو در خانه.', {'triceps': 85, 'chest': 55}),
    ('اسکات-با-مکث', 'اسکات با مکث', 'Pause Squat', 'quads', ['glutes', 'hamstrings'], ['barbell'], 'advanced', 'squat', 'compound', 'push', 'standing', 'پا', 'اسکات با مکث در پایین برای قدرت.', 'اسکات با توقف ۲–۳ ثانیه در پایین‌ترین نقطه؛ برای قدرت از نقطه مرده.', 'اسکات-هالتر', 'اسکات هالتر', 'قدرت از عمق.', {'quads': 90, 'glutes': 75}),
    ('بورپی', 'بورپی', 'Burpee', 'full_body', ['chest', 'quads', 'abs'], ['bodyweight'], 'intermediate', 'compound', 'compound', 'push', 'standing', 'تمام بدن', 'بورپی برای کاردیو و قدرت عملکردی.', 'حرکت ترکیبی پرش و شنا؛ برای چربی‌سوزی و آمادگی در تمرین‌های فانکشنال ایران.', 'کوهنورد', 'کوهنورد', 'کاردیو شدید.', {'quads': 60, 'chest': 50, 'abs': 55}),
    ('ددباگ', 'ددباگ', 'Dead Bug', 'abs', ['hip_flexors'], ['bodyweight'], 'beginner', 'anti_extension', 'isolation', 'pull', 'supine', 'Core', 'ددباگ برای Core پایدار.', 'حرکت اصلاحی درازکش؛ برای Core بدون فشار گردن محبوب فیزیوتراپی و بدنسازی.', 'پلانک-plank', 'پلانک', 'Core امن.', {'abs': 85}),
    ('پالوف-پرس', 'پالوف پرس', 'Pallof Press', 'abs', ['obliques'], ['cable'], 'intermediate', 'anti_rotation', 'isolation', 'push', 'standing', 'Core', 'پالوف ضد چرخش برای Core.', 'فشار افقی سیم‌کش مقابل کشش؛ برای پایداری Core و کمر.', 'پلانک-جانبی', 'پلانک جانبی', 'ضد چرخش.', {'abs': 80, 'obliques': 70}),
    ('پرس-سینه-دمبل-تک-دست', 'پرس سینه دمبل تک دست', 'Single Arm Dumbbell Press', 'chest', ['triceps', 'abs'], ['dumbbell', 'bench'], 'intermediate', 'horizontal_push', 'compound', 'push', 'supine', 'سینه', 'پرس تک‌دست برای Core و تعادل.', 'پرس سینه یک دست؛ ضدچرخش Core و رفع عدم تقارن.', 'پرس-سینه-با-دمبل', 'پرس سینه با دمبل', 'تعادل و Core.', {'chest': 85, 'abs': 40}),
    ('زیربغل-نشسته-سیمکش', 'زیربغل نشسته سیمکش', 'Seated Cable Row', 'back_lat', ['biceps', 'rhomboids'], ['cable'], 'beginner', 'horizontal_pull', 'compound', 'pull', 'seated', 'پشت', 'رویینگ نشسته سیمکش کلاسیک.', 'کشش افقی نشسته؛ یکی از پرتکرارترین حرکات پشت در سالن ایرانی.', 'رویینگ-سیمکش', 'رویینگ سیمکش', 'پشت پهن و ضخیم.', {'back_lat': 88, 'rhomboids': 55, 'biceps': 45}),
    ('لانج-هالتر', 'لانج با هالتر', 'Barbell Lunge', 'quads', ['glutes', 'hamstrings'], ['barbell'], 'intermediate', 'lunge', 'compound', 'push', 'standing', 'پا', 'لانج هالتر برای پا و تعادل.', 'لانج با هالتر پشت یا جلو؛ قدرت پا تک‌طرفه در روز پا.', 'لانج', 'لانج', 'قدرت تک‌پا.', {'quads': 85, 'glutes': 75}),
    ('لانج-عقب', 'لانج عقب', 'Reverse Lunge', 'quads', ['glutes'], ['dumbbell'], 'beginner', 'lunge', 'compound', 'push', 'standing', 'پا', 'لانج عقب فشار کمتر روی زانو.', 'قدم به عقب با دمبل؛ برای مبتدی و زانو حساس مناسب‌تر از لانج جلو.', 'لانج-راه-رفتن', 'لانج راه رفتن', 'زانو دوست‌دار.', {'quads': 80, 'glutes': 75}),
    ('پشت-بازو-سیمکش-معکوس', 'پشت بازو سیمکش معکوس', 'Reverse Grip Pushdown', 'triceps', [], ['cable'], 'beginner', 'elbow_extension', 'isolation', 'push', 'standing', 'پشت بازو', 'پشت بازو دست معکوس برای سر دراز.', 'فشار پایین با کف دست رو به بالا؛ تاکید روی سر دراز تریسپس.', 'پشت-بازو-خرچنگ-سیمکش', 'پشت بازو خرچنگ سیمکش', 'سر دراز تریسپس.', {'triceps': 90}),
    ('وال-سیت', 'وال سیت', 'Wall Sit', 'quads', ['glutes'], ['bodyweight'], 'beginner', 'isometric', 'isolation', 'push', 'standing', 'پا', 'وال سیت ایزومتریک برای استقامت پا.', 'نشستن imaginary روی دیوار؛ برای استقامت چهارسر در خانه و گرم‌کردن فوتبال محبوب ایران.', 'اسکات-گابلت', 'اسکات گابلت', 'استقامت چهارسر.', {'quads': 85, 'glutes': 50}),
]
