// GymAI Popular 20 — BATCH 4 (20 حرکت چهارم)
// Code Snippets: Run everywhere | بدون تگ php

if (!function_exists('gymai_pop20_batch4_definitions')) {
function gymai_pop20_batch4_definitions() {
    $base_img = 'https://gymaipro.ir/wp-content/uploads/2026/06/';
    $defs = [];
    $add = function (array $row) use (&$defs, $base_img) {
        if (empty($row['image'])) {
            $key = !empty($row['image_key']) ? $row['image_key'] : ('exercise-batch4-' . str_pad((string) (count($defs) + 1), 2, '0', STR_PAD_LEFT));
            $row['image'] = $base_img . $key . '.jpg';
        }
        $defs[] = $row;
    };

    $add([
        'image_key' => 'exercise-batch4-01',
        'slug' => 'اسکات-فرانت',
        'title' => 'اسکات فرانت',
        'aliases' => ['Front Squat', 'Barbell Front Squat', 'اسکات جلو هالتر'],
        'intro' => '<strong>اسکات فرانت</strong> اسکات با هالتر جلوی بدن برای چهارسر، Core و قامت عمودی است. در بدنسازی پیشرفته و سالن‌های ایرانی برای تقویت اسکات با بار جلو بسیار رایج است.',
        'caption' => 'اسکات فرانت — هالتر روی دلتوئید، قامت عمودی',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'Core، باسن', 'difficulty' => 'پیشرفته', 'equipment' => 'هالتر، رک', 'type' => 'قدرتی / حجمی'],
        'tips' => ['آرنج بالا، میله روی شانه.', 'قامت عمودی در کل حرکت.', 'زانو هم‌راستا با پا.'],
        'setup' => ['هالتر روی رک، گرفتن clean grip یا cross.', 'پا عرض شانه.', 'Core سفت، سینه بالا.'],
        'execution' => ['باسن عقب و پایین.', 'عمق تا ران موازی یا پایین‌تر.', 'فشار کامل کف پا.', 'ایستادن بدون قفل سخت زانو.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: quadriceps', 'کمکی: glutes، Core', 'تثبیت: erector، ساعد'],
        'mistakes' => [['آرنج افتاده', 'آرنج موازی زمین'], ['پاشنه بلند', 'کف پا ثابت'], ['تنه جلو', 'قامت عمودی']],
        'program' => [['حجم', '۳–۴', '۶–۱۰', '۱۲۰–۱۵۰ث'], ['قدرت', '۴–۵', '۳–۶', '۱۸۰ث'], ['تکنیک', '۳', '۸', '۹۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'اسکات گابلت', 'slug' => 'اسکات-گابلت']],
        'faqs' => [['q' => 'فرانت یا بک اسکات؟', 'a' => 'فرانت Core و quad بیشتر؛ بک اسکات بار سنگین‌تر و کل بدن.']],
        'summary' => 'اسکات فرانت برای quad، Core و اسکات امن با بار جلو.',
        'summary_keys' => 'آرنج بالا | قامت عمودی | Core سفت',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'abs'],
            'difficulty' => 'advanced', 'equipment_keys' => ['barbell', 'rack'],
            'exercise_type' => 'strength', 'movement_pattern' => 'squat', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'clean', 'resistance_profile' => 'free_weight', 'joint_focus' => 'knee_hip',
            'muscle_targets' => ['quads' => 95, 'glutes' => 70, 'abs' => 55, 'hamstrings' => 40],
            'met' => 6, 'movement_distance_cm' => 55, 'calories_per_1000kg' => 50, 'exercise_difficulty_score' => 7, 'typical_rpe' => 8,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'strength', 'recommended_sets' => '3-5',
            'rep_range_strength' => '3-6', 'rep_range_hypertrophy' => '6-10', 'rep_range_endurance' => '10-12', 'rest_seconds' => 150, 'tempo' => '2-1-2',
            'short_description' => 'اسکات فرانت اسکات با هالتر جلو برای چهارسر، Core و قامت.',
            'target_area' => 'پا و Core',
        ],
        'rank_extra' => 'اسکات پیشرفته با بار جلو.',
    ]);

    $add([
        'image_key' => 'exercise-batch4-02',
        'slug' => 'پل-باسن',
        'title' => 'پل باسن',
        'aliases' => ['Glute Bridge', 'Hip Bridge', 'Bridge', 'پل لگن'],
        'intro' => '<strong>پل باسن</strong> حرکت هیپ‌هینج درازکش برای فعال‌سازی باسن و همسترینگ است. در تمرینات خانه و گرم‌کردن روز پا در سالن‌های ایرانی بسیار محبوب است.',
        'caption' => 'پل باسن — فشار پاشنه و انقباض باسن بالا',
        'quick' => ['main' => 'باسن', 'secondary' => 'همسترینگ، کمر', 'difficulty' => 'مبتدی', 'equipment' => 'بدون تجهیزات (یا وزنه)', 'type' => 'حجمی / فعال‌سازی'],
        'tips' => ['پاشنه روی زمین.', 'مکث انقباض بالا.', 'چانه به سینه در peak.'],
        'setup' => ['درازکش، زانو خم، پا عرض لگن.', 'دست کنار بدن.', 'Core سفت.'],
        'execution' => ['بالا آوردن لگن با باسن.', 'خط زانو تا شانه.', 'مکث ۱–۲ ثانیه.', 'پایین کنترل بدون تکیه کامل.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: gluteus maximus', 'کمکی: hamstrings، erector', 'تثبیت: Core'],
        'mistakes' => [['کمر بیش از حد قوس', 'چانه به سینه'], ['پاشنه بلند', 'پاشنه ثابت'], ['بدون مکث', 'انقباض کامل']],
        'program' => [['فعال‌سازی', '۲–۳', '۱۵–۲۰', '۳۰ث'], ['حجم', '۳–۴', '۱۲–۱۵', '۶۰ث'], ['قدرت', '۳', '۸–۱۲ با وزنه', '۹۰ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'هیپ تراست', 'slug' => 'هیپ-تراست']],
        'faqs' => [['q' => 'پل باسن یا هیپ تراست؟', 'a' => 'پل باسن ساده‌تر؛ هیپ تراست دامنه و بار بیشتر.']],
        'summary' => 'پل باسن پایه فعال‌سازی و رشد باسن.',
        'summary_keys' => 'پاشنه ثابت | مکث بالا | Core سفت',
        'meta' => [
            'main_muscle' => 'glutes', 'secondary_muscle_keys' => ['hamstrings', 'lower_back'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'none', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'hip',
            'muscle_targets' => ['glutes' => 90, 'hamstrings' => 50, 'lower_back' => 30, 'abs' => 20],
            'met' => 3.5, 'movement_distance_cm' => 35, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 2, 'typical_rpe' => 6,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '8-12', 'rep_range_hypertrophy' => '12-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 60, 'tempo' => '2-2-2',
            'short_description' => 'پل باسن برای باسن، همسترینگ و Core در حالت درازکش.',
            'target_area' => 'باسن',
        ],
        'rank_extra' => 'فعال‌سازی باسن در خانه.',
    ]);

    $add([
        'image_key' => 'exercise-batch4-03',
        'slug' => 'جمع-زانو-آویزان',
        'title' => 'جمع زانو آویزان',
        'aliases' => ['Hanging Knee Raise', 'Hanging Knee Curl', 'Knee Raise', 'زیر شکم آویزان'],
        'intro' => '<strong>جمع زانو آویزان</strong> حرکت فلکشن Core آویزان برای شکم پایین و فلکسور لگن است. در تمرینات شکم سالن‌های ایرانی بعد از بارفیکس بسیار رایج است.',
        'caption' => 'جمع زانو آویزان — جمع زانو بدون تاب بدن',
        'quick' => ['main' => 'شکم پایین', 'secondary' => 'فلکسور لگن', 'difficulty' => 'متوسط', 'equipment' => 'بارفیکس یا دستگاه', 'type' => 'حجمی / Core'],
        'tips' => ['شکم منقبض، نه تاب بدن.', 'زانو تا سینه یا بالاتر.', 'پایین کنترل‌شده.'],
        'setup' => ['آویزان از میله، overhand.', 'بدن ثابت، شانه فعال.', 'پا کنار هم یا کمی جلو.'],
        'execution' => ['جمع زانو به سمت سینه.', 'مکث کوتاه بالا.', 'پایین آهسته.', 'تکرار بدون ارتعاش.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: rectus abdominis lower', 'کمکی: hip flexors', 'تثبیت: lats، forearms'],
        'mistakes' => [['تاب بدن', 'شکم کنترل'], ['فقط زانو کم', 'دامنه کامل'], ['آرنج خم زیاد', 'آویزان فعال']],
        'program' => [['حجم', '۳–۴', '۱۰–۱۵', '۴۵–۶۰ث'], ['استقامت', '۳', '۱۵–۲۰', '۳۰ث'], ['قدرت', '۳', '۸–۱۰', '۶۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'پای آویزان', 'slug' => 'پای-آویزان']],
        'faqs' => [['q' => 'زانو یا پا صاف؟', 'a' => 'زانو آسان‌تر؛ پا صاف سخت‌تر برای شکم پایین.']],
        'summary' => 'جمع زانو آویزان برای شکم پایین و Core قوی.',
        'summary_keys' => 'بدون تاب | شکم منقبض | تمپو کنترل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['hip_flexors', 'back_lat'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['pull_up_bar'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'spinal_flexion', 'body_engagement' => 'core_dominant',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'hanging', 'grip_type' => 'pronated', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'core_spine',
            'muscle_targets' => ['abs' => 90, 'hip_flexors' => 55, 'back_lat' => 30, 'forearms' => 25],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 35, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '10-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'جمع زانو آویزان برای شکم پایین و فلکسور لگن.',
            'target_area' => 'شکم',
        ],
        'rank_extra' => 'شکم پایین با وزن بدن.',
    ]);

    $add([
        'image_key' => 'exercise-batch4-04',
        'slug' => 'زیربغل-دست-جمع',
        'title' => 'زیربغل دست جمع',
        'aliases' => ['Close Grip Lat Pulldown', 'Neutral Grip Pulldown', 'V-Bar Pulldown', 'پول‌داون دست جمع'],
        'intro' => '<strong>زیربغل دست جمع</strong> کشش عمودی با گرفتن neutral یا دست جمع برای ضخامت پشت و زیربغل است. مکمل زیربغل سیمکش دست باز در سالن‌های ایرانی محسوب می‌شود.',
        'caption' => 'زیربغل دست جمع — آرنج کنار بدن، کشش به سینه',
        'quick' => ['main' => 'زیربغل، پشت میانی', 'secondary' => 'جلوبازو', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'قدرتی / حجمی'],
        'tips' => ['کتف پایین قبل از خم.', 'آرنج نزدیک بدن.', 'کشش به بالای سینه.'],
        'setup' => ['نشسته، دستگیره V یا neutral.', 'ران زیر پد.', 'سینه بالا.'],
        'execution' => ['کشش با آرنج پایین.', 'میله/دستگیره به سینه.', 'مکث عقب.', 'بازگشت آهسته.'],
        'breathing' => 'بازدم پایین — دم بالا.',
        'muscles' => ['اصلی: latissimus dorsi، rhomboids', 'کمکی: biceps', 'تثبیت: Core'],
        'mistakes' => [['کشش با بدن', 'تنه ثابت'], ['آرنج باز', 'کنار بدن'], ['دامنه ناقص', 'کشش کامل بالا']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۶–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'زیربغل سیمکش', 'slug' => 'زیربغل-سیمکش']],
        'faqs' => [['q' => 'دست جمع یا باز؟', 'a' => 'جمع ضخامت میانی؛ باز پهن‌تر lats.']],
        'summary' => 'زیربغل دست جمع برای ضخامت پشت و lats.',
        'summary_keys' => 'آرنج کنار | کتف پایین | کشش به سینه',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['rhomboids', 'biceps', 'traps_middle'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'shoulder_elbow',
            'muscle_targets' => ['back_lat' => 90, 'rhomboids' => 75, 'biceps' => 50, 'traps_middle' => 40],
            'met' => 5, 'movement_distance_cm' => 50, 'calories_per_1000kg' => 47, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-8', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 75, 'tempo' => '2-1-2',
            'short_description' => 'زیربغل دست جمع کشش عمودی برای ضخامت پشت و زیربغل.',
            'target_area' => 'زیربغل و پشت',
        ],
        'rank_extra' => 'ضخامت پشت با دست جمع.',
    ]);

    $add([
        'image_key' => 'exercise-batch4-05',
        'slug' => 'زیربغل-یک-دست-دمبل',
        'title' => 'زیربغل یک دست دمبل',
        'aliases' => ['Single Arm Dumbbell Row', 'One Arm DB Row', 'Kroc Row', 'رویینگ تک دست'],
        'intro' => '<strong>زیربغل یک دست دمبل</strong> کشش افقی تک‌طرفه برای زیربغل، پشت میانی و تعادل است. در روز پشت سالن‌های ایرانی جایگزین رایج رویینگ دو دست است.',
        'caption' => 'زیربغل یک دست دمبل — کتف جمع و کشش به لگن',
        'quick' => ['main' => 'زیربغل، پشت میانی', 'secondary' => 'جلوبازو', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل، نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['کتف جمع در عقب.', 'آرنج نزدیک بدن.', 'کشش به جیب لگن.'],
        'setup' => ['یک زانو و دست روی نیمکت.', 'دمبل آزاد، کمر خنثی.', 'پا ثابت.'],
        'execution' => ['کشش دمبل به لگن.', 'مکث عقب.', 'پایین کنترل.', 'تعویض دست.'],
        'breathing' => 'بازدم کشش — دم پایین.',
        'muscles' => ['اصلی: lats، rhomboids', 'کمکی: biceps، rear delt', 'تثبیت: Core'],
        'mistakes' => [['تاب بدن', 'تنه ثابت'], ['کشش به سینه', 'به لگن/شکم'], ['کتف شل', 'جمع قبل از کشش']],
        'program' => [['حجم', '۳–۴', '۱۰–۱۲ هر دست', '۶۰–۹۰ث'], ['قدرت', '۳–۴', '۶–۸', '۹۰ث'], ['استقامت', '۳', '۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'رویینگ هالتر', 'slug' => 'رویینگ-هالتر']],
        'faqs' => [['q' => 'کدام دست اول؟', 'a' => 'دست ضعیف‌تر اول؛ هر دو دست یکسان.']],
        'summary' => 'رویینگ تک دست برای پشت متقارن و ضخامت.',
        'summary_keys' => 'کتف جمع | کشش به لگن | تنه ثابت',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['rhomboids', 'biceps', 'shoulder_posterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'transverse', 'laterality' => 'unilateral',
            'posture' => 'bent_over', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'shoulder_elbow',
            'muscle_targets' => ['back_lat' => 90, 'rhomboids' => 75, 'biceps' => 45, 'shoulder_posterior' => 35],
            'met' => 5, 'movement_distance_cm' => 42, 'calories_per_1000kg' => 45, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-8', 'rep_range_hypertrophy' => '10-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 75, 'tempo' => '2-1-2',
            'short_description' => 'زیربغل یک دست دمبل کشش افقی تک‌طرفه برای پشت و lats.',
            'target_area' => 'پشت',
        ],
        'rank_extra' => 'پشت متقارن تک دست.',
    ]);
    $add([
        'image_key' => 'exercise-batch4-06',
        'slug' => 'نشر-از-جلو',
        'title' => 'نشر از جلو',
        'aliases' => ['Front Raise', 'Dumbbell Front Raise', 'Plate Front Raise', 'نشر قدامی'],
        'intro' => '<strong>نشر از جلو</strong> حرکت ایزوله برای دلتوئید قدامی است. در روز سرشانه سالن‌های ایرانی بعد از پرس overhead برای تکمیل جلو سرشانه بسیار رایج است.',
        'caption' => 'نشر از جلو — بالا تا خط شانه، آرنج نرم',
        'quick' => ['main' => 'سرشانه قدامی', 'secondary' => 'ذوزنقه (کم)', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل یا صفحه', 'type' => 'حجمی'],
        'tips' => ['آرنج کمی خم ثابت.', 'بالا تا خط شانه.', 'بدون تاب بدن.'],
        'setup' => ['ایستاده، دمبل جلوی ران.', 'Core سفت.', 'شانه پایین.'],
        'execution' => ['بالا بردن جلوی بدن.', 'مکث کوتاه.', 'پایین آهسته.', 'تناوبی یا همزمان.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: deltoid anterior', 'کمکی: traps upper', 'تثبیت: Core'],
        'mistakes' => [['وزنه سنگین', 'سبک و کنترل'], ['بالا بیش از شانه', 'خط شانه کافی'], ['تاب بدن', 'ثبات']],
        'program' => [['حجم', '۳–۴', '۱۲–۱۵', '۴۵–۶۰ث'], ['پمپ', '۳', '۱۵–۲۰', '۳۰ث'], ['استقامت', '۳', '۲۰', '۳۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'پرس سرشانه با دمبل', 'slug' => 'پرس-سرشانه-دمبل']],
        'faqs' => [['q' => 'دمبل یا صفحه؟', 'a' => 'هر دو مؤثر؛ صفحه grip متفاوت، دمبل دامنه طبیعی‌تر.']],
        'summary' => 'نشر از جلو برای جلو سرشانه و فرم V.',
        'summary_keys' => 'وزنه سبک | خط شانه | بدون تاب',
        'meta' => [
            'main_muscle' => 'shoulder_anterior', 'secondary_muscle_keys' => ['traps_upper'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'shoulder_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'shoulder',
            'muscle_targets' => ['shoulder_anterior' => 95, 'traps_upper' => 25],
            'met' => 3, 'movement_distance_cm' => 45, 'calories_per_1000kg' => 30, 'exercise_difficulty_score' => 2, 'typical_rpe' => 6.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '', 'rep_range_hypertrophy' => '12-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 45, 'tempo' => '2-1-2',
            'short_description' => 'نشر از جلو ایزوله برای دلتوئید قدامی.',
            'target_area' => 'سرشانه قدامی',
        ],
        'rank_extra' => 'جلو سرشانه ایزوله.',
    ]);

    $add([
        'image_key' => 'exercise-batch4-07',
        'slug' => 'شراگ-دمبل',
        'title' => 'شراگ دمبل',
        'aliases' => ['Dumbbell Shrug', 'DB Shrugs', 'Shrugs', 'شراگ با دمبل'],
        'intro' => '<strong>شراگ دمبل</strong> حرکت ایزوله برای ذوزنقه بالایی (upper traps) است. در روز پشت/سرشانه سالن‌های ایرانی مکمل کول هالتر محسوب می‌شود.',
        'caption' => 'شراگ دمبل — بالا بردن شانه، گردن خنثی',
        'quick' => ['main' => 'ذوزنقه بالایی', 'secondary' => 'ساعد', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل', 'type' => 'حجمی'],
        'tips' => ['بالا بردن شانه، نه چرخش.', 'مکث ۱ ثانیه بالا.', 'گردن خنثی.'],
        'setup' => ['ایستاده، دمبل کنار بدن.', 'آرنج صاف.', 'Core سفت.'],
        'execution' => ['بالا بردن شانه به گوش.', 'مکث peak.', 'پایین آهسته.', 'تکرار.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: upper trapezius', 'کمکی: forearms', 'تثبیت: Core'],
        'mistakes' => [['چرخش شانه', 'فقط بالا-پایین'], ['کشش گردن', 'گردن خنثی'], ['پرتاب', 'تمپو کنترل']],
        'program' => [['حجم', '۳–۴', '۱۲–۱۵', '۴۵–۶۰ث'], ['سنگین', '۳', '۸–۱۰', '۹۰ث'], ['استقامت', '۳', '۱۵–۲۰', '۳۰ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کول هالتر', 'slug' => 'کول-هالتر']],
        'faqs' => [['q' => 'دمبل یا هالتر؟', 'a' => 'دمبل دامنه طبیعی؛ هالتر بار سنگین‌تر.']],
        'summary' => 'شراگ دمبل برای ذوزنقه بالایی پر.',
        'summary_keys' => 'شانه بالا | گردن خنثی | مکث peak',
        'meta' => [
            'main_muscle' => 'traps_upper', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'scapular_elevation', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'shoulder',
            'muscle_targets' => ['traps_upper' => 95, 'forearms' => 35],
            'met' => 3.5, 'movement_distance_cm' => 15, 'calories_per_1000kg' => 32, 'exercise_difficulty_score' => 2, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '8-10', 'rep_range_hypertrophy' => '12-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 60, 'tempo' => '2-2-2',
            'short_description' => 'شراگ دمبل برای upper traps و ساعد.',
            'target_area' => 'ذوزنقه',
        ],
        'rank_extra' => 'ذوزنقه بالایی با دمبل.',
    ]);

    $add([
        'image_key' => 'exercise-batch4-08',
        'slug' => 'پشت-بازو-بالای-سر-سیمکش',
        'title' => 'پشت بازو بالای سر سیمکش',
        'aliases' => ['Overhead Cable Triceps Extension', 'Cable Overhead Extension', 'Rope Overhead Extension'],
        'intro' => '<strong>پشت بازو بالای سر سیمکش</strong> اکستنشن overhead با کابل برای کشش long head سه‌سر است. در Arms Day سالن‌های ایرانی جایگزین محبوب پشت بازو دمبل بالای سر است.',
        'caption' => 'پشت بازو بالای سر سیمکش — آرنج ثابت، کشش کامل',
        'quick' => ['main' => 'پشت بازو (long head)', 'secondary' => 'ساعد', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش، طناب', 'type' => 'حجمی'],
        'tips' => ['آرنج ثابت کنار سر.', 'کشش تا انقباض کامل.', 'بدون تاب کمر.'],
        'setup' => ['پولی پایین، طناب.', 'پشت به دستگاه، طناب بالای سر.', 'گام جلو، کابل کشیده.'],
        'execution' => ['باز کردن آرنج جلو.', 'مکث در انقباض.', 'پایین کنترل پشت سر.', 'تکرار.'],
        'breathing' => 'بازدم باز — دم پایین.',
        'muscles' => ['اصلی: triceps long head', 'کمکی: forearms', 'تثبیت: Core'],
        'mistakes' => [['آرنج باز', 'ثابت کنار سر'], ['کمر قوس', 'Core سفت'], ['نیمه دامنه', 'کشش کامل']],
        'program' => [['حجم', '۳–۴', '۱۰–۱۵', '۴۵–۶۰ث'], ['پمپ', '۳', '۱۵–۲۰', '۳۰ث'], ['قدرت', '۳', '۸–۱۰', '۷۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت بازو پشت سر', 'slug' => 'پشت-بازو-پشت-سر']],
        'faqs' => [['q' => 'طناب یا میله؟', 'a' => 'طناب مچ راحت‌تر؛ میله grip ثابت.']],
        'summary' => 'اکستنشن overhead کابل برای long head سه‌سر.',
        'summary_keys' => 'آرنج ثابت | کشش کامل | تنش مداوم',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'elbow_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'elbow',
            'muscle_targets' => ['triceps' => 95, 'forearms' => 25],
            'met' => 3.5, 'movement_distance_cm' => 45, 'calories_per_1000kg' => 32, 'exercise_difficulty_score' => 2, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '8-10', 'rep_range_hypertrophy' => '10-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 45, 'tempo' => '2-1-2',
            'short_description' => 'پشت بازو بالای سر سیمکش برای long head و هایپرتروفی سه‌سر.',
            'target_area' => 'پشت بازو',
        ],
        'rank_extra' => 'long head با تنش مداوم.',
    ]);
    $add([
        'image_key' => 'exercise-batch4-09',
        'slug' => 'کراس-باز-سیمکش',
        'title' => 'کراس باز سیمکش',
        'aliases' => ['Reverse Cable Crossover', 'Rear Delt Cable Fly', 'High to Low Reverse Fly', 'فلای معکوس کابل'],
        'intro' => '<strong>کراس باز سیمکش</strong> حرکت کششی برای سرشانه خلفی و پشت میانی با کابل است. در prehab و روز پشت سالن‌های ایرانی مکمل پاروی صورت محسوب می‌شود.',
        'caption' => 'کراس باز سیمکش — آرنج نرم، باز کردن عقب',
        'quick' => ['main' => 'سرشانه خلفی', 'secondary' => 'رomboids، ذوزنقه', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'حجمی / prehab'],
        'tips' => ['آرنج کمی خم ثابت.', 'باز کردن دست عقب.', 'کتف جمع در peak.'],
        'setup' => ['بین دو پولی بالا.', 'گام جلو، دست‌ها جلو.', 'تنه کمی خم.'],
        'execution' => ['باز کردن دست به پهلو/عقب.', 'مکث peak.', 'بازگشت کنترل.', 'تکرار.'],
        'breathing' => 'بازدم باز — دم جلو.',
        'muscles' => ['اصلی: shoulder posterior', 'کمکی: rhomboids، traps', 'تثبیت: Core'],
        'mistakes' => [['وزنه سنگین', 'سبک و کنترل'], ['آرنج باز', 'آرنج نرم'], ['تاب بدن', 'ثبات']],
        'program' => [['prehab', '۳–۴', '۱۵–۲۰', '۴۵ث'], ['حجم', '۳', '۱۲–۱۵', '۶۰ث'], ['گرم‌کردن', '۲', '۱۵', '۳۰ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پاروی صورت', 'slug' => 'پاروی-صورت']],
        'faqs' => [['q' => 'کراس باز یا پاروی صورت؟', 'a' => 'هر دو rear delt؛ کراس باز دامنه پهن‌تر، face pull posture بهتر.']],
        'summary' => 'کراس باز برای سرشانه خلفی و posture.',
        'summary_keys' => 'وزنه سبک | کتف جمع | آرنج نرم',
        'meta' => [
            'main_muscle' => 'shoulder_posterior', 'secondary_muscle_keys' => ['rhomboids', 'traps_upper'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'transverse', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'shoulder',
            'muscle_targets' => ['shoulder_posterior' => 90, 'rhomboids' => 55, 'traps_upper' => 40],
            'met' => 3.5, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 30, 'exercise_difficulty_score' => 2, 'typical_rpe' => 6.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '', 'rep_range_hypertrophy' => '12-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'کراس باز سیمکش برای سرشانه خلفی و پشت میانی.',
            'target_area' => 'سرشانه خلفی',
        ],
        'rank_extra' => 'rear delt با کابل.',
    ]);

    $add([
        'image_key' => 'exercise-batch4-10',
        'slug' => 'شنا-شیب-منفی',
        'title' => 'شنا شیب منفی',
        'aliases' => ['Decline Push-Up', 'Feet Elevated Push-Up', 'Pike Push-Up Light', 'شنا پا بالا'],
        'intro' => '<strong>شنا شیب منفی</strong> شنا با پا روی سطح مرتفع برای تمرکز روی سینه بالایی و سرشانه است. در تمرینات خانه و بدون دستگاه سالن‌های ایرانی بسیار کاربردی است.',
        'caption' => 'شنا شیب منفی — پا بالا، خط بدن صاف',
        'quick' => ['main' => 'سینه بالایی', 'secondary' => 'سرشانه، پشت بازو', 'difficulty' => 'متوسط', 'equipment' => 'نیمکت یا سکو', 'type' => 'قدرتی / حجمی'],
        'tips' => ['خط بدن از سر تا پا.', 'دست عرض شانه.', 'پایین تا سینه نزدیک زمین.'],
        'setup' => ['پا روی نیمکت/سکو.', 'دست روی زمین عرض شانه.', 'Core سفت.'],
        'execution' => ['پایین کنترل‌شده.', 'آرنج ۴۵ درجه.', 'بازدم بالا.', 'تکرار بدون افتادگی کمر.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: chest upper', 'کمکی: triceps، anterior deltoid', 'تثبیت: Core'],
        'mistakes' => [['کمر افتاده', 'Core سفت'], ['پا خیلی بالا', 'زاویه ملایم'], ['دامنه ناقص', 'سینه نزدیک زمین']],
        'program' => [['حجم', '۳–۴', '۱۰–۱۵', '۴۵–۶۰ث'], ['استقامت', '۳', '۱۵–۲۵', '۳۰ث'], ['قدرت', '۴', '۶–۱۰', '۶۰ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'شنا سوئدی', 'slug' => 'شنا-سوئدی']],
        'faqs' => [['q' => 'چقدر پا بالا؟', 'a' => 'هرچه بالاتر سینه بالایی بیشتر؛ با زاویه ملایم شروع کنید.']],
        'summary' => 'شنا شیب منفی برای بالاسینه بدون وزنه.',
        'summary_keys' => 'Core سفت | خط بدن صاف | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest_upper', 'secondary_muscle_keys' => ['shoulder_anterior', 'triceps', 'abs'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bench', 'bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'decline', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'shoulder_elbow',
            'muscle_targets' => ['chest_upper' => 90, 'shoulder_anterior' => 50, 'triceps' => 45, 'abs' => 35],
            'met' => 4.5, 'movement_distance_cm' => 35, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '10-15', 'rep_range_endurance' => '15-25', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'شنا شیب منفی برای سینه بالایی، سرشانه و Core.',
            'target_area' => 'سینه بالایی',
        ],
        'rank_extra' => 'بالاسینه با وزن بدن.',
    ]);

    $add([
        'image_key' => 'exercise-batch4-11',
        'slug' => 'دیپ-نیمکت',
        'title' => 'دیپ بین نیمکت',
        'aliases' => ['Bench Dip', 'Triceps Bench Dip', 'Chair Dip', 'دیپ نیمکت'],
        'intro' => '<strong>دیپ بین نیمکت</strong> حرکت فشار برای پشت بازو با پشت روی نیمکت است. در تمرینات خانه و Arms Day سالن‌های ایرانی جایگزین ساده دیپ پارالل محسوب می‌شود.',
        'caption' => 'دیپ بین نیمکت — آرنج عقب، پایین کنترل',
        'quick' => ['main' => 'پشت بازو', 'secondary' => 'سینه پایین، سرشانه', 'difficulty' => 'مبتدی', 'equipment' => 'نیمکت', 'type' => 'حجمی / قدرتی'],
        'tips' => ['آرنج عقب نه باز.', 'پایین تا ۹۰ درجه.', 'شانه پایین.'],
        'setup' => ['دست روی لبه نیمکت.', 'پا جلو روی زمین یا روی نیمکت دوم.', 'بدن نزدیک نیمکت.'],
        'execution' => ['پایین با خم آرنج.', 'بالا تا تقریباً صاف.', 'کنترل تمپو.', 'تکرار.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: triceps', 'کمکی: chest lower، anterior deltoid', 'تثبیت: Core'],
        'mistakes' => [['آرنج باز', 'نزدیک بدن'], ['شانه بالا', 'کتف پایین'], ['عمق زیاد', '۹۰° کافی']],
        'program' => [['حجم', '۳–۴', '۱۰–۱۵', '۴۵–۶۰ث'], ['استقامت', '۳', '۱۵–۲۰', '۳۰ث'], ['قدرت', '۳', '۶–۱۰ با وزنه', '۶۰ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت بازو کیک بک', 'slug' => 'پشت-بازو-کیک-بک']],
        'faqs' => [['q' => 'پا روی زمین یا بالا؟', 'a' => 'زمین آسان‌تر؛ پا بالا سخت‌تر برای triceps.']],
        'summary' => 'دیپ نیمکت برای پشت بازو در خانه و سالن.',
        'summary_keys' => 'آرنج عقب | شانه پایین | تمپو کنترل',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => ['chest', 'shoulder_anterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bench', 'bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated_elevated', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'elbow_shoulder',
            'muscle_targets' => ['triceps' => 90, 'chest_lower' => 45, 'shoulder_anterior' => 35],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 36, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '10-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'دیپ بین نیمکت برای پشت بازو و سینه پایین.',
            'target_area' => 'پشت بازو',
        ],
        'rank_extra' => 'triceps بدون پارالل.',
    ]);

    $add([
        'image_key' => 'exercise-batch4-12',
        'slug' => 'رومانیایی-دمبل',
        'title' => 'رومانیایی دمبل',
        'aliases' => ['Dumbbell Romanian Deadlift', 'DB RDL', 'Romanian Deadlift Dumbbell', 'RDL دمبل'],
        'intro' => '<strong>رومانیایی دمبل</strong> هیپ‌هینج با دمبل برای همسترینگ و باسن است. در روز پا سالن‌های ایرانی جایگزین سبک‌تر ددلیفت کلاسیک برای RDL محسوب می‌شود.',
        'caption' => 'رومانیایی دمبل — لگن عقب، پشت خنثی',
        'quick' => ['main' => 'همسترینگ', 'secondary' => 'باسن، کمر', 'difficulty' => 'متوسط', 'equipment' => 'دمبل', 'type' => 'قدرتی / حجمی'],
        'tips' => ['لگن عقب، زانو نرم.', 'دمبل نزدیک پا.', 'کشش همسترینگ در پایین.'],
        'setup' => ['ایستاده، دمبل جلوی ران.', 'پا عرض لگن.', 'Core سفت، سینه بالا.'],
        'execution' => ['لگن عقب، خم با کمر خنثی.', 'پایین تا کشش همسترینگ.', 'فشار پاشنه برای بالا.', 'ایستادن کامل.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: hamstrings', 'کمکی: glutes، erector', 'تثبیت: Core'],
        'mistakes' => [['کمر گرد', 'قامت خنثی'], ['زانو خم زیاد', 'هینج لگن'], ['دمبل دور از پا', 'نزدیک ساق']],
        'program' => [['حجم', '۳–۴', '۱۰–۱۲', '۹۰ث'], ['قدرت', '۴', '۶–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۶۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'ددلیفت', 'slug' => 'ددلیفت']],
        'faqs' => [['q' => 'دمبل یا هالتر؟', 'a' => 'دمبل برای شروع و دامنه؛ هالتر بار سنگین‌تر.']],
        'summary' => 'RDL دمبل برای همسترینگ و باسن.',
        'summary_keys' => 'لگن عقب | پشت خنثی | کشش کنترل',
        'meta' => [
            'main_muscle' => 'hamstrings', 'secondary_muscle_keys' => ['glutes', 'lower_back'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'hip',
            'muscle_targets' => ['hamstrings' => 90, 'glutes' => 75, 'lower_back' => 45, 'abs' => 25],
            'met' => 5, 'movement_distance_cm' => 50, 'calories_per_1000kg' => 46, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-8', 'rep_range_hypertrophy' => '10-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '3-1-2',
            'short_description' => 'رومانیایی دمبل هیپ‌هینج برای همسترینگ، باسن و Core.',
            'target_area' => 'پشت پا و باسن',
        ],
        'rank_extra' => 'همسترینگ با دمبل.',
    ]);

    $add([
        'image_key' => 'exercise-batch4-13',
        'slug' => 'سومو-ددلیفت',
        'title' => 'سومو ددلیفت',
        'aliases' => ['Sumo Deadlift', 'Wide Stance Deadlift', 'Sumo DL', 'ددلیفت سومو'],
        'intro' => '<strong>سومو ددلیفت</strong> ددلیفت با پا باز و دست داخل پا برای باسن، داخل ران و quad است. در powerlifting و روز پا سالن‌های ایرانی جایگزین محبوب conventional است.',
        'caption' => 'سومو ددلیفت — پا باز، کمر عمودی‌تر',
        'quick' => ['main' => 'باسن، داخل ران', 'secondary' => 'چهارسر، کمر', 'difficulty' => 'پیشرفته', 'equipment' => 'هالتر', 'type' => 'قدرتی'],
        'tips' => ['پا باز، انگشتان به پلت.', 'زانو بیرون.', 'کمر خنثی، سینه بالا.'],
        'setup' => ['میله روی زمین.', 'پا عریض، دست داخل زانو.', 'کتف جمع، Core سفت.'],
        'execution' => ['فشار کف پا، میله بالا.', 'کمر ثابت در کشش.', 'ایستادن کامل.', 'پایین کنترل همان مسیر.'],
        'breathing' => 'دم پایین — بازدم بالا (یا Valsalva سنگین).',
        'muscles' => ['اصلی: glutes، adductors', 'کمکی: quads، erector', 'تثبیت: Core، traps'],
        'mistakes' => [['پا خیلی باریک', 'stance سومو'], ['زانو داخل', 'زانو بیرون'], ['کمر گرد', 'کتف جمع']],
        'program' => [['قدرت', '۴–۵', '۳–۶', '۱۸۰–۲۴۰ث'], ['حجم', '۳–۴', '۶–۸', '۱۵۰ث'], ['تکنیک', '۳', '۵', '۱۲۰ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'ددلیفت', 'slug' => 'ددلیفت']],
        'faqs' => [['q' => 'سومو یا conventional؟', 'a' => 'سومو باسن/داخل ران؛ conventional کمر و hamstring بیشتر.']],
        'summary' => 'سومو ددلیفت برای باسن و قدرت با stance باز.',
        'summary_keys' => 'پا باز | زانو بیرون | کمر خنثی',
        'meta' => [
            'main_muscle' => 'glutes', 'secondary_muscle_keys' => ['hamstrings', 'quads', 'lower_back', 'adductors'],
            'difficulty' => 'advanced', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'mixed', 'resistance_profile' => 'free_weight', 'joint_focus' => 'hip_knee',
            'muscle_targets' => ['glutes' => 90, 'adductors' => 80, 'quads' => 70, 'hamstrings' => 65, 'lower_back' => 55, 'traps_upper' => 40],
            'met' => 6.5, 'movement_distance_cm' => 55, 'calories_per_1000kg' => 55, 'exercise_difficulty_score' => 7, 'typical_rpe' => 8.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'strength', 'recommended_sets' => '3-5',
            'rep_range_strength' => '3-6', 'rep_range_hypertrophy' => '6-8', 'rep_range_endurance' => '8-10', 'rest_seconds' => 180, 'tempo' => '1-0-1',
            'short_description' => 'سومو ددلیفت برای باسن، داخل ران و قدرت لگن.',
            'target_area' => 'پا و باسن',
        ],
        'rank_extra' => 'قدرت باسن با stance باز.',
    ]);
    $add([
        'image_key' => 'exercise-batch4-14',
        'slug' => 'فارمر-واک',
        'title' => 'فارمر واک',
        'aliases' => ['Farmer\'s Walk', 'Farmer Carry', 'Dumbbell Carry', 'حمل دمبل'],
        'intro' => '<strong>فارمر واک</strong> حرکت حمل وزنه برای ذوزنقه، Core، ساعد و قدرت گرفتن است. در تمرینات عملکردی و پایان روز بدنسازی سالن‌های ایرانی رایج است.',
        'caption' => 'فارمر واک — شانه عقب، قدم کوتاه و سریع',
        'quick' => ['main' => 'ذوزنقه، Core', 'secondary' => 'ساعد، پا', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل یا kettlebell', 'type' => 'قدرتی / عملکردی'],
        'tips' => ['شانه عقب و پایین.', 'قدم کوتاه.', 'نگه‌داشتن وزنه بدون تماس با پا.'],
        'setup' => ['دمبل سنگین کنار بدن.', 'ایستاده، Core سفت.', 'گردن خنثی.'],
        'execution' => ['راه رفتن با وزنه.', 'قدم کوتاه و کنترل.', 'مسافت یا زمان هدف.', 'قرار دادن کنترل‌شده.'],
        'breathing' => 'تنفس عادی — نفس حبس نکنید.',
        'muscles' => ['اصلی: traps، Core', 'کمکی: forearms، glutes', 'تثبیت: کل بدن'],
        'mistakes' => [['شانه گرد', 'عقب و پایین'], ['تماس وزنه با پا', 'فاصله کنار'], ['قوس کمر', 'Core سفت']],
        'program' => [['قدرت', '۳–۴', '۲۰–۴۰ متر', '۹۰ث'], ['استقامت', '۳', '۶۰ ثانیه', '۶۰ث'], ['حجم', '۳', '۳۰ متر', '۷۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کتله بل سوینگ', 'slug' => 'کتله-بل-سوینگ']],
        'faqs' => [['q' => 'چقدر سنگین؟', 'a' => 'وزنه‌ای که ۳۰–۶۰ ثانیه فرم خوب حفظ شود.']],
        'summary' => 'فارمر واک برای Core، ساعد و قدرت عملکردی.',
        'summary_keys' => 'شانه عقب | قدم کوتاه | Core سفت',
        'meta' => [
            'main_muscle' => 'traps_upper', 'secondary_muscle_keys' => ['abs', 'forearms', 'glutes'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell', 'kettlebell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'carry', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'static', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'full_body',
            'muscle_targets' => ['traps_upper' => 85, 'abs' => 70, 'forearms' => 75, 'glutes' => 40],
            'met' => 6, 'movement_distance_cm' => 3000, 'calories_per_1000kg' => 50, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'strength', 'recommended_sets' => '3-4',
            'rep_range_strength' => '20-40m', 'rep_range_hypertrophy' => '30-60 sec', 'rep_range_endurance' => '60-90 sec', 'rest_seconds' => 90, 'tempo' => 'controlled',
            'short_description' => 'فارمر واک حمل وزنه برای ذوزنقه، Core و ساعد.',
            'target_area' => 'Core و ساعد',
        ],
        'rank_extra' => 'قدرت گرفتن و Core.',
    ]);

    $add([
        'image_key' => 'exercise-batch4-15',
        'slug' => 'چرخش-روسی',
        'title' => 'چرخش روسی',
        'aliases' => ['Russian Twist', 'Seated Twist', 'Weighted Russian Twist', 'تاب روسی'],
        'intro' => '<strong>چرخش روسی</strong> حرکت چرخشی Core برای مورب‌ها و شکم است. در تمرینات شکم خانه و سالن ایرانی برای obliques بسیار محبوب است.',
        'caption' => 'چرخش روسی — چرخش کنترل‌شده، پا از زمین',
        'quick' => ['main' => 'مورب‌ها', 'secondary' => 'شکم، فلکسور لگن', 'difficulty' => 'مبتدی', 'equipment' => 'بدون تجهیزات (یا صفحه/دمبل)', 'type' => 'Core / استقامتی'],
        'tips' => ['چرخش از Core نه فقط دست.', 'پا از زمین (پیشرفته).', 'تمپو کنترل.'],
        'setup' => ['نشسته، زانو خم، پاشنه نزدیک.', 'تنه کمی عقب، Core سفت.', 'دست جلوی سینه یا با وزنه.'],
        'execution' => ['چرخش به یک پهلو.', 'لمس زمین یا نزدیک.', 'چرخش به پهلو دیگر.', 'تکرار ریتمیک.'],
        'breathing' => 'بازدم در چرخش — دم وسط.',
        'muscles' => ['اصلی: obliques', 'کمکی: rectus abdominis', 'تثبیت: hip flexors'],
        'mistakes' => [['فقط دست می‌چرخد', 'Core فعال'], ['کمر گرد', 'سینه بالا'], ['تمپo سریع', 'کنترل']],
        'program' => [['استقامت', '۳', '۲۰–۳۰ هر طرف', '۳۰ث'], ['حجم', '۳–۴', '۱۵–۲۰', '۴۵ث'], ['سنگین', '۳', '۱۲ با وزنه', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کرانچ', 'slug' => 'کرانچ']],
        'faqs' => [['q' => 'پا روی زمین؟', 'a' => 'روی زمین آسان‌تر؛ پا بالا سخت‌تر برای Core.']],
        'summary' => 'چرخش روسی برای مورب‌ها و Core چرخشی.',
        'summary_keys' => 'چرخش Core | تمپو کنترل | پا بالا',
        'meta' => [
            'main_muscle' => 'obliques', 'secondary_muscle_keys' => ['abs', 'hip_flexors'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight', 'plate'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'spinal_rotation', 'body_engagement' => 'core_dominant',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'transverse', 'laterality' => 'alternating',
            'posture' => 'seated', 'grip_type' => 'none', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'core_spine',
            'muscle_targets' => ['obliques' => 90, 'abs' => 60, 'hip_flexors' => 35],
            'met' => 3.5, 'movement_distance_cm' => 30, 'calories_per_1000kg' => 28, 'exercise_difficulty_score' => 3, 'typical_rpe' => 6.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'endurance', 'recommended_sets' => '3-4',
            'rep_range_strength' => '', 'rep_range_hypertrophy' => '15-20', 'rep_range_endurance' => '20-30', 'rest_seconds' => 45, 'tempo' => '2-1-2',
            'short_description' => 'چرخش روسی برای مورب‌ها و Core با چرخش کنترل‌شده.',
            'target_area' => 'مورب‌ها',
        ],
        'rank_extra' => 'مورب‌ها و Core چرخشی.',
    ]);

    $add([
        'image_key' => 'exercise-batch4-16',
        'slug' => 'کوهنورد',
        'title' => 'کوهنورد',
        'aliases' => ['Mountain Climber', 'Running Plank', 'Alternating Knee Drive', 'کاین کلایmber'],
        'intro' => '<strong>کوهنورد</strong> حرکت پویا پلانک برای Core، فلکسور لگن و کاردیو است. در HIIT و گرم‌کردن سالن‌های ایرانی بسیار پرکاربرد است.',
        'caption' => 'کوهنورد — پلانک ثابت، زانو به سینه',
        'quick' => ['main' => 'شکم، Core', 'secondary' => 'فلکسور لگن، شانه', 'difficulty' => 'مبتدی', 'equipment' => 'بدون تجهیزات', 'type' => 'کاردیو / Core'],
        'tips' => ['خط بدن پلانک ثابت.', 'زانو به سینه نه بیرون.', 'Core سفت.'],
        'setup' => ['شنا بالا، دست زیر شانه.', 'پا کشیده، Core سفت.', 'بدن صاف.'],
        'execution' => ['یک زانو به سینه.', 'تعویض سریع پا.', 'ادامه ریتمیک.', 'نگه‌داشتن لگن پایین.'],
        'breathing' => 'تنفس عادی — ریتم با حرکت.',
        'muscles' => ['اصلی: rectus abdominis', 'کمکی: hip flexors، shoulders', 'تثبیت: Core'],
        'mistakes' => [['لگن بالا', 'پلانک ثابت'], ['پا بیرون', 'زانو به سینه'], ['کمر افتاده', 'Core سفت']],
        'program' => [['کاردیو', '۳–۴', '۳۰–۴۵ث', '۳۰ث'], ['Core', '۳', '۲۰–۳۰', '۴۵ث'], ['HIIT', '۴', '۴۰ث کار', '۲۰ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'جمع زانو پلانک', 'slug' => 'جمع-زانو-پلانک']],
        'faqs' => [['q' => 'آهسته یا سریع؟', 'a' => 'سریع کاردیو؛ آهسته Core بیشتر.']],
        'summary' => 'کوهنورد برای Core، کاردیو و چربی‌سوزی.',
        'summary_keys' => 'پلانک ثابت | زانو به سینه | Core سفت',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['hip_flexors', 'shoulder_anterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'cardio', 'movement_pattern' => 'dynamic_plank', 'body_engagement' => 'core_dominant',
            'mechanics_type' => 'compound', 'force_type' => 'dynamic', 'plane_of_motion' => 'sagittal', 'laterality' => 'alternating',
            'posture' => 'plank', 'grip_type' => 'none', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'core_hip',
            'muscle_targets' => ['abs' => 85, 'hip_flexors' => 70, 'shoulder_anterior' => 40, 'obliques' => 35],
            'met' => 8, 'movement_distance_cm' => 50, 'calories_per_1000kg' => 55, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'endurance', 'recommended_sets' => '3-4',
            'rep_range_strength' => '', 'rep_range_hypertrophy' => '', 'rep_range_endurance' => '30-60 sec', 'rest_seconds' => 30, 'tempo' => 'fast',
            'short_description' => 'کوهنورد پویا برای Core، فلکسور لگن و کاردیو.',
            'target_area' => 'شکم و Core',
        ],
        'rank_extra' => 'Core و کاردیو در خانه.',
    ]);

    $add([
        'image_key' => 'exercise-batch4-17',
        'slug' => 'پشت-بازو-دمبل-خوابیده',
        'title' => 'پشت بازو دمبل خوابیده',
        'aliases' => ['Lying Dumbbell Triceps Extension', 'Skull Crusher DB', 'DB Lying Extension', 'پشت بازو خوابیده'],
        'intro' => '<strong>پشت بازو دمبل خوابیده</strong> اکستنشن سه‌سر در حالت درازکش برای کشش long head است. در Arms Day سالن‌های ایرانی مکمل پشت بازو پشت سر محسوب می‌شود.',
        'caption' => 'پشت بازو دمبل خوابیده — آرنج ثابت، پایین پشت سر',
        'quick' => ['main' => 'پشت بازو', 'secondary' => 'ساعد', 'difficulty' => 'متوسط', 'equipment' => 'دمبل، نیمکت', 'type' => 'حجمی'],
        'tips' => ['آرنج ثابت رو به بالا.', 'پایین پشت سر.', 'دمبل کنار هم یا یکی.'],
        'setup' => ['درازکش روی نیمکت.', 'دمبل بالای سینه، آرنج رو به سقف.', 'پا ثابت.'],
        'execution' => ['خم آرنج، پایین پشت سر.', 'کشش triceps.', 'بازگشت تا صاف.', 'تکرار کنترل.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: triceps', 'کمکی: forearms', 'تثبیت: Core'],
        'mistakes' => [['آرنج باز', 'ثابت رو به بالا'], ['دمبل به صورت', 'پشت سر'], ['نیمه دامنه', 'کشش کامل']],
        'program' => [['حجم', '۳–۴', '۱۰–۱۲', '۶۰ث'], ['قدرت', '۳', '۶–۸', '۹۰ث'], ['فینشر', '۲', '۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت بازو دمبل', 'slug' => 'پشت-بازو-دمبل']],
        'faqs' => [['q' => 'یک یا دو دمبل؟', 'a' => 'دو دمبل دامنه بیشتر؛ یکی برای تمرکز.']],
        'summary' => 'پشت بازو خوابیده برای long head و حجم سه‌سر.',
        'summary_keys' => 'آرنج ثابت | پشت سر | کشش کامل',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell', 'bench'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'elbow_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'lying_supine', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'elbow',
            'muscle_targets' => ['triceps' => 95, 'forearms' => 25],
            'met' => 3.5, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 32, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-8', 'rep_range_hypertrophy' => '10-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '3-1-2',
            'short_description' => 'پشت بازو دمبل خوابیده برای long head و هایپرتروفی سه‌سر.',
            'target_area' => 'پشت بازو',
        ],
        'rank_extra' => 'long head در حالت درازکش.',
    ]);

    $add([
        'image_key' => 'exercise-batch4-18',
        'slug' => 'پشت-بازو-پشت-سر-سیمکش',
        'title' => 'پشت بازو پشت سر سیمکش',
        'aliases' => ['Cable Triceps Pushdown Behind Head', 'Rope Behind Head Extension', 'Overhead Rope Extension Seated'],
        'intro' => '<strong>پشت بازو پشت سر سیمکش</strong> اکستنشن سه‌سر با طناب از پشت سر برای کشش long head است. در Arms Day سالن‌های ایرانی مکمل پشت بازو بالای سر سیمکش است.',
        'caption' => 'پشت بازو پشت سر سیمکش — آرنج ثابت، کشش کامل',
        'quick' => ['main' => 'پشت بازو (long head)', 'secondary' => 'ساعد', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش، طناب', 'type' => 'حجمی'],
        'tips' => ['آرنج ثابت کنار سر.', 'کشش از پشت سر جلو.', 'بدون تاب کمر.'],
        'setup' => ['نشسته یا ایستاده، پولی بالا.', 'طناب پشت سر.', 'گام جلو، کابل کشیده.'],
        'execution' => ['باز کردن آرنج جلو.', 'مکث انقباض.', 'پایین کنترل پشت سر.', 'تکرار.'],
        'breathing' => 'بازدم باز — دم پایین.',
        'muscles' => ['اصلی: triceps long head', 'کمکی: forearms', 'تثبیت: Core'],
        'mistakes' => [['آرنج باز', 'ثابت'], ['کمر قوس', 'Core سفت'], ['وزنه سنگین', 'کنترل']],
        'program' => [['حجم', '۳–۴', '۱۲–۱۵', '۴۵–۶۰ث'], ['پمپ', '۳', '۱۵–۲۰', '۳۰ث'], ['فینشر', '۲', '۱۵', '۳۰ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت بازو بالای سر سیمکش', 'slug' => 'پشت-بازو-بالای-سر-سیمکش']],
        'faqs' => [['q' => 'فرق با بالای سر؟', 'a' => 'زاویه کابل متفاوت؛ هر دو long head را هدف می‌گیرند.']],
        'summary' => 'اکستنشن پشت سر کابل برای long head سه‌سر.',
        'summary_keys' => 'آرنج ثابت | کشش کامل | تنش مداوم',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'elbow_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'elbow',
            'muscle_targets' => ['triceps' => 95, 'forearms' => 25],
            'met' => 3.5, 'movement_distance_cm' => 42, 'calories_per_1000kg' => 31, 'exercise_difficulty_score' => 2, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '8-10', 'rep_range_hypertrophy' => '12-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 45, 'tempo' => '2-1-2',
            'short_description' => 'پشت بازو پشت سر سیمکش برای long head و پمپ سه‌سر.',
            'target_area' => 'پشت بازو',
        ],
        'rank_extra' => 'long head با طناب.',
    ]);

    $add([
        'image_key' => 'exercise-batch4-19',
        'slug' => 'جمع-زانو-پلانک',
        'title' => 'جمع زانو پلانک',
        'aliases' => ['Plank Knee to Elbow', 'Spiderman Plank', 'Cross Body Mountain Climber', 'زانو به آرنج'],
        'intro' => '<strong>جمع زانو پلانک</strong> حرکت Core پویا با آوردن زانو به آرنج مخالف در پلانک است. در تمرینات شکم و HIIT سالن‌های ایرانی برای obliques بسیار رایج است.',
        'caption' => 'جمع زانو پلانک — پلانک ثابت، زانو به آرنج',
        'quick' => ['main' => 'مورب‌ها، شکم', 'secondary' => 'فلکسور لگن', 'difficulty' => 'متوسط', 'equipment' => 'بدون تجهیزات', 'type' => 'Core / کاردیو'],
        'tips' => ['لگن ثابت.', 'زانو به آرنج مخالف.', 'Core سفت.'],
        'setup' => ['پلانک روی دست یا آرنج.', 'بدن صاف.', 'پا عرض لگن.'],
        'execution' => ['زانو راست به آرنج چپ.', 'بازگشت و تعویض.', 'تکرار تناوبی.', 'بدون چرخش لگن.'],
        'breathing' => 'بازدم در جمع — دم باز.',
        'muscles' => ['اصلی: obliques، abs', 'کمکی: hip flexors', 'تثبیت: shoulders'],
        'mistakes' => [['لگن می‌چرخد', 'ثبات'], ['زانو کم', 'تماس آرنج'], ['کمر افتاده', 'Core سفت']],
        'program' => [['Core', '۳–۴', '۱۰–۱۵ هر طرف', '۳۰–۴۵ث'], ['HIIT', '۳', '۳۰ث', '۲۰ث'], ['استقامت', '۳', '۲۰', '۳۰ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پلانک جانبی', 'slug' => 'پلانک-جانبی']],
        'faqs' => [['q' => 'آرنج یا دست؟', 'a' => 'دست دامنه بیشتر؛ آرنج راحت‌تر برای مبتدی.']],
        'summary' => 'جمع زانو پلانک برای مورب‌ها و Core پویا.',
        'summary_keys' => 'لگن ثابت | زانو به آرنج | Core سفت',
        'meta' => [
            'main_muscle' => 'obliques', 'secondary_muscle_keys' => ['abs', 'hip_flexors'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'dynamic_plank', 'body_engagement' => 'core_dominant',
            'mechanics_type' => 'compound', 'force_type' => 'dynamic', 'plane_of_motion' => 'transverse', 'laterality' => 'alternating',
            'posture' => 'plank', 'grip_type' => 'none', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'core_spine',
            'muscle_targets' => ['obliques' => 90, 'abs' => 75, 'hip_flexors' => 50, 'shoulder_anterior' => 30],
            'met' => 5, 'movement_distance_cm' => 35, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'endurance', 'recommended_sets' => '3-4',
            'rep_range_strength' => '', 'rep_range_hypertrophy' => '10-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 45, 'tempo' => '2-1-2',
            'short_description' => 'جمع زانو پلانک برای مورب‌ها، شکم و Core پویا.',
            'target_area' => 'مورب‌ها و شکم',
        ],
        'rank_extra' => 'Core پویا با پلانک.',
    ]);

    $add([
        'image_key' => 'exercise-batch4-20',
        'slug' => 'پرس-سینه-دست-جمع',
        'title' => 'پرس سینه دست جمع',
        'aliases' => ['Close Grip Bench Press', 'Close Grip DB Press', 'Narrow Grip Press', 'پرس دست جمع'],
        'intro' => '<strong>پرس سینه دست جمع</strong> فشار افقی با گرفتن دست جمع برای پشت بازو و سینه داخلی است. در روز سینه/Arms سالن‌های ایرانی مکمل پرس معمولی محسوب می‌شود.',
        'caption' => 'پرس سینه دست جمع — دست جمع، آرنج نزدیک',
        'quick' => ['main' => 'پشت بازو', 'secondary' => 'سینه داخلی، سرشانه', 'difficulty' => 'متوسط', 'equipment' => 'هالتر یا دمبل، نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['دست جمع عرض شانه یا کمتر.', 'آرنج نزدیک بدن.', 'پایین به خط پایین سینه.'],
        'setup' => ['درازکش روی نیمکت.', 'گرفتن جمع روی میله/دمبل.', 'کتف جمع، پا ثابت.'],
        'execution' => ['پایین کنترل به سینه.', 'آرنج نزدیک.', 'بازدم فشار بالا.', 'بدون قفل سخت آرنج.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: triceps', 'کمکی: chest inner، anterior deltoid', 'تثبیت: Core'],
        'mistakes' => [['دست خیلی جمع', 'عرض شانه'], ['آرنج باز', 'نزدیک بدن'], ['کتف شل', 'جمع کتف']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۶۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'پرس سینه با دمبل', 'slug' => 'پرس-سینه-با-دمبل']],
        'faqs' => [['q' => 'فقط triceps؟', 'a' => 'triceps اصلی؛ سینه داخلی و سرشانه کمکی.']],
        'summary' => 'پرس دست جمع برای پشت بازو و سینه داخلی.',
        'summary_keys' => 'دست جمع | آرنج نزدیک | کتف جمع',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => ['chest', 'shoulder_anterior'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'narrow', 'resistance_profile' => 'free_weight', 'joint_focus' => 'elbow_shoulder',
            'muscle_targets' => ['triceps' => 90, 'chest_middle' => 55, 'chest_inner' => 50, 'shoulder_anterior' => 35],
            'met' => 5.5, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '5-8', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پرس سینه دست جمع برای پشت بازو، سینه داخلی و قدرت فشار.',
            'target_area' => 'پشت بازو و سینه',
        ],
        'rank_extra' => 'triceps با پرس دست جمع.',
    ]);

    return $defs;
}
}
