// GymAI Popular — BATCH 14 (20 حرکت — حرکات 241 تا 260)
// Code Snippets: Run everywhere | بدون تگ php

if (!function_exists('gymai_pop20_batch14_definitions')) {
function gymai_pop20_batch14_definitions() {
    $base_img = 'https://gymaipro.ir/wp-content/uploads/2026/08/';
    $defs = [];
    $add = function (array $row) use (&$defs, $base_img) {
        if (empty($row['image'])) {
            $key = !empty($row['image_key']) ? $row['image_key'] : ('exercise-batch14-' . str_pad((string) (count($defs) + 1), 2, '0', STR_PAD_LEFT));
            $row['image'] = $base_img . $key . '.jpg';
        }
        $defs[] = $row;
    };

    $add([
        'image_key' => 'exercise-batch14-01',
        'slug' => 'شراگ-پشت-دمبل',
        'title' => 'شراگ پشت دمبل',
        'aliases' => ['Behind Body Shrug', 'BehindBodyShrug', 'شراگ پشت دمبل', 'Behind the Back Shrug', 'شراگ پشت'],
        'intro' => '<strong>شراگ پشت دمبل</strong> (Behind Body Shrug) دمبل‌ها پشت بدن؛ زاویه متفاوت برای ذوزنقه. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل اجرا می‌شود.',
        'caption' => 'شراگ پشت دمبل — کول، اجرای کنترل‌شده',
        'quick' => ['main' => 'کول', 'secondary' => 'ساعد', 'difficulty' => 'متوسط', 'equipment' => 'دمبل', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی کول در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: کول', 'کمکی: ساعد', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'شراگ دمبل', 'slug' => 'شراگ-دمبل']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'شراگ پشت دمبل برای کول و کول در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'کول | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'traps', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['traps' => 94, 'forearms' => 35],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'شراگ پشت بدن برای تله بالا.',
            'target_area' => 'کول',
        ],
        'rank_extra' => 'تله متفاوت.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-02',
        'slug' => 'شراگ-هالتر',
        'title' => 'شراگ هالتر',
        'aliases' => ['Barbell Shrug', 'BarbellShrug', 'شراگ هالتر', 'شراگ باربل', 'کول هالتر شراگ'],
        'intro' => '<strong>شراگ هالتر</strong> (Barbell Shrug) بالا بردن شانه با هالتر؛ کلاسیک روز پشت یا کول. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'شراگ هالتر — کول، اجرای کنترل‌شده',
        'quick' => ['main' => 'کول', 'secondary' => 'ساعد', 'difficulty' => 'مبتدی', 'equipment' => 'هالتر', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی کول در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: کول', 'کمکی: ساعد', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کول هالتر', 'slug' => 'کول-هالتر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'شراگ هالتر برای کول و کول در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'کول | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'traps', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'beginner', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['traps' => 95, 'forearms' => 40],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'شراگ هالتر برای ذوزنقه بالا.',
            'target_area' => 'کول',
        ],
        'rank_extra' => 'تله هالتر.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-03',
        'slug' => 'آپرایت-رو-دمبل',
        'title' => 'آپرایت رو دمبل',
        'aliases' => ['Dumbbell Upright Row', 'DumbbellUprightRow', 'آپرایت رو دمبل', 'آپرایت رو', 'Upright Row', 'کول دمبل کششی'],
        'intro' => '<strong>آپرایت رو دمبل</strong> (Dumbbell Upright Row) کشش عمودی دمبل تا سینه؛ جانب شانه و تله — آرنج بالاتر از مچ. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل اجرا می‌شود.',
        'caption' => 'آپرایت رو دمبل — سرشانه جانب، اجرای کنترل‌شده',
        'quick' => ['main' => 'سرشانه جانب', 'secondary' => 'traps', 'difficulty' => 'متوسط', 'equipment' => 'دمبل', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سرشانه جانب در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سرشانه جانب', 'کمکی: traps', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کول دمبل', 'slug' => 'کول-دمبل']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'آپرایت رو دمبل برای سرشانه و کول و سرشانه جانب در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سرشانه جانب | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_lateral', 'secondary_muscle_keys' => ['traps'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_lateral' => 80, 'traps' => 70],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'آپرایت رو با دمبل.',
            'target_area' => 'سرشانه و کول',
        ],
        'rank_extra' => 'جانب + کول.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-04',
        'slug' => 'آپرایت-رو-کابل',
        'title' => 'آپرایت رو کابل',
        'aliases' => ['Cable Upright Row', 'CableUprightRow', 'آپرایت رو کابل'],
        'intro' => '<strong>آپرایت رو کابل</strong> (Cable Upright Row) کشش عمودی با کابل؛ کنترل بهتر از هالتر. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'آپرایت رو کابل — سرشانه جانب، اجرای کنترل‌شده',
        'quick' => ['main' => 'سرشانه جانب', 'secondary' => 'traps', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سرشانه جانب در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سرشانه جانب', 'کمکی: traps', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'آپرایت رو دمبل', 'slug' => 'آپرایت-رو-دمبل']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'آپرایت رو کابل برای سرشانه و سرشانه جانب در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سرشانه جانب | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_lateral', 'secondary_muscle_keys' => ['traps'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_lateral' => 78, 'traps' => 68],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'آپرایت رو سیمکش با کشش مداوم.',
            'target_area' => 'سرشانه',
        ],
        'rank_extra' => 'کشش مداوم.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-05',
        'slug' => 'تی-ریز',
        'title' => 'تی ریز',
        'aliases' => ['T Raise', 'TRaise', 'تی ریز'],
        'intro' => '<strong>تی ریز</strong> (T Raise) دست‌ها به طرفین در وضعیت T؛ prehab و اصلاح وضعیت. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل اجرا می‌شود.',
        'caption' => 'تی ریز — سرشانه پشت، اجرای کنترل‌شده',
        'quick' => ['main' => 'سرشانه پشت', 'secondary' => 'پشت میانی', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی سرشانه پشت در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سرشانه پشت', 'کمکی: پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'وای ریز', 'slug' => 'وای-ریز']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'تی ریز برای سرشانه پشت و سرشانه پشت در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سرشانه پشت | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_posterior', 'secondary_muscle_keys' => ['rhomboids'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'prone', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_posterior' => 88, 'rhomboids' => 55],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'T Raise برای دلتوئید خلفی.',
            'target_area' => 'سرشانه پشت',
        ],
        'rank_extra' => 'پشت شانه.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-06',
        'slug' => 'اکسترنال-روتیشن',
        'title' => 'اکسترنال روتیشن',
        'aliases' => ['External Rotation', 'ExternalRotation', 'اکسترنال روتیشن', 'چرخش خارجی شانه', 'External Rotation Cuff', 'کاف اکسترنال'],
        'intro' => '<strong>اکسترنال روتیشن</strong> (External Rotation) حرکت درمانی برای عضله اینفراسپیاتوس؛ گرم‌کردن شانه ضروری. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش و دمبل اجرا می‌شود.',
        'caption' => 'اکسترنال روتیشن — سرشانه پشت، اجرای کنترل‌شده',
        'quick' => ['main' => 'سرشانه پشت', 'secondary' => 'ساعد', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش و دمبل', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی سرشانه پشت در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سرشانه پشت', 'کمکی: ساعد', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'فیس پول', 'slug' => 'فیس-پول']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'اکسترنال روتیشن برای کاف روتاتور و سرشانه پشت در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سرشانه پشت | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_posterior', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable', 'dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'rotation', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_posterior' => 85, 'rotator_cuff' => 95],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'چرخش خارجی شانه برای کاف.',
            'target_area' => 'کاف روتاتور',
        ],
        'rank_extra' => 'سلامت کاف.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-07',
        'slug' => 'اینترنال-روتیشن',
        'title' => 'اینترنال روتیشن',
        'aliases' => ['Internal Rotation', 'InternalRotation', 'اینترنال روتیشن', 'چرخش داخلی شانه', 'Internal Rotation Cuff'],
        'intro' => '<strong>اینترنال روتیشن</strong> (Internal Rotation) مکمل اکسترنال روتیشن برای تعادل عضلات چرخاننده. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'اینترنال روتیشن — سرشانه قدامی، اجرای کنترل‌شده',
        'quick' => ['main' => 'سرشانه قدامی', 'secondary' => 'ساعد', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی سرشانه قدامی در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سرشانه قدامی', 'کمکی: ساعد', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'اکسترنال روتیشن', 'slug' => 'اکسترنال-روتیشن']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'اینترنال روتیشن برای کاف روتاتور و سرشانه قدامی در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سرشانه قدامی | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_anterior', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'rotation', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_anterior' => 60, 'rotator_cuff' => 90],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'چرخش داخلی شانه برای تعادل کاف.',
            'target_area' => 'کاف روتاتور',
        ],
        'rank_extra' => 'تعادل کاف.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-08',
        'slug' => 'بند-پول-اپارت',
        'title' => 'بند پول اپارت',
        'aliases' => ['Band Pull Apart', 'BandPullApart', 'بند پول اپارت', 'Pull Apart', 'کش پول اپارت', 'بند پول‌اپارت'],
        'intro' => '<strong>بند پول اپارت</strong> (Band Pull Apart) باز کردن کش جلوی سینه؛ گرم‌کردن روزانه شانه و کتف. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'بند پول اپارت — سرشانه پشت، اجرای کنترل‌شده',
        'quick' => ['main' => 'سرشانه پشت', 'secondary' => 'پشت میانی', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی سرشانه پشت در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سرشانه پشت', 'کمکی: پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'فیس پول', 'slug' => 'فیس-پول']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'بند پول اپارت برای پشت شانه و سرشانه پشت در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سرشانه پشت | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_posterior', 'secondary_muscle_keys' => ['rhomboids'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_posterior' => 85, 'rhomboids' => 60],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پول اپارت با کش برای posture.',
            'target_area' => 'پشت شانه',
        ],
        'rank_extra' => 'گرم‌کردن شانه.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-09',
        'slug' => 'ریورس-کراس-اور',
        'title' => 'ریورس کراس اور',
        'aliases' => ['Reverse Cable Crossover', 'ReverseCableCrossover', 'ریورس کراس اور', 'ریورس کراس', 'Reverse Crossover'],
        'intro' => '<strong>ریورس کراس اور</strong> (Reverse Cable Crossover) کراس از جلو به عقب برای پشت شانه؛ مکمل فیس پول. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'ریورس کراس اور — سرشانه پشت، اجرای کنترل‌شده',
        'quick' => ['main' => 'سرشانه پشت', 'secondary' => 'پشت میانی', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی سرشانه پشت در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سرشانه پشت', 'کمکی: پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کراس باز سیمکش', 'slug' => 'کراس-باز-سیمکش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'ریورس کراس اور برای سرشانه پشت و سرشانه پشت در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سرشانه پشت | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_posterior', 'secondary_muscle_keys' => ['rhomboids'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_posterior' => 92, 'rhomboids' => 45],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'کراس اور معکوس برای دلت خلفی.',
            'target_area' => 'سرشانه پشت',
        ],
        'rank_extra' => 'دلت خلفی.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-10',
        'slug' => 'میلیتری-پرس',
        'title' => 'میلیتری پرس',
        'aliases' => ['Military Press', 'MilitaryPress', 'میلیتری پرس', 'پرس نظامی', 'استریت پرس'],
        'intro' => '<strong>میلیتری پرس</strong> (Military Press) پرس سر هالتر ایستاده با پا جفت؛ استاندارد قدرت شانه. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'میلیتری پرس — سرشانه قدامی، اجرای کنترل‌شده',
        'quick' => ['main' => 'سرشانه قدامی', 'secondary' => 'پشت بازو، Core', 'difficulty' => 'متوسط', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سرشانه قدامی در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سرشانه قدامی', 'کمکی: پشت بازو، Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پرس سرشانه با هالتر', 'slug' => 'پرس-سرشانه-با-هالتر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'میلیتری پرس برای سرشانه و سرشانه قدامی در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سرشانه قدامی | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_anterior', 'secondary_muscle_keys' => ['triceps', 'abs'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_anterior' => 92, 'triceps' => 50, 'abs' => 35],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'میلیتری پرس کلاسیک ایستاده.',
            'target_area' => 'سرشانه',
        ],
        'rank_extra' => 'قدرت شانه.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-11',
        'slug' => 'اسکال-کراشر',
        'title' => 'اسکال کراشر',
        'aliases' => ['Skull Crusher', 'SkullCrusher', 'اسکال کراشر', 'اسکال‌کراشر', 'Lying Tricep Extension', 'فرنچ پرس خوابیده'],
        'intro' => '<strong>اسکال کراشر</strong> (Skull Crusher) اکستنشن خوابیده با EZ یا هالتر به سمت پیشانی؛ کلاسیک حجم تریسپس. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر و نیمکت اجرا می‌شود.',
        'caption' => 'اسکال کراشر — پشت بازو، اجرای کنترل‌شده',
        'quick' => ['main' => 'پشت بازو', 'secondary' => '—', 'difficulty' => 'متوسط', 'equipment' => 'هالتر و نیمکت', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی پشت بازو در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: پشت بازو', 'کمکی: عضلات کمکی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت بازو دمبل خوابیده', 'slug' => 'پشت-بازو-دمبل-خوابیده']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'اسکال کراشر برای پشت بازو و پشت بازو در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'پشت بازو | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => [],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'elbow_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['triceps' => 95],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'اسکال کراشر برای پشت بازو بلند.',
            'target_area' => 'پشت بازو',
        ],
        'rank_extra' => 'تریسپس بلند.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-12',
        'slug' => 'فرنچ-پرس',
        'title' => 'فرنچ پرس',
        'aliases' => ['French Press', 'FrenchPress', 'فرنچ پرس', 'Overhead EZ Extension'],
        'intro' => '<strong>فرنچ پرس</strong> (French Press) اکستنشن پشت‌سر با هالتر یا EZ؛ تاکید سر بلند تریسپس. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'فرنچ پرس — پشت بازو، اجرای کنترل‌شده',
        'quick' => ['main' => 'پشت بازو', 'secondary' => '—', 'difficulty' => 'متوسط', 'equipment' => 'هالتر', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی پشت بازو در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: پشت بازو', 'کمکی: عضلات کمکی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت بازو پشت سر', 'slug' => 'پشت-بازو-پشت-سر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'فرنچ پرس برای پشت بازو و پشت بازو در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'پشت بازو | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => [],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'elbow_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['triceps' => 94],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'فرنچ پرس نشسته/ایستاده.',
            'target_area' => 'پشت بازو',
        ],
        'rank_extra' => 'سر بلند تریسپس.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-13',
        'slug' => 'پوشداون-طناب',
        'title' => 'پوش‌داون طناب',
        'aliases' => ['Rope Pushdown', 'RopePushdown', 'پوش‌داون طناب', 'تریسپس طناب', 'Rope Tricep Pushdown', 'پشت بازو طناب'],
        'intro' => '<strong>پوش‌داون طناب</strong> (Rope Pushdown) پشت بازو سیمکش با طناب و باز کردن در پایین؛ پمپ عالی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'پوش‌داون طناب — پشت بازو، اجرای کنترل‌شده',
        'quick' => ['main' => 'پشت بازو', 'secondary' => '—', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی پشت بازو در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: پشت بازو', 'کمکی: عضلات کمکی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت بازو سیمکش', 'slug' => 'پشت-بازو-سیمکش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پوش‌داون طناب برای پشت بازو و پشت بازو در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'پشت بازو | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => [],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'elbow_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['triceps' => 93],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پوش‌داون طناب برای انقباض بیرونی.',
            'target_area' => 'پشت بازو',
        ],
        'rank_extra' => 'پمپ تریسپس.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-14',
        'slug' => 'پوشداون-میله',
        'title' => 'پوش‌داون میله',
        'aliases' => ['Bar Pushdown', 'BarPushdown', 'پوش‌داون میله', 'پشت بازو میله', 'Straight Bar Pushdown'],
        'intro' => '<strong>پوش‌داون میله</strong> (Bar Pushdown) نسخه میله‌ای پشت بازو سیمکش؛ برای وزنه سنگین‌تر از طناب. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'پوش‌داون میله — پشت بازو، اجرای کنترل‌شده',
        'quick' => ['main' => 'پشت بازو', 'secondary' => '—', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی پشت بازو در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: پشت بازو', 'کمکی: عضلات کمکی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پوش‌داون طناب', 'slug' => 'پوشداون-طناب']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پوش‌داون میله برای پشت بازو و پشت بازو در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'پشت بازو | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => [],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'elbow_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['triceps' => 92],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پوش‌داون میله مستقیم یا EZ.',
            'target_area' => 'پشت بازو',
        ],
        'rank_extra' => 'تریسپس سنگین.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-15',
        'slug' => 'دراگ-کرل',
        'title' => 'دراگ کرل',
        'aliases' => ['Drag Curl', 'DragCurl', 'دراگ کرل', 'کرل دراگ'],
        'intro' => '<strong>دراگ کرل</strong> (Drag Curl) کرل با کشیدن میله روی تنه به بالا؛ آرنج عقب می‌رود. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'دراگ کرل — جلوبازو، اجرای کنترل‌شده',
        'quick' => ['main' => 'جلوبازو', 'secondary' => 'ساعد', 'difficulty' => 'متوسط', 'equipment' => 'هالتر', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی جلوبازو در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: جلوبازو', 'کمکی: ساعد', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'جلو بازو هالتر', 'slug' => 'جلو-بازو-هالتر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'دراگ کرل برای جلوبازو و جلوبازو در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'جلوبازو | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'biceps', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'elbow_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['biceps' => 94, 'forearms' => 30],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'دراگ کرل برای سر بلند جلوبازو.',
            'target_area' => 'جلوبازو',
        ],
        'rank_extra' => 'سر بلند.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-16',
        'slug' => 'زوتمن-کرل',
        'title' => 'زوتمن کرل',
        'aliases' => ['Zottman Curl', 'ZottmanCurl', 'زوتمن کرل', 'کرل زوتمن'],
        'intro' => '<strong>زوتمن کرل</strong> (Zottman Curl) بالا سوپین، پایین پرونیت؛ ترکیب کرل و ساعد معکوس. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل اجرا می‌شود.',
        'caption' => 'زوتمن کرل — جلوبازو، اجرای کنترل‌شده',
        'quick' => ['main' => 'جلوبازو', 'secondary' => 'ساعد', 'difficulty' => 'متوسط', 'equipment' => 'دمبل', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی جلوبازو در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: جلوبازو', 'کمکی: ساعد', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'جلو بازو دمبل', 'slug' => 'جلو-بازو-دمبل']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'زوتمن کرل برای جلوبازو و ساعد و جلوبازو در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'جلوبازو | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'biceps', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'elbow_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['biceps' => 85, 'forearms' => 75],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'زوتمن کرل برای جلوبازو + ساعد.',
            'target_area' => 'جلوبازو و ساعد',
        ],
        'rank_extra' => 'بازو + ساعد.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-17',
        'slug' => 'مچ-خم',
        'title' => 'مچ خم',
        'aliases' => ['Wrist Curl', 'WristCurl', 'مچ خم', 'ساعد مچ خم', 'مچ هالتر'],
        'intro' => '<strong>مچ خم</strong> (Wrist Curl) کرل مچ کف‌دست رو بالا؛ قدرت grip و حجم ساعد. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر و دمبل اجرا می‌شود.',
        'caption' => 'مچ خم — ساعد، اجرای کنترل‌شده',
        'quick' => ['main' => 'ساعد', 'secondary' => '—', 'difficulty' => 'مبتدی', 'equipment' => 'هالتر و دمبل', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی ساعد در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: ساعد', 'کمکی: عضلات کمکی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'ساعد هالتر', 'slug' => 'ساعد-هالتر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'مچ خم برای ساعد و ساعد در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'ساعد | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'forearms', 'secondary_muscle_keys' => [],
            'difficulty' => 'beginner', 'equipment_keys' => ['barbell', 'dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'wrist_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['forearms' => 95],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'مچ خم برای فلکسور ساعد.',
            'target_area' => 'ساعد',
        ],
        'rank_extra' => 'فلکسور ساعد.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-18',
        'slug' => 'مچ-باز',
        'title' => 'مچ باز',
        'aliases' => ['Reverse Wrist Curl', 'ReverseWristCurl', 'مچ باز', 'مچ معکوس'],
        'intro' => '<strong>مچ باز</strong> (Reverse Wrist Curl) کرل مچ کف‌دست رو پایین؛ تعادل با مچ خم. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر و دمبل اجرا می‌شود.',
        'caption' => 'مچ باز — ساعد، اجرای کنترل‌شده',
        'quick' => ['main' => 'ساعد', 'secondary' => '—', 'difficulty' => 'مبتدی', 'equipment' => 'هالتر و دمبل', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی ساعد در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: ساعد', 'کمکی: عضلات کمکی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'ساعد معکوس', 'slug' => 'ساعد-معکوس']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'مچ باز برای ساعد و ساعد در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'ساعد | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'forearms', 'secondary_muscle_keys' => [],
            'difficulty' => 'beginner', 'equipment_keys' => ['barbell', 'dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'wrist_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['forearms' => 95],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'مچ باز برای اکستنسور ساعد.',
            'target_area' => 'ساعد',
        ],
        'rank_extra' => 'اکستنسور.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-19',
        'slug' => 'پریچر-دمبل',
        'title' => 'پریچر دمبل',
        'aliases' => ['Dumbbell Preacher Curl', 'DumbbellPreacherCurl', 'پریچر دمبل'],
        'intro' => '<strong>پریچر دمبل</strong> (Dumbbell Preacher Curl) کرل روی نیمکت پریچر با یک دمبل؛ رفع عدم تقارن. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل و نیمکت اجرا می‌شود.',
        'caption' => 'پریچر دمبل — جلوبازو، اجرای کنترل‌شده',
        'quick' => ['main' => 'جلوبازو', 'secondary' => '—', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل و نیمکت', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی جلوبازو در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: جلوبازو', 'کمکی: عضلات کمکی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'جلو بازو پریچر', 'slug' => 'جلو-بازو-پریچر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پریچر دمبل برای جلوبازو و جلوبازو در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'جلوبازو | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'biceps', 'secondary_muscle_keys' => [],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'elbow_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['biceps' => 96],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پریچر با دمبل تک‌دست.',
            'target_area' => 'جلوبازو',
        ],
        'rank_extra' => 'تک‌دست.',
    ]);

    $add([
        'image_key' => 'exercise-batch14-20',
        'slug' => 'اسکات-کرل',
        'title' => 'اسکات کرل',
        'aliases' => ['Scott Curl', 'ScottCurl', 'اسکات کرل', 'لری اسکات کرل'],
        'intro' => '<strong>اسکات کرل</strong> (Scott Curl) نام دیگر پریچر کرل به افتخار لری اسکات؛ جلوبازو بدون تقلب. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر و نیمکت اجرا می‌شود.',
        'caption' => 'اسکات کرل — جلوبازو، اجرای کنترل‌شده',
        'quick' => ['main' => 'جلوبازو', 'secondary' => 'ساعد', 'difficulty' => 'مبتدی', 'equipment' => 'هالتر و نیمکت', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی جلوبازو در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: جلوبازو', 'کمکی: ساعد', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'جلو بازو پریچر', 'slug' => 'جلو-بازو-پریچر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'اسکات کرل برای جلوبازو و جلوبازو در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'جلوبازو | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'biceps', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'beginner', 'equipment_keys' => ['barbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'elbow_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['biceps' => 95],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'اسکات کرل همان پریچر کلاسیک.',
            'target_area' => 'جلوبازو',
        ],
        'rank_extra' => 'پریچر کلاسیک.',
    ]);

    return $defs;
}
}
