// GymAI Popular — BATCH 7 (20 حرکت — حرکات 101 تا 120)
// Code Snippets: Run everywhere | بدون تگ php

if (!function_exists('gymai_pop20_batch7_definitions')) {
function gymai_pop20_batch7_definitions() {
    $base_img = 'https://gymaipro.ir/wp-content/uploads/2026/07/';
    $defs = [];
    $add = function (array $row) use (&$defs, $base_img) {
        if (empty($row['image'])) {
            $key = !empty($row['image_key']) ? $row['image_key'] : ('exercise-batch7-' . str_pad((string) (count($defs) + 1), 2, '0', STR_PAD_LEFT));
            $row['image'] = $base_img . $key . '.jpg';
        }
        $defs[] = $row;
    };

    $add([
        'image_key' => 'exercise-batch7-01',
        'slug' => 'اسکات-جعبه',
        'title' => 'اسکات جعبه',
        'aliases' => ['Box Squat', 'BoxSquat', 'اسکات جعبه'],
        'intro' => '<strong>اسکات جعبه</strong> (Box Squat) اسکات با نشست کنترل‌شده روی باکس یا نیمکت؛ در پاورلیفتینگ و بدنسازی برای یادگیری عمق و خروج از نقطه مرده بسیار رایج است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر و نیمکت اجرا می‌شود.',
        'caption' => 'اسکات جعبه — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، همسترینگ، Core', 'difficulty' => 'متوسط', 'equipment' => 'هالتر و نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن، همسترینگ، Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'اسکات گابلت', 'slug' => 'اسکات-گابلت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'اسکات جعبه برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'hamstrings', 'abs'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'squat', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 90, 'glutes' => 80, 'hamstrings' => 50],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'اسکات جعبه برای قدرت از عمق و تکنیک امن.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'یادگیری عمق اسکات.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-02',
        'slug' => 'اسکات-بلغاری-هالتر',
        'title' => 'اسکات بلغاری هالتر',
        'aliases' => ['Barbell Bulgarian Split Squat', 'BarbellBulgarianSplitSquat', 'اسکات بلغاری هالتر'],
        'intro' => '<strong>اسکات بلغاری هالتر</strong> (Barbell Bulgarian Split Squat) اسپلیت اسکات با هالتر پشت یا جلو؛ یکی از قوی‌ترین حرکات تک‌پا برای چهارسر و باسن در سالن‌های حرفه‌ای. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'اسکات بلغاری هالتر — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، همسترینگ', 'difficulty' => 'متوسط', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن، همسترینگ', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'اسپلیت اسکات بلغاری', 'slug' => 'اسپلیت-اسکات-بلغاری']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'اسکات بلغاری هالتر برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'hamstrings'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'lunge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 90, 'glutes' => 85, 'hamstrings' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'بلغاری با هالتر برای قدرت تک‌پا.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'قدرت تک‌پا.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-03',
        'slug' => 'اسکات-کوزاک',
        'title' => 'اسکات کوزاک',
        'aliases' => ['Cossack Squat', 'CossackSquat', 'اسکات کوزاک'],
        'intro' => '<strong>اسکات کوزاک</strong> (Cossack Squat) اسکات جانبی عمیق با یک پا باز؛ برای پراپشن، انعطاف و تقویت پا در تمرین‌های فانکشنال محبوب است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'اسکات کوزاک — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، adductors', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن، adductors', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'لانج جانبی', 'slug' => 'لانج-جانبی']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'اسکات کوزاک برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'adductors'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'squat', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 80, 'glutes' => 70, 'adductors' => 60],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'اسکات کوزاک برای دامنه جانبی و انعطاف.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'انعطاف و پا.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-04',
        'slug' => 'اسکات-تک-پا-باکس',
        'title' => 'اسکات تک پا باکس',
        'aliases' => ['Single Leg Box Squat', 'SingleLegBoxSquat', 'اسکات تک پا باکس'],
        'intro' => '<strong>اسکات تک پا باکس</strong> (Single Leg Box Squat) اسکات با یک پا و نشست کنترل‌شده روی باکس؛ مرحله قبل از پistol squat برای تقویت چهارسر و تعادل. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با نیمکت و وزن بدن اجرا می‌شود.',
        'caption' => 'اسکات تک پا باکس — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، Core', 'difficulty' => 'پیشرفته', 'equipment' => 'نیمکت و وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم نیمکت و وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن، Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'اسکات کوزاک', 'slug' => 'اسکات-کوزاک']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'اسکات تک پا باکس برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'abs'],
            'difficulty' => 'advanced', 'equipment_keys' => ['bench', 'bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'squat', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 88, 'glutes' => 75, 'abs' => 40],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'اسکات تک‌پا روی باکس برای تعادل و قدرت.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'تعادل و قدرت.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-05',
        'slug' => 'لندماین-اسکات',
        'title' => 'لندماین اسکات',
        'aliases' => ['Landmine Squat', 'LandmineSquat', 'لندماین اسکات'],
        'intro' => '<strong>لندماین اسکات</strong> (Landmine Squat) اسکات با انتهای هالتر در گوشه؛ برای مبتدی‌ها و کسانی که اسکات آزاد سخت است گزینه عالی در سالن ایرانی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'لندماین اسکات — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، Core', 'difficulty' => 'مبتدی', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن، Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'اسکات گابلت', 'slug' => 'اسکات-گابلت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'لندماین اسکات برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'abs'],
            'difficulty' => 'beginner', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'squat', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 85, 'glutes' => 75, 'abs' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'لندماین اسکات با فشار کمتر روی کمر.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'اسکات دوست‌دار کمر.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-06',
        'slug' => 'لگ-پرس-تک-پا',
        'title' => 'لگ پرس تک پا',
        'aliases' => ['Single Leg Press', 'SingleLegPress', 'لگ پرس تک پا'],
        'intro' => '<strong>لگ پرس تک پا</strong> (Single Leg Press) پرس پا با یک پا روی دستگاه؛ برای تقویت جداگانه هر طرف و اصلاح عدم تقارن بسیار کاربردی است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'لگ پرس تک پا — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن', 'difficulty' => 'متوسط', 'equipment' => 'دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'لگ پرس', 'slug' => 'لگ-پرس']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'لگ پرس تک پا برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'squat', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 88, 'glutes' => 70],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'لگ پرس تک‌پا برای رفع عدم تقارن.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'عدم تقارن پا.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-07',
        'slug' => 'همسترینگ-نوردیک',
        'title' => 'همسترینگ نوردیک',
        'aliases' => ['Nordic Hamstring Curl', 'NordicHamstringCurl', 'همسترینگ نوردیک'],
        'intro' => '<strong>همسترینگ نوردیک</strong> (Nordic Hamstring Curl) حرکت اکسنتریک همسترینگ با زانو روی زمین؛ برای پیشگیری از آسیب و قدرت پشت پا در فوتبال و بدنسازی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن و نیمکت اجرا می‌شود.',
        'caption' => 'همسترینگ نوردیک — همسترینگ، اجرای کنترل‌شده',
        'quick' => ['main' => 'همسترینگ', 'secondary' => 'باسن، calves', 'difficulty' => 'پیشرفته', 'equipment' => 'وزن بدن و نیمکت', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی همسترینگ در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: همسترینگ', 'کمکی: باسن، calves', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت پا خوابیده', 'slug' => 'پشت-پا-خوابیده']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'همسترینگ نوردیک برای پشت پا و همسترینگ در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'همسترینگ | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'hamstrings', 'secondary_muscle_keys' => ['glutes', 'calves'],
            'difficulty' => 'advanced', 'equipment_keys' => ['bodyweight', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'knee_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'kneeling', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['hamstrings' => 95, 'glutes' => 40],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'نوردیک کرل سخت‌ترین تست همسترینگ.',
            'target_area' => 'پشت پا',
        ],
        'rank_extra' => 'پیشگیری آسیب.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-08',
        'slug' => 'پشت-پا-خوابیده',
        'title' => 'پشت پا خوابیده',
        'aliases' => ['Lying Leg Curl', 'LyingLegCurl', 'پشت پا خوابیده'],
        'intro' => '<strong>پشت پا خوابیده</strong> (Lying Leg Curl) کرل پا درازکش روی دستگاه؛ استاندارد روز پا برای جداسازی همسترینگ در اکثر سالن‌ها. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'پشت پا خوابیده — همسترینگ، اجرای کنترل‌شده',
        'quick' => ['main' => 'همسترینگ', 'secondary' => 'calves', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی همسترینگ در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: همسترینگ', 'کمکی: calves', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت پا ایستاده', 'slug' => 'پشت-پا-ایستاده']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پشت پا خوابیده برای پشت پا و همسترینگ در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'همسترینگ | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'hamstrings', 'secondary_muscle_keys' => ['calves'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'knee_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'prone', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['hamstrings' => 95],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پشت پا خوابیده برای ایزوله همسترینگ.',
            'target_area' => 'پشت پا',
        ],
        'rank_extra' => 'ایزوله همسترینگ.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-09',
        'slug' => 'پشت-پا-نشسته-دستگاه',
        'title' => 'پشت پا نشسته دستگاه',
        'aliases' => ['Seated Leg Curl', 'SeatedLegCurl', 'پشت پا نشسته دستگاه'],
        'intro' => '<strong>پشت پا نشسته دستگاه</strong> (Seated Leg Curl) کرل پا نشسته؛ زاویه کشش متفاوت از حالت خوابیده و برای حجم پشت پا مکمل خوبی است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'پشت پا نشسته دستگاه — همسترینگ، اجرای کنترل‌شده',
        'quick' => ['main' => 'همسترینگ', 'secondary' => 'calves', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی همسترینگ در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: همسترینگ', 'کمکی: calves', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت پا خوابیده', 'slug' => 'پشت-پا-خوابیده']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پشت پا نشسته دستگاه برای پشت پا و همسترینگ در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'همسترینگ | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'hamstrings', 'secondary_muscle_keys' => ['calves'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'knee_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['hamstrings' => 92, 'calves' => 25],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پشت پا نشسته برای کشش بیشتر همسترینگ.',
            'target_area' => 'پشت پا',
        ],
        'rank_extra' => 'زاویه متفاوت.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-10',
        'slug' => 'هیپ-تراست-هالتر',
        'title' => 'هیپ تراست هالتر',
        'aliases' => ['Barbell Hip Thrust', 'BarbellHipThrust', 'هیپ تراست هالتر'],
        'intro' => '<strong>هیپ تراست هالتر</strong> (Barbell Hip Thrust) بالا بردن لگن با هالتر روی باسن؛ یکی از مؤثرترین حرکات برای رشد گلوت در بدنسازی مدرن. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر و نیمکت اجرا می‌شود.',
        'caption' => 'هیپ تراست هالتر — باسن، اجرای کنترل‌شده',
        'quick' => ['main' => 'باسن', 'secondary' => 'همسترینگ، Core', 'difficulty' => 'متوسط', 'equipment' => 'هالتر و نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی باسن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: باسن', 'کمکی: همسترینگ، Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'هیپ تراست', 'slug' => 'هیپ-تراست']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'هیپ تراست هالتر برای باسن و باسن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'باسن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'glutes', 'secondary_muscle_keys' => ['hamstrings', 'abs'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'hip_extension', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['glutes' => 95, 'hamstrings' => 55, 'abs' => 30],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'هیپ تراست هالتر برای باسن قوی.',
            'target_area' => 'باسن',
        ],
        'rank_extra' => 'رشد باسن.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-11',
        'slug' => 'پل-باسن-تک-پا',
        'title' => 'پل باسن تک پا',
        'aliases' => ['Single Leg Glute Bridge', 'SingleLegGluteBridge', 'پل باسن تک پا'],
        'intro' => '<strong>پل باسن تک پا</strong> (Single Leg Glute Bridge) پل باسن با یک پا؛ در خانه و گرم‌کردن برای فعال‌سازی گلوت قبل از اسکات بسیار مفید است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'پل باسن تک پا — باسن، اجرای کنترل‌شده',
        'quick' => ['main' => 'باسن', 'secondary' => 'همسترینگ، Core', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی باسن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: باسن', 'کمکی: همسترینگ، Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پل باسن', 'slug' => 'پل-باسن']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پل باسن تک پا برای باسن و باسن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'باسن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'glutes', 'secondary_muscle_keys' => ['hamstrings', 'abs'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'hip_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['glutes' => 90, 'hamstrings' => 45],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پل تک‌پا برای فعال‌سازی باسن.',
            'target_area' => 'باسن',
        ],
        'rank_extra' => 'فعال‌سازی باسن.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-12',
        'slug' => 'لانج-جانبی',
        'title' => 'لانج جانبی',
        'aliases' => ['Lateral Lunge', 'LateralLunge', 'لانج جانبی'],
        'intro' => '<strong>لانج جانبی</strong> (Lateral Lunge) قدم پهل به کنار با خم زانو؛ حرکت عملکردی برای چابکی و تقویت پا در تمرین خانگی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل اجرا می‌شود.',
        'caption' => 'لانج جانبی — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، adductors', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن، adductors', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'لانج', 'slug' => 'لانج']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'لانج جانبی برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'adductors'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'lunge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 75, 'glutes' => 70, 'adductors' => 55],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'لانج جانبی برای پا و داخل ران.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'چابکی پا.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-13',
        'slug' => 'لانج-اسکی',
        'title' => 'لانج اسکی',
        'aliases' => ['Curtsy Lunge', 'CurtsyLunge', 'لانج اسکی'],
        'intro' => '<strong>لانج اسکی</strong> (Curtsy Lunge) لانج با پا عقب مورب؛ برای باسن میانی و تعادل در تمرین‌های زنانه و فانکشنال محبوب. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل اجرا می‌شود.',
        'caption' => 'لانج اسکی — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن', 'difficulty' => 'متوسط', 'equipment' => 'دمبل', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'لانج عقب', 'slug' => 'لانج-عقب']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'لانج اسکی برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'lunge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['glutes' => 85, 'quads' => 75],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'لانج اسکی برای باسن و پا.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'باسن و تعادل.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-14',
        'slug' => 'ساق-دونکی',
        'title' => 'ساق دونکی',
        'aliases' => ['Donkey Calf Raise', 'DonkeyCalfRaise', 'ساق دونکی'],
        'intro' => '<strong>ساق دونکی</strong> (Donkey Calf Raise) ساق با خم شدن تنه؛ کشش بیشتر روی گاستrocnemius در سالن‌های مجهز. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'ساق دونکی — ساق پا، اجرای کنترل‌شده',
        'quick' => ['main' => 'ساق پا', 'secondary' => '—', 'difficulty' => 'متوسط', 'equipment' => 'دستگاه', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی ساق پا در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: ساق پا', 'کمکی: عضلات کمکی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'ساق ایستاده', 'slug' => 'ساق-ایستاده']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'ساق دونکی برای ساق پا و ساق پا در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'ساق پا | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'calves', 'secondary_muscle_keys' => [],
            'difficulty' => 'intermediate', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'calf_raise', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['calves' => 95],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'ساق دونکی برای کشش عمیق ساق.',
            'target_area' => 'ساق پا',
        ],
        'rank_extra' => 'کشش ساق.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-15',
        'slug' => 'ددلیفت-تراپ-بار',
        'title' => 'ددلیفت تراپ بار',
        'aliases' => ['Trap Bar Deadlift', 'TrapBarDeadlift', 'ددلیفت تراپ بار'],
        'intro' => '<strong>ددلیفت تراپ بار</strong> (Trap Bar Deadlift) ددلیفت با هالتر شش‌گوش؛ موقعیت بدن مرکزتر و برای مبتدی و ورزشکار عملکردی ایده‌آل. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'ددلیفت تراپ بار — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، همسترینگ، lower_back', 'difficulty' => 'متوسط', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن، همسترینگ، lower_back', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'ددلیفت', 'slug' => 'ددلیفت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'ددلیفت تراپ بار برای پا و پشت و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'hamstrings', 'lower_back'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'hip_hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 70, 'glutes' => 85, 'hamstrings' => 75, 'lower_back' => 50],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'ددلیفت تراپ بار برای پا و کمر امن‌تر.',
            'target_area' => 'پا و پشت',
        ],
        'rank_extra' => 'ددلیفت دوست‌دار کمر.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-16',
        'slug' => 'ددلیفت-بلوک',
        'title' => 'ددلیفت بلوک',
        'aliases' => ['Block Pull', 'BlockPull', 'ددلیفت بلوک'],
        'intro' => '<strong>ددلیفت بلوک</strong> (Block Pull) ددلیفت از ارتفاع بلوک؛ برای تقویت قفل میانی در پاورلیفتینگ و ضخامت پشت. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'ددلیفت بلوک — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'باسن، همسترینگ، traps', 'difficulty' => 'پیشرفته', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: باسن، همسترینگ، traps', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'ددلیفت', 'slug' => 'ددلیفت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'ددلیفت بلوک برای پشت و پا و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['glutes', 'hamstrings', 'traps'],
            'difficulty' => 'advanced', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'hip_hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['lower_back' => 75, 'glutes' => 80, 'hamstrings' => 70, 'traps' => 55],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'ددلیفت بلوک برای قفل میانی و بالا.',
            'target_area' => 'پشت و پا',
        ],
        'rank_extra' => 'قفل میانی.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-17',
        'slug' => 'ددلیفت-رک',
        'title' => 'ددلیفت رک',
        'aliases' => ['Rack Pull', 'RackPull', 'ددلیفت رک'],
        'intro' => '<strong>ددلیفت رک</strong> (Rack Pull) ددلیفت از رک در ارتفاع زانو؛ برای تله و پشت بالا و انتقال به ددلیفت سنگین. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'ددلیفت رک — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'باسن، همسترینگ، traps', 'difficulty' => 'پیشرفته', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: باسن، همسترینگ، traps', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'ددلیفت بلوک', 'slug' => 'ددلیفت-بلوک']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'ددلیفت رک برای پشت و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['glutes', 'hamstrings', 'traps'],
            'difficulty' => 'advanced', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'hip_hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['traps' => 85, 'lower_back' => 70, 'glutes' => 65, 'hamstrings' => 60],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'ددلیفت رک برای ضخامت بالای پشت.',
            'target_area' => 'پشت',
        ],
        'rank_extra' => 'پشت بالا.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-18',
        'slug' => 'ددلیفت-رومانیایی-تک-پا',
        'title' => 'ددلیفت رومانیایی تک پا',
        'aliases' => ['Single Leg Romanian Deadlift', 'SingleLegRomanianDeadlift', 'ددلیفت رومانیایی تک پا'],
        'intro' => '<strong>ددلیفت رومانیایی تک پا</strong> (Single Leg Romanian Deadlift) هیپ‌هینج با یک پا؛ برای همسترینگ، باسن و تعادل در تمرین فانکشنال و بدنسازی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل اجرا می‌شود.',
        'caption' => 'ددلیفت رومانیایی تک پا — همسترینگ، اجرای کنترل‌شده',
        'quick' => ['main' => 'همسترینگ', 'secondary' => 'باسن، lower_back', 'difficulty' => 'متوسط', 'equipment' => 'دمبل', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی همسترینگ در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: همسترینگ', 'کمکی: باسن، lower_back', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'رومانیایی دمبل', 'slug' => 'رومانیایی-دمبل']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'ددلیفت رومانیایی تک پا برای پشت پا و همسترینگ در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'همسترینگ | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'hamstrings', 'secondary_muscle_keys' => ['glutes', 'lower_back'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'hip_hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['hamstrings' => 85, 'glutes' => 75, 'abs' => 40],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'RDL تک‌پا برای تعادل و همسترینگ.',
            'target_area' => 'پشت پا',
        ],
        'rank_extra' => 'تعادل و پشت پا.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-19',
        'slug' => 'اسکوات-پرش',
        'title' => 'اسکوات پرش',
        'aliases' => ['Jump Squat', 'JumpSquat', 'اسکوات پرش'],
        'intro' => '<strong>اسکوات پرش</strong> (Jump Squat) اسکات با پرش در بالا؛ برای پلیومتریک، چابکی و قدرت پا در آمادگی ورزشی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'اسکوات پرش — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، calves', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن، calves', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'اسکات گابلت', 'slug' => 'اسکات-گابلت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'اسکوات پرش برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'calves'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'squat', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 80, 'glutes' => 70, 'calves' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'اسکوات پرش برای قدرت انفجاری پا.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'قدرت انفجاری.',
    ]);

    $add([
        'image_key' => 'exercise-batch7-20',
        'slug' => 'پرس-پا-پا-باز',
        'title' => 'پرس پا پا باز',
        'aliases' => ['Wide Stance Leg Press', 'WideStanceLegPress', 'پرس پا پا باز'],
        'intro' => '<strong>پرس پا پا باز</strong> (Wide Stance Leg Press) پرس پا با فاصله پا بیشتر؛ تاکید روی adductor و چهارسر در روز پا. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'پرس پا پا باز — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، adductors', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن، adductors', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'لگ پرس', 'slug' => 'لگ-پرس']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پرس پا پا باز برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'adductors'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'squat', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 85, 'glutes' => 70, 'adductors' => 50],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'لگ پرس پا باز برای داخل ران و چهارسر.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'پا باز.',
    ]);

    return $defs;
}
}
