// GymAI Popular — BATCH 13 (20 حرکت — حرکات 221 تا 240)
// Code Snippets: Run everywhere | بدون تگ php

if (!function_exists('gymai_pop20_batch13_definitions')) {
function gymai_pop20_batch13_definitions() {
    $base_img = 'https://gymaipro.ir/wp-content/uploads/2026/08/';
    $defs = [];
    $add = function (array $row) use (&$defs, $base_img) {
        if (empty($row['image'])) {
            $key = !empty($row['image_key']) ? $row['image_key'] : ('exercise-batch13-' . str_pad((string) (count($defs) + 1), 2, '0', STR_PAD_LEFT));
            $row['image'] = $base_img . $key . '.jpg';
        }
        $defs[] = $row;
    };

    $add([
        'image_key' => 'exercise-batch13-01',
        'slug' => 'قفسه-بالاسینه',
        'title' => 'قفسه بالاسینه',
        'aliases' => ['Incline Dumbbell Fly', 'InclineDumbbellFly', 'قفسه بالاسینه', 'فلای بالاسینه', 'قفسه شیب', 'Incline Fly', 'قفسه بالا سینه'],
        'intro' => '<strong>قفسه بالاسینه</strong> (Incline Dumbbell Fly) فلای روی نیمکت شیب؛ نام رایج سالن‌های ایرانی برای بالاسینه. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل و نیمکت اجرا می‌شود.',
        'caption' => 'قفسه بالاسینه — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'سرشانه', 'difficulty' => 'متوسط', 'equipment' => 'دمبل و نیمکت', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پرس سینه شیب دار', 'slug' => 'پرس-سینه-شیب-دار']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'قفسه بالاسینه برای بالاسینه و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['shoulder_anterior'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'incline_seated', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest_upper' => 92, 'chest' => 75],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'قفسه دمبل بالاسینه برای کشش سینه بالا.',
            'target_area' => 'بالاسینه',
        ],
        'rank_extra' => 'کشش بالاسینه.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-02',
        'slug' => 'کراس-اور-بالا-به-پایین',
        'title' => 'کراس اور بالا به پایین',
        'aliases' => ['High to Low Cable Fly', 'HightoLowCableFly', 'کراس اور بالا به پایین', 'کراس اور بالا', 'High to Low Crossover', 'کراس از بالا'],
        'intro' => '<strong>کراس اور بالا به پایین</strong> (High to Low Cable Fly) پولی بالا، حرکت قوسی به پایین؛ تاکید الیاف پایینی سینه. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'کراس اور بالا به پایین — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'سرشانه', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کراس سیمکش', 'slug' => 'کراس-سیمکش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'کراس اور بالا به پایین برای سینه پایین و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['shoulder_anterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest_lower' => 90, 'chest' => 80],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'کراس از بالا به پایین برای سینه پایین.',
            'target_area' => 'سینه پایین',
        ],
        'rank_extra' => 'سینه پایین.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-03',
        'slug' => 'کراس-اور-پایین-به-بالا',
        'title' => 'کراس اور پایین به بالا',
        'aliases' => ['Low to High Cable Fly', 'LowtoHighCableFly', 'کراس اور پایین به بالا', 'کراس اور پایین', 'Low to High Crossover', 'کراس بالاسینه'],
        'intro' => '<strong>کراس اور پایین به بالا</strong> (Low to High Cable Fly) پولی پایین، حرکت به سمت بالا؛ مکمل پرس بالاسینه. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'کراس اور پایین به بالا — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'سرشانه', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پرس سینه شیب دار', 'slug' => 'پرس-سینه-شیب-دار']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'کراس اور پایین به بالا برای بالاسینه و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['shoulder_anterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest_upper' => 90, 'chest' => 78],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'کراس از پایین به بالا برای بالاسینه.',
            'target_area' => 'بالاسینه',
        ],
        'rank_extra' => 'بالاسینه کابل.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-04',
        'slug' => 'پرس-بالاسینه-اسمیت',
        'title' => 'پرس بالاسینه اسمیت',
        'aliases' => ['Smith Incline Press', 'SmithInclinePress', 'پرس بالاسینه اسمیت', 'اسمیت بالاسینه', 'Incline Smith Press', 'پرس شیب اسمیت'],
        'intro' => '<strong>پرس بالاسینه اسمیت</strong> (Smith Incline Press) بنچ شیب روی اسمیت؛ ثبات مسیر برای مبتدی و حجم. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه و نیمکت اجرا می‌شود.',
        'caption' => 'پرس بالاسینه اسمیت — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'پشت بازو، سرشانه', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه و نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: پشت بازو، سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پرس سینه اسمیت', 'slug' => 'پرس-سینه-اسمیت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پرس بالاسینه اسمیت برای بالاسینه و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['triceps', 'shoulder_anterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'incline_seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest_upper' => 90, 'chest' => 80, 'triceps' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پرس شیب روی اسمیت.',
            'target_area' => 'بالاسینه',
        ],
        'rank_extra' => 'بالاسینه ثابت.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-05',
        'slug' => 'گیوتین-پرس',
        'title' => 'گیوتین پرس',
        'aliases' => ['Guillotine Press', 'GuillotinePress', 'گیوتین پرس'],
        'intro' => '<strong>گیوتین پرس</strong> (Guillotine Press) پرس با میله نزدیک گردن؛ دامنه کشش زیاد — فقط با وزنه سبک و اسپاتر. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر و نیمکت اجرا می‌شود.',
        'caption' => 'گیوتین پرس — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'سرشانه', 'difficulty' => 'پیشرفته', 'equipment' => 'هالتر و نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پرس سینه با هالتر', 'slug' => 'پرس-سینه-با-هالتر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'گیوتین پرس برای سینه و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['shoulder_anterior'],
            'difficulty' => 'advanced', 'equipment_keys' => ['barbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest' => 88, 'chest_upper' => 70, 'shoulder_anterior' => 50],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'گیوتین پرس برای کشش بالای سینه — احتیاط.',
            'target_area' => 'سینه',
        ],
        'rank_extra' => 'کشش سینه — احتیاط.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-06',
        'slug' => 'پرس-سینه-همر',
        'title' => 'پرس سینه همر',
        'aliases' => ['Hammer Strength Chest Press', 'HammerStrengthChestPress', 'پرس سینه همر', 'چست پرس همر', 'Iso Lateral Chest Press', 'همر چست'],
        'intro' => '<strong>پرس سینه همر</strong> (Hammer Strength Chest Press) پرس ایزو‌لترال دستگاه؛ هر طرف جدا برای تعادل سینه. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'پرس سینه همر — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'پشت بازو، سرشانه', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: پشت بازو، سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پرس سینه دستگاه', 'slug' => 'پرس-سینه-دستگاه']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پرس سینه همر برای سینه و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['triceps', 'shoulder_anterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest' => 90, 'triceps' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پرس سینه همر استرنگث.',
            'target_area' => 'سینه',
        ],
        'rank_extra' => 'ایزولترال سینه.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-07',
        'slug' => 'پول-اور-دستگاه',
        'title' => 'پول اور دستگاه',
        'aliases' => ['Machine Pullover', 'MachinePullover', 'پول اور دستگاه'],
        'intro' => '<strong>پول اور دستگاه</strong> (Machine Pullover) حرکت قوسی دستگاه؛ سینه، زیربغل و serratus با هم. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'پول اور دستگاه — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'back_lat، پشت بازو', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: back_lat، پشت بازو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پول اور دمبل', 'slug' => 'پول-اور-دمبل']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پول اور دستگاه برای سینه و زیربغل و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['back_lat', 'triceps'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest' => 75, 'back_lat' => 65, 'triceps' => 35],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پول‌اور دستگاه کلاسیک ناکسیوس.',
            'target_area' => 'سینه و زیربغل',
        ],
        'rank_extra' => 'قفسه سینه.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-08',
        'slug' => 'رویینگ-تی-بار-صفحه',
        'title' => 'رویینگ تی بار صفحه',
        'aliases' => ['Plate Loaded T-Bar Row', 'PlateLoadedT-BarRow', 'رویینگ تی بار صفحه', 'تی بار صفحه‌ای', 'Chest Supported T-Bar', 'تی‌بار لندماین'],
        'intro' => '<strong>رویینگ تی بار صفحه</strong> (Plate Loaded T-Bar Row) رویینگ با هالتر لندماین و صفحه؛ کلاسیک ضخامت میانی پشت. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر و دستگاه اجرا می‌شود.',
        'caption' => 'رویینگ تی بار صفحه — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو، پشت میانی', 'difficulty' => 'متوسط', 'equipment' => 'هالتر و دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو، پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'زیربغل تی بار', 'slug' => 'زیربغل-تی-بار']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'رویینگ تی بار صفحه برای پشت و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'rhomboids'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell', 'machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'bent_over', 'grip_type' => 'pronated', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 90, 'rhomboids' => 55, 'biceps' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'تی‌بار صفحه‌ای برای ضخامت پشت.',
            'target_area' => 'پشت',
        ],
        'rank_extra' => 'ضخامت پشت.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-09',
        'slug' => 'رویینگ-نشسته-دستگاه',
        'title' => 'رویینگ نشسته دستگاه',
        'aliases' => ['Seated Row Machine', 'SeatedRowMachine', 'رویینگ نشسته دستگاه', 'قایقی دستگاه', 'سیتد رو', 'Seated Row', 'رو دستگاه'],
        'intro' => '<strong>رویینگ نشسته دستگاه</strong> (Seated Row Machine) قایقی نشسته روی دستگاه پلیت یا استک؛ پایه روز پشت. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'رویینگ نشسته دستگاه — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو، پشت میانی', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو، پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'زیربغل نشسته سیمکش', 'slug' => 'زیربغل-نشسته-سیمکش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'رویینگ نشسته دستگاه برای پشت و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'rhomboids'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 88, 'rhomboids' => 55, 'biceps' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'رویینگ نشسته دستگاه برای ضخامت پشت.',
            'target_area' => 'پشت',
        ],
        'rank_extra' => 'ضخامت پشت.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-10',
        'slug' => 'سیل-رو',
        'title' => 'سیل رو',
        'aliases' => ['Seal Row', 'SealRow', 'سیل رو', 'رویینگ سیل'],
        'intro' => '<strong>سیل رو</strong> (Seal Row) رویینگ دمر روی نیمکت بلند؛ حذف تاب کمر. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر و نیمکت اجرا می‌شود.',
        'caption' => 'سیل رو — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو، پشت میانی', 'difficulty' => 'متوسط', 'equipment' => 'هالتر و نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو، پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'زیربغل سینه روی نیمکت', 'slug' => 'زیربغل-سینه-روی-نیمکت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'سیل رو برای پشت و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'rhomboids'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'prone', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 90, 'rhomboids' => 55, 'biceps' => 42],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'سیل رو بدون تقلب کمر.',
            'target_area' => 'پشت',
        ],
        'rank_extra' => 'بدون تقلب.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-11',
        'slug' => 'زیربغل-همر',
        'title' => 'زیربغل همر',
        'aliases' => ['Hammer Strength Lat Pulldown', 'HammerStrengthLatPulldown', 'زیربغل همر', 'همر لت', 'Iso Lateral Pulldown'],
        'intro' => '<strong>زیربغل همر</strong> (Hammer Strength Lat Pulldown) کشش عمودی دستگاه همر؛ هر طرف جدا برای عرض پشت. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'زیربغل همر — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'زیربغل سیمکش', 'slug' => 'زیربغل-سیمکش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'زیربغل همر برای زیربغل و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 90, 'biceps' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'زیربغل همر ایزولترال.',
            'target_area' => 'زیربغل',
        ],
        'rank_extra' => 'ایزولترال لات.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-12',
        'slug' => 'کراس-بادی-لت',
        'title' => 'کراس بادی لت',
        'aliases' => ['Cable Cross Body Lat Pulldown', 'CableCrossBodyLatPulldown', 'کراس بادی لت'],
        'intro' => '<strong>کراس بادی لت</strong> (Cable Cross Body Lat Pulldown) کشش سیمکش از بالا مورب به سمت باسن مخالف؛ جداسازی لات. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'کراس بادی لت — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'پهلو', 'difficulty' => 'متوسط', 'equipment' => 'سیم‌کش', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: پهلو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'زیربغل دست صاف', 'slug' => 'زیربغل-دست-صاف']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'کراس بادی لت برای زیربغل و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['obliques'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 88, 'obliques' => 30],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'لت کراس‌بادی برای کشش مورب.',
            'target_area' => 'زیربغل',
        ],
        'rank_extra' => 'لات مورب.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-13',
        'slug' => 'دیپ-دستگاه',
        'title' => 'دیپ دستگاه',
        'aliases' => ['Assisted / Machine Dip', 'Assisted/MachineDip', 'دیپ دستگاه', 'دیپ کمکی', 'Assisted Dip', 'Machine Dip', 'دیپ ماشین'],
        'intro' => '<strong>دیپ دستگاه</strong> (Assisted / Machine Dip) دیپ روی دستگاه کمکی یا وزنه‌دار؛ مسیر یادگیری دیپ پارالل. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'دیپ دستگاه — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'پشت بازو، سرشانه', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: پشت بازو، سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'دیپ پارالل', 'slug' => 'دیپ-پارالل']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'دیپ دستگاه برای سینه و پشت‌بازو و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['triceps', 'shoulder_anterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'support', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest' => 70, 'triceps' => 80, 'shoulder_anterior' => 40],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'دیپ دستگاه با کمک یا وزنه.',
            'target_area' => 'سینه و پشت‌بازو',
        ],
        'rank_extra' => 'دیپ امن.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-14',
        'slug' => 'بارفیکس-دست-جمع',
        'title' => 'بارفیکس دست جمع',
        'aliases' => ['Close Grip Pull-Up', 'CloseGripPull-Up', 'بارفیکس دست جمع', 'کلوز گریپ پول‌آپ', 'Close Grip Chin'],
        'intro' => '<strong>بارفیکس دست جمع</strong> (Close Grip Pull-Up) کشش با گرفتن نزدیک؛ جلو بازو بیشتر از دست باز. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن و میله اجرا می‌شود.',
        'caption' => 'بارفیکس دست جمع — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن و میله', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و میله و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'چین آپ', 'slug' => 'چین-آپ']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'بارفیکس دست جمع برای زیربغل و جلوبازو و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight', 'bar'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'hanging', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 85, 'biceps' => 60],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'بارفیکس دست جمع برای ضخامت و جلوبازو.',
            'target_area' => 'زیربغل و جلوبازو',
        ],
        'rank_extra' => 'ضخامت پشت.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-15',
        'slug' => 'پول-آپ-خنثی',
        'title' => 'پول آپ گریپ خنثی',
        'aliases' => ['Neutral Grip Pull-Up', 'NeutralGripPull-Up', 'پول آپ گریپ خنثی', 'بارفیکس موازی', 'Neutral Pull-Up', 'همر گریپ پول‌آپ'],
        'intro' => '<strong>پول آپ گریپ خنثی</strong> (Neutral Grip Pull-Up) گرفتن موازی روی میله چندگریپ؛ شانه و مچ دوست‌تر. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن و میله اجرا می‌شود.',
        'caption' => 'پول آپ گریپ خنثی — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن و میله', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و میله و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'بارفیکس', 'slug' => 'بارفیکس']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'پول آپ گریپ خنثی برای زیربغل و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight', 'bar'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'hanging', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 88, 'biceps' => 55],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'بارفیکس موازی برای شانه راحت‌تر.',
            'target_area' => 'زیربغل',
        ],
        'rank_extra' => 'گریپ موازی.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-16',
        'slug' => 'پول-اور-سیمکش',
        'title' => 'پول اور سیمکش',
        'aliases' => ['Cable Pullover', 'CablePullover', 'پول اور سیمکش'],
        'intro' => '<strong>پول اور سیمکش</strong> (Cable Pullover) کشش از بالا با دست صاف؛ فعال‌سازی لات قبل از پولداون. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'پول اور سیمکش — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'chest، پشت بازو', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: chest، پشت بازو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'زیربغل دست صاف', 'slug' => 'زیربغل-دست-صاف']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پول اور سیمکش برای زیربغل و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['chest', 'triceps'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 88, 'chest' => 40, 'triceps' => 30],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پول‌اور ایستاده با سیمکش.',
            'target_area' => 'زیربغل',
        ],
        'rank_extra' => 'فعال‌سازی لات.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-17',
        'slug' => 'اسپوتو-پرس',
        'title' => 'اسپوتو پرس',
        'aliases' => ['Spoto Press', 'SpotoPress', 'اسپوتو پرس'],
        'intro' => '<strong>اسپوتو پرس</strong> (Spoto Press) پرس با توقف ۱–۲ سانتی بالای سینه؛ قدرت و کنترل بنچ. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر و نیمکت اجرا می‌شود.',
        'caption' => 'اسپوتو پرس — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'پشت بازو', 'difficulty' => 'پیشرفته', 'equipment' => 'هالتر و نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: پشت بازو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پرس سینه با هالتر', 'slug' => 'پرس-سینه-با-هالتر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'اسپوتو پرس برای سینه و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['triceps'],
            'difficulty' => 'advanced', 'equipment_keys' => ['barbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest' => 90, 'triceps' => 55],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'اسپوتو پرس برای کنترل نزدیک سینه.',
            'target_area' => 'سینه',
        ],
        'rank_extra' => 'کنترل بنچ.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-18',
        'slug' => 'پرس-زمین-دمبل',
        'title' => 'پرس زمین دمبل',
        'aliases' => ['Dumbbell Floor Press', 'DumbbellFloorPress', 'پرس زمین دمبل'],
        'intro' => '<strong>پرس زمین دمبل</strong> (Dumbbell Floor Press) پرس روی زمین؛ محدودیت دامنه برای شانه حساس. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل اجرا می‌شود.',
        'caption' => 'پرس زمین دمبل — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'پشت بازو', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: پشت بازو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پرس زمین هالتر', 'slug' => 'پرس-زمین-هالتر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پرس زمین دمبل برای سینه و پشت‌بازو و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['triceps'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest' => 80, 'triceps' => 60],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پرس زمین با دمبل برای شانه امن.',
            'target_area' => 'سینه و پشت‌بازو',
        ],
        'rank_extra' => 'شانه امن.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-19',
        'slug' => 'چست-فلای-دستگاه',
        'title' => 'چست فلای دستگاه',
        'aliases' => ['Machine Chest Fly', 'MachineChestFly', 'چست فلای دستگاه', 'فلای ماشین', 'Machine Fly'],
        'intro' => '<strong>چست فلای دستگاه</strong> (Machine Chest Fly) دستگاه فلای اهرمی؛ کشش سینه با مسیر ثابت. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'چست فلای دستگاه — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'سرشانه', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'فلای پک دستگاه', 'slug' => 'فلای-پک-دستگاه']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'چست فلای دستگاه برای سینه و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['shoulder_anterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest' => 90, 'chest_middle' => 85],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'فلای سینه دستگاه غیر از پک‌دک.',
            'target_area' => 'سینه',
        ],
        'rank_extra' => 'کشش سینه.',
    ]);

    $add([
        'image_key' => 'exercise-batch13-20',
        'slug' => 'وای-ریز',
        'title' => 'وای ریز',
        'aliases' => ['Y Raise', 'YRaise', 'وای ریز', 'پرون وای'],
        'intro' => '<strong>وای ریز</strong> (Y Raise) بالا بردن دست‌ها به شکل Y؛ prehab شانه و posture. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل اجرا می‌شود.',
        'caption' => 'وای ریز — سرشانه پشت، اجرای کنترل‌شده',
        'quick' => ['main' => 'سرشانه پشت', 'secondary' => 'ذوزنقه', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی سرشانه پشت در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سرشانه پشت', 'کمکی: ذوزنقه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پاروی صورت', 'slug' => 'پاروی-صورت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'وای ریز برای سرشانه و کتف و سرشانه پشت در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سرشانه پشت | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_posterior', 'secondary_muscle_keys' => ['traps_middle'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'prone', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_posterior' => 70, 'traps_middle' => 75, 'lower_traps' => 80],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'Y Raise برای کتف و پشت شانه.',
            'target_area' => 'سرشانه و کتف',
        ],
        'rank_extra' => 'سلامت کتف.',
    ]);

    return $defs;
}
}
