// GymAI Popular 20 — BATCH 3 (20 حرکت سوم)
// Code Snippets: Run everywhere | بدون تگ php

if (!function_exists('gymai_pop20_batch3_definitions')) {
function gymai_pop20_batch3_definitions() {
    $base_img = 'https://gymaipro.ir/wp-content/uploads/2026/06/';
    $defs = [];
    $add = function (array $row) use (&$defs, $base_img) {
        if (empty($row['image'])) {
            $key = !empty($row['image_key']) ? $row['image_key'] : ('exercise-batch3-' . str_pad((string) (count($defs) + 1), 2, '0', STR_PAD_LEFT));
            $row['image'] = $base_img . $key . '.jpg';
        }
        $defs[] = $row;
    };

    $add([
        'image_key' => 'exercise-batch3-01',
        'slug' => 'اسکات-گابلت',
        'title' => 'اسکات گابلت',
        'aliases' => ['Goblet Squat', 'DB Goblet Squat', 'اسکات با دمبل جلو'],
        'intro' => '<strong>اسکات گابلت</strong> اسکات با دمبل یا کتل‌بل جلوی سینه است. برای یادگیری الگوی اسکات، تقویت Core و تمرین پا در سالن‌های ایرانی بسیار رایج است.',
        'caption' => 'اسکات گابلت — دمبل جلوی سینه، زانو هم‌راستا با پا',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، Core', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل یا کتل‌بل', 'type' => 'قدرتی / حجمی'],
        'tips' => ['دمبل نزدیک سینه، آرنج داخل.', 'زانو هم‌راستا با انگشت پا.', 'عمق تا ران موازی یا کمی پایین‌تر.'],
        'setup' => ['ایستاده، پا عرض شانه.', 'دمبل عمودی جلوی سینه.', 'Core سفت، قفسه بالا.'],
        'execution' => ['باسن عقب و پایین.', 'زانو باز نشود بیش از حد.', 'فشار کف پا برای بالا.', 'ایستادن کامل بدون قفل سخت.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: quadriceps', 'کمکی: glutes، Core', 'تثبیت: ساعد و کمر'],
        'mistakes' => [['زانو به داخل', 'فشار بیرون زانو'], ['پاشنه بلند', 'کف پا ثابت'], ['تنه بیش از حد جلو', 'قامت عمودی']],
        'program' => [['حجم', '۳–۴', '۱۰–۱۵', '۶۰–۹۰ث'], ['قدرت', '۴', '۶–۱۰', '۹۰ث'], ['استقامت', '۳', '۱۵–۲۰', '۴۵ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'لانج', 'slug' => 'لانج']],
        'faqs' => [['q' => 'دمبل یا کتل‌بل؟', 'a' => 'هر دو عالی؛ کتل‌بل دسته راحت‌تر، دمبل در همه سالن‌ها موجود است.']],
        'summary' => 'اسکات گابلت بهترین گزینه مبتدی برای اسکات عمیق و امن.',
        'summary_keys' => 'دمبل جلوی سینه | زانو هم‌راستا | Core سفت',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'abs'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell', 'kettlebell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'squat', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'knee_hip',
            'muscle_targets' => ['quads' => 90, 'glutes' => 75, 'abs' => 40, 'hamstrings' => 35],
            'met' => 5, 'movement_distance_cm' => 55, 'calories_per_1000kg' => 45, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '10-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 75, 'tempo' => '2-1-2',
            'short_description' => 'اسکات گابلت اسکات با وزنه جلوی سینه برای چهارسر، باسن و Core.',
            'target_area' => 'پا و باسن',
        ],
        'rank_extra' => 'اسکات امن برای مبتدی و خانه.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-02',
        'slug' => 'پرس-سرشانه-دمبل',
        'title' => 'پرس سرشانه با دمبل',
        'aliases' => ['Dumbbell Shoulder Press', 'DB Overhead Press', 'Seated DB Press', 'پرس دمبل سرشانه'],
        'intro' => '<strong>پرس سرشانه با دمبل</strong> حرکت فشار عمودی با دمبل برای رشد سرشانه و پشت بازو است. دامنه طبیعی‌تر از هالتر و تمرین جداگانه هر دست از مزایای آن در سالن‌های ایرانی است.',
        'caption' => 'پرس سرشانه با دمبل — Core سفت و مسیر عمودی',
        'quick' => ['main' => 'سرشانه (قدامی/میانی)', 'secondary' => 'پشت بازو، ذوزنقه', 'difficulty' => 'متوسط', 'equipment' => 'دمبل، نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['Core و کمر سفت.', 'دمبل کنار سر در بالا.', 'آرنج کمی جلوتر از مچ.'],
        'setup' => ['نشسته یا ایستاده.', 'دمبل کنار شانه، کف دست رو به جلو.', 'پا ثابت، کمر خنثی.'],
        'execution' => ['با بازدم فشار به بالا.', 'دمبل بالای سر بدون برخورد.', 'با دم پایین کنترل‌شده.', 'آرنج نرم در بالا.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: دلتوئید قدامی و میانی', 'کمکی: تریسپس، تراپس', 'تثبیت: Core'],
        'mistakes' => [['قوس بیش از حد کمر', 'Core سفت'], ['پرس جلو بدن', 'مسیر عمودی'], ['دامنه ناقص', 'پایین تا گوش']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۶۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'پرس سرشانه با هالتر', 'slug' => 'پرس-سرشانه-با-هالتر']],
        'faqs' => [['q' => 'نشسته یا ایستاده؟', 'a' => 'نشسته ثبات بیشتر؛ ایستاده Core و قدرت عملکردی بیشتر.']],
        'summary' => 'پرس سرشانه دمبل برای حجم و تعادل سرشانه عالی است.',
        'summary_keys' => 'Core سفت | مسیر عمودی | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_anterior', 'secondary_muscle_keys' => ['shoulder_lateral', 'triceps', 'traps_upper'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'shoulder_elbow',
            'muscle_targets' => ['shoulder_anterior' => 90, 'shoulder_lateral' => 70, 'triceps' => 50, 'traps_upper' => 30, 'abs' => 25],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 46, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '5-8', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-0-2',
            'short_description' => 'پرس سرشانه با دمبل فشار عمودی برای سرشانه، پشت بازو و Core.',
            'target_area' => 'سرشانه',
        ],
        'rank_extra' => 'حجم سرشانه با دامنه طبیعی دمبل.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-03',
        'slug' => 'زیربغل-سیمکش',
        'title' => 'زیربغل سیمکش',
        'aliases' => ['Lat Pulldown', 'Cable Pulldown', 'Wide Grip Pulldown', 'پول‌داون'],
        'intro' => '<strong>زیربغل سیمکش</strong> (Lat Pulldown) کشش عمودی با دستگاه برای ساخت زیربغل پهن است. جایگزین بارفیکس برای مبتدی و پرکاربردترین حرکت پشت در سالن‌های ایرانی محسوب می‌شود.',
        'caption' => 'زیربغل سیمکش — کتف پایین و کشش تا سینه',
        'quick' => ['main' => 'زیربغل (لات)', 'secondary' => 'جلوبازو، پشت میانی', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'قدرتی / حجمی'],
        'tips' => ['کتف پایین قبل از خم آرنج.', 'کشش به بالای سینه.', 'بدون تاب بدن.'],
        'setup' => ['نشسته، ران زیر پد.', 'گرفتن میله کمی بازتر از شانه.', 'کتف فعال، سینه بالا.'],
        'execution' => ['کشش با آرنج به پایین.', 'میله نزدیک بالای سینه.', 'مکث کوتاه عقب.', 'بازگشت آهسته تا کشش کامل.'],
        'breathing' => 'بازدم پایین — دم بالا.',
        'muscles' => ['اصلی: latissimus dorsi', 'کمکی: biceps، rhomboids', 'تثبیت: Core'],
        'mistakes' => [['کشش با بدن', 'تنه ثابت'], ['میله پشت گردن', 'جلو سینه امن‌تر'], ['آرنج باز', 'آرنج کنار بدن']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۶–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'بارفیکس', 'slug' => 'بارفیکس']],
        'faqs' => [['q' => 'عرض گرفتن؟', 'a' => 'دست باز لات بیشتر؛ دست جمع ضخامت میانی پشت.']],
        'summary' => 'زیربغل سیمکش پایه تمرین پشت برای پهن شدن زیربغل.',
        'summary_keys' => 'کتف پایین | کشش به سینه | تمپو کنترل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'rhomboids', 'traps_middle'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'pronated', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'shoulder_elbow',
            'muscle_targets' => ['back_lat' => 95, 'biceps' => 45, 'rhomboids' => 40, 'traps_middle' => 35],
            'met' => 5, 'movement_distance_cm' => 55, 'calories_per_1000kg' => 48, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-8', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 75, 'tempo' => '2-1-2',
            'short_description' => 'زیربغل سیمکش کشش عمودی برای زیربغل، جلوبازو و پشت میانی.',
            'target_area' => 'زیربغل',
        ],
        'rank_extra' => 'ساخت پشت پهن بدون بارفیکس.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-04',
        'slug' => 'اکستنشن-پا',
        'title' => 'اکستنشن پا',
        'aliases' => ['Leg Extension', 'Quad Extension', 'پشت پا دستگاه جلو'],
        'intro' => '<strong>اکستنشن پا</strong> حرکت ایزوله برای چهارسر روی دستگاه Leg Extension است. در برنامه‌های پا ایرانی برای پمپ و پیش‌خستگی چهارسر بسیار رایج است.',
        'caption' => 'اکستنشن پا — انقباض چهارسر در بالا',
        'quick' => ['main' => 'چهارسر', 'secondary' => '—', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه Leg Extension', 'type' => 'حجمی'],
        'tips' => ['پشت کاملاً به پشتی.', 'انقباض ۱ ثانیه بالا.', 'پایین آهسته بدون پرتاب.'],
        'setup' => ['نشسته، مچ پشت پد.', 'زانو هم‌راستا محور.', 'گرفتن دستگیره.'],
        'execution' => ['باز کردن پا تا صاف.', 'مکث در انقباض.', 'پایین کنترل‌شده.', 'بدون پرتاب وزنه.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: quadriceps', 'کمکی: —', 'تثبیت: Core'],
        'mistakes' => [['پرتاب وزنه', 'تمپو کنترل'], ['زانو قفل سخت', 'آرنج نرم'], ['کمر جدا از پشتی', 'تکیه کامل']],
        'program' => [['حجم', '۳–۴', '۱۲–۱۵', '۴۵–۶۰ث'], ['پمپ', '۳', '۱۵–۲۰', '۳۰ث'], ['استقامت', '۳', '۲۰–۲۵', '۳۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'اسکات گابلت', 'slug' => 'اسکات-گابلت']],
        'faqs' => [['q' => 'قبل یا بعد اسکات؟', 'a' => 'بعد اسکات برای پمپ؛ قبل برای پیش‌خستگی (پیشرفته).']],
        'summary' => 'اکستنشن پا برای جداسازی و حجم چهارسر ایده‌آل است.',
        'summary_keys' => 'انقباض بالا | تمپو آهسته | پشت به صندلی',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => [],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'knee_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'none', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'knee',
            'muscle_targets' => ['quads' => 95, 'quads_rectus' => 90],
            'met' => 3.5, 'movement_distance_cm' => 45, 'calories_per_1000kg' => 35, 'exercise_difficulty_score' => 2, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '8-12', 'rep_range_hypertrophy' => '12-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'اکستنشن پا ایزوله دستگاه برای هایپرتروفی چهارسر.',
            'target_area' => 'چهارسر',
        ],
        'rank_extra' => 'پمپ و حجم چهارسر.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-05',
        'slug' => 'هیپ-تراست',
        'title' => 'هیپ تراست',
        'aliases' => ['Hip Thrust', 'Barbell Hip Thrust', 'Glute Bridge Barbell', 'پشت باسن هالتر'],
        'intro' => '<strong>هیپ تراست</strong> حرکت هیپ‌هینج با تمرکز بر انقباض باسن است. یکی از محبوب‌ترین حرکات برای رشد گلوت در بدنسازی مدرن و سالن‌های ایرانی محسوب می‌شود.',
        'caption' => 'هیپ تراست — مکث انقباض باسن در بالا',
        'quick' => ['main' => 'باسن', 'secondary' => 'همسترینگ، کمر', 'difficulty' => 'متوسط', 'equipment' => 'هالتر، نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['پشت کتف روی نیمکت.', 'چانه به سینه در بالا.', 'مکث ۱–۲ ثانیه در peak.'],
        'setup' => ['شانه روی نیمکت، میله روی لگن (با pad).', 'پا عرض لگن، کف پا ثابت.', 'Core سفت.'],
        'execution' => ['پایین کنترل‌شده.', 'فشار پاشنه و بالا آوردن لگن.', 'خط بدن از زانو تا شانه.', 'پایین بدون تکیه کامل.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: gluteus maximus', 'کمکی: hamstrings، erector', 'تثبیت: Core'],
        'mistakes' => [['کمر بیش از حد قوس', 'چانه به سینه'], ['پا خیلی دور', 'زاویه ۹۰° زانو'], ['بدون مکث بالا', 'انقباض کامل']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۹۰ث'], ['قدرت', '۴', '۶–۸', '۱۲۰ث'], ['پمپ', '۳', '۱۵–۲۰', '۶۰ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پل باسن', 'slug' => 'پل-باسن']],
        'faqs' => [['q' => 'هالتر یا بدون وزنه؟', 'a' => 'بدون وزنه برای شروع؛ هالتر برای پیشرفت حجمی.']],
        'summary' => 'هیپ تراست بهترین حرکت برای فعال‌سازی و حجم باسن.',
        'summary_keys' => 'مکث بالا | پاشنه ثابت | خط بدن صاف',
        'meta' => [
            'main_muscle' => 'glutes', 'secondary_muscle_keys' => ['hamstrings', 'lower_back'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'none', 'resistance_profile' => 'free_weight', 'joint_focus' => 'hip',
            'muscle_targets' => ['glutes' => 95, 'hamstrings' => 55, 'lower_back' => 35, 'abs' => 25],
            'met' => 5.5, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 50, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-8', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-2-2',
            'short_description' => 'هیپ تراست برای باسن، همسترینگ و Core با انقباض قوی.',
            'target_area' => 'باسن',
        ],
        'rank_extra' => 'رشد باسن و قدرت لگن.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-06',
        'slug' => 'رویینگ-هالتر',
        'title' => 'رویینگ هالتر',
        'aliases' => ['Barbell Row', 'Bent Over Row', 'BB Row', 'زیربغل هالتر خم'],
        'intro' => '<strong>رویینگ هالتر</strong> کشش افقی با هالتر برای ضخامت پشت، رomboid و قدرت زیربغل است. یکی از حرکات پایه روز پشت در بدنسازی و سالن‌های ایرانی محسوب می‌شود.',
        'caption' => 'رویینگ هالتر — کمر خنثی و کتف جمع',
        'quick' => ['main' => 'پشت (میانی/لات)', 'secondary' => 'جلوبازو، کمر', 'difficulty' => 'متوسط', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['کمر تقریباً موازی زمین.', 'کشش به پایین شکم.', 'کتف جمع در عقب.'],
        'setup' => ['هالتر از زمین یا رک.', 'خم با باسن عقب.', 'گرفتن overhand عرض شانه.'],
        'execution' => ['کشش میله به پایین سینه.', 'مکث عقب.', 'پایین کنترل‌شده.', 'بدون تاب.'],
        'breathing' => 'بازدم کشش — دم پایین.',
        'muscles' => ['اصلی: lats، rhomboids', 'کمکی: biceps، erector', 'تثبیت: Core، همسترینگ'],
        'mistakes' => [['کمر گرد', 'کتف جمع'], ['کشش با بدن', 'آرنج ثابت نسبت به تنه'], ['میله خیلی بالا', 'خط شکم/سینه پایین']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۶۰ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'رویینگ سیمکش', 'slug' => 'رویینگ-سیمکش']],
        'faqs' => [['q' => 'underhand یا overhand؟', 'a' => 'underhand جلوبازو بیشتر؛ overhand پشت پهن‌تر.']],
        'summary' => 'رویینگ هالتر برای پشت ضخیم و قدرت کشش افقی.',
        'summary_keys' => 'کمر خنثی | کتف جمع | تمپو کنترل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['rhomboids', 'biceps', 'lower_back'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'transverse', 'laterality' => 'bilateral',
            'posture' => 'bent_over', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'shoulder_elbow',
            'muscle_targets' => ['back_lat' => 85, 'rhomboids' => 80, 'traps_middle' => 70, 'biceps' => 45, 'lower_back' => 40],
            'met' => 5.5, 'movement_distance_cm' => 45, 'calories_per_1000kg' => 48, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '5-8', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'رویینگ هالتر کشش افقی برای زیربغل، پشت میانی و جلوبازو.',
            'target_area' => 'پشت',
        ],
        'rank_extra' => 'ضخامت پشت با بار سنگین.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-07',
        'slug' => 'نشر-جانب-سیمکش',
        'title' => 'نشر جانب سیمکش',
        'aliases' => ['Cable Lateral Raise', 'Single Arm Cable Lateral', 'نشر جانبی کابل'],
        'intro' => '<strong>نشر جانب سیمکش</strong> حرکت ایزوله برای سرشانه میانی با تنش مداوم کابل است. در سالن‌های ایرانی جایگزین محبوب نشر جانب دمبل برای پمپ سرشانه است.',
        'caption' => 'نشر جانب سیمکش — آرنج نرم و بالا تا خط شانه',
        'quick' => ['main' => 'سرشانه میانی', 'secondary' => 'ذوزنقه (کم)', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'حجمی'],
        'tips' => ['آرنج کمی خم ثابت.', 'بالا تا خط شانه.', 'بدون تاب بدن.'],
        'setup' => ['کنار دستگاه، کابل پایین.', 'گرفتن دستگیره، دست مقابل.', 'ایستاده صاف.'],
        'execution' => ['بالا بردن دست کنار.', 'مکث کوتاه بالا.', 'پایین آهسته.', 'تکرار یا تعویض دست.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: deltoid lateral', 'کمکی: traps upper', 'تثبیت: Core'],
        'mistakes' => [['وزنه سنگین', 'کنترل تمپو'], ['بالا بیش از شانه', 'دامنه تا خط شانه'], ['چرخش تنه', 'ثبات بدن']],
        'program' => [['حجم', '۳–۴', '۱۲–۱۵', '۴۵–۶۰ث'], ['پمپ', '۳', '۱۵–۲۰', '۳۰ث'], ['استقامت', '۳', '۲۰–۲۵', '۳۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'پرس سرشانه با دمبل', 'slug' => 'پرس-سرشانه-دمبل']],
        'faqs' => [['q' => 'یک دست یا دو دست؟', 'a' => 'تک دست تمرکز بهتر؛ هر دو سریع‌تر.']],
        'summary' => 'نشر جانب سیمکش برای عرض سرشانه و پمپ.',
        'summary_keys' => 'تنش مداوم | آرنج نرم | بدون تاب',
        'meta' => [
            'main_muscle' => 'shoulder_lateral', 'secondary_muscle_keys' => ['traps_upper'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'shoulder_abduction', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'frontal', 'laterality' => 'unilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'shoulder',
            'muscle_targets' => ['shoulder_lateral' => 95, 'traps_upper' => 30],
            'met' => 3.5, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 32, 'exercise_difficulty_score' => 2, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '8-12', 'rep_range_hypertrophy' => '12-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 45, 'tempo' => '2-1-2',
            'short_description' => 'نشر جانب سیمکش ایزوله برای سرشانه میانی با تنش مداوم.',
            'target_area' => 'سرشانه میانی',
        ],
        'rank_extra' => 'عرض سرشانه با کابل.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-08',
        'slug' => 'جلو-بازو-چکشی',
        'title' => 'جلو بازو چکشی',
        'aliases' => ['Hammer Curl', 'Neutral Grip Curl', 'DB Hammer Curl', 'کرل چکشی'],
        'intro' => '<strong>جلو بازو چکشی</strong> (Hammer Curl) با گرفتن neutral دمبل برای brachialis و ضخامت بازو است. در کنار کرل کلاسیک در Arms Day سالن‌های ایرانی بسیار رایج است.',
        'caption' => 'جلو بازو چکشی — آرنج ثابت، گرفتن neutral',
        'quick' => ['main' => 'جلوبازو، brachialis', 'secondary' => 'ساعد', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل', 'type' => 'حجمی'],
        'tips' => ['آرنج کنار بدن.', 'بدون تاب.', 'پایین کامل.'],
        'setup' => ['دمبل کنار بدن، neutral grip.', 'ایستاده یا نشسته.', 'شانه پایین.'],
        'execution' => ['خم آرنج تا انقباض.', 'مکث کوتاه.', 'پایین آهسته.', 'تناوبی یا همزمان.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: brachialis، biceps', 'کمکی: forearms', 'تثبیت: Core'],
        'mistakes' => [['تاب بدن', 'کاهش وزنه'], ['آرنج جلو', 'ثابت کنار تنه'], ['نیمه دامنه', 'پایین کامل']],
        'program' => [['حجم', '۳–۴', '۱۰–۱۵', '۴۵–۶۰ث'], ['استقامت', '۳', '۱۵–۲۰', '۳۰ث'], ['قدرت', '۳', '۶–۱۰', '۷۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'جلو بازو هالتر', 'slug' => 'جلو-بازو-هالتر']],
        'faqs' => [['q' => 'فرق با کرل معمولی؟', 'a' => 'چکشی brachialis و ساعد بیشتر؛ supinated biceps بیشتر.']],
        'summary' => 'چکشی برای ضخامت بازو و brachialis.',
        'summary_keys' => 'neutral grip | آرنج ثابت | تمپو',
        'meta' => [
            'main_muscle' => 'biceps', 'secondary_muscle_keys' => ['brachialis', 'forearms'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'elbow_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'alternating',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'elbow',
            'muscle_targets' => ['brachialis' => 90, 'biceps' => 75, 'forearms' => 45],
            'met' => 3.5, 'movement_distance_cm' => 42, 'calories_per_1000kg' => 34, 'exercise_difficulty_score' => 2, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '10-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'جلو بازو چکشی برای brachialis، جلوبازو و ساعد.',
            'target_area' => 'جلوبازو',
        ],
        'rank_extra' => 'ضخامت بازو با گرفتن neutral.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-09',
        'slug' => 'اسپلیت-اسکات-بلغاری',
        'title' => 'اسپلیت اسکات بلغاری',
        'aliases' => ['Bulgarian Split Squat', 'Rear Foot Elevated Split Squat', 'اسکات بلغاری'],
        'intro' => '<strong>اسپلیت اسکات بلغاری</strong> حرکت تک‌پا با پای عقب روی نیمکت است. برای چهارسر، باسن و تعادل در برنامه‌های پا ایرانی بسیار محبوب است.',
        'caption' => 'اسپلیت اسکات بلغاری — زانو جلو روی مچ پا',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، همسترینگ', 'difficulty' => 'متوسط', 'equipment' => 'نیمکت، دمبل (اختیاری)', 'type' => 'قدرتی / حجمی'],
        'tips' => ['زانو جلو روی مچ پا.', 'تنه عمودی.', 'عمق کنترل‌شده.'],
        'setup' => ['پای عقب روی نیمکت.', 'پای جلو جلوتر کافی.', 'دمبل اختیاری کنار.'],
        'execution' => ['پایین تا زانو نزدیک زمین.', 'فشار پا جلو برای بالا.', 'تکرار یک پا.', 'تعویض پا.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: quadriceps', 'کمکی: glutes، hamstrings', 'تثبیت: Core'],
        'mistakes' => [['زانو جلو زیاد', 'قدم بلندتر'], ['پای عقب خیلی نزدیک', 'فاصله مناسب'], ['تنه جلو', 'قامت عمودی']],
        'program' => [['حجم', '۳', '۱۰–۱۲ هر پا', '۶۰–۹۰ث'], ['قدرت', '۳–۴', '۶–۸', '۹۰ث'], ['استقامت', '۳', '۱۵', '۴۵ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'لانج', 'slug' => 'لانج']],
        'faqs' => [['q' => 'بدون وزنه مؤثر است؟', 'a' => 'بله؛ با دمبل یا هالتر پیشرفت کنید.']],
        'summary' => 'اسپلیت بلغاری برای پا، باسن و تعادل.',
        'summary_keys' => 'تک‌پا | زانو روی مچ | عمق کنترل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'hamstrings'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bench', 'dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'lunge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'unilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'knee_hip',
            'muscle_targets' => ['quads' => 90, 'glutes' => 80, 'hamstrings' => 50, 'abs' => 30],
            'met' => 5, 'movement_distance_cm' => 50, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-8', 'rep_range_hypertrophy' => '10-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 75, 'tempo' => '2-1-2',
            'short_description' => 'اسپلیت اسکات بلغاری تک‌پا برای چهارسر، باسن و تعادل.',
            'target_area' => 'پا و باسن',
        ],
        'rank_extra' => 'تمرین تک‌پا پیشرفته.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-10',
        'slug' => 'پشت-پا-ایستاده',
        'title' => 'پشت پا ایستاده',
        'aliases' => ['Standing Leg Curl', 'Hamstring Curl Standing', 'Leg Curl Standing'],
        'intro' => '<strong>پشت پا ایستاده</strong> حرکت ایزوله برای همسترینگ روی دستگاه است. در سالن‌های ایرانی جایگزین رایج پشت پا دستگاه نشسته برای تمرکز تک‌پا است.',
        'caption' => 'پشت پا ایستاده — انقباض همسترینگ',
        'quick' => ['main' => 'همسترینگ', 'secondary' => 'باسن (کم)', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه Leg Curl', 'type' => 'حجمی'],
        'tips' => ['تنه ثابت.', 'انقباض کامل بالا.', 'پایین آهسته.'],
        'setup' => ['ایستاده، پد روی مچ.', 'تکیه ملایم دستگیره.', 'زانو نرم.'],
        'execution' => ['خم زانو تا پاشنه به باسن.', 'مکث بالا.', 'پایین کنترل.', 'تعویض پا.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: hamstrings', 'کمکی: glutes', 'تثبیت: Core'],
        'mistakes' => [['تاب بدن', 'ثبات'], ['نیمه دامنه', 'کامل'], ['کمر قوس', 'تنه ثابت']],
        'program' => [['حجم', '۳–۴', '۱۲–۱۵', '۴۵–۶۰ث'], ['پمپ', '۳', '۱۵–۲۰', '۳۰ث'], ['تک‌پا', '۳', '۱۰–۱۲', '۴۵ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'ددلیفت', 'slug' => 'ددلیفت']],
        'faqs' => [['q' => 'ایستاده یا نشسته؟', 'a' => 'ایستاده تک‌پا و کشش بیشتر؛ نشسته هر دو پا با هم.']],
        'summary' => 'پشت پا ایستاده برای جداسازی همسترینگ.',
        'summary_keys' => 'تک‌پا | انقباض کامل | تمپو',
        'meta' => [
            'main_muscle' => 'hamstrings', 'secondary_muscle_keys' => ['glutes'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'knee_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'unilateral',
            'posture' => 'standing', 'grip_type' => 'none', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'knee',
            'muscle_targets' => ['hamstrings' => 95, 'glutes' => 25],
            'met' => 3.5, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 33, 'exercise_difficulty_score' => 2, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '8-12', 'rep_range_hypertrophy' => '12-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پشت پا ایستاده ایزوله برای همسترینگ تک‌پا.',
            'target_area' => 'پشت پا',
        ],
        'rank_extra' => 'جداسازی همسترینگ.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-11',
        'slug' => 'ساق-ایستاده',
        'title' => 'ساق ایستاده',
        'aliases' => ['Standing Calf Raise', 'Calf Raise Machine', 'ساق پا دستگاه'],
        'intro' => '<strong>ساق ایستاده</strong> حرکت ایزوله برای gastrocnemius (ساق دو سر) است. پایان روز پا در سالن‌های ایرانی تقریباً همیشه با چند ست ساق همراه است.',
        'caption' => 'ساق ایستاده — کشش کامل پایین و روی پنجه بالا',
        'quick' => ['main' => 'ساق پا (gastrocnemius)', 'secondary' => 'سولئوس (کم)', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه یا هالتر', 'type' => 'حجمی'],
        'tips' => ['کشش کامل پاشنه پایین.', 'مکث بالا روی پنجه.', 'زانو نرم.'],
        'setup' => ['شانه زیر پد دستگاه.', 'پنجه روی سکو.', 'کمر خنثی.'],
        'execution' => ['پایین تا کشش ساق.', 'بالا روی پنجه.', 'مکث ۱ ثانیه.', 'تکرار ریتمیک.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: gastrocnemius', 'کمکی: soleus', 'تثبیت: Core'],
        'mistakes' => [['نیمه دامنه', 'کشش و انقباض کامل'], ['زانو خم', 'آرنج نرم'], ['پرتاب', 'تمپو کنترل']],
        'program' => [['حجم', '۴–۵', '۱۲–۲۰', '۳۰–۴۵ث'], ['استقامت', '۳', '۲۰–۳۰', '۳۰ث'], ['سنگین', '۳', '۸–۱۲', '۶۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'اسکات گابلت', 'slug' => 'اسکات-گابلت']],
        'faqs' => [['q' => 'ایستاده یا نشسته؟', 'a' => 'ایستاده gastrocnemius؛ نشسته soleus بیشتر.']],
        'summary' => 'ساق ایستاده برای رشد ساق پا ضروری است.',
        'summary_keys' => 'دامنه کامل | مکث بالا | کشش پایین',
        'meta' => [
            'main_muscle' => 'calves', 'secondary_muscle_keys' => ['soleus'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'ankle_plantarflexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'none', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'ankle',
            'muscle_targets' => ['calves' => 95, 'soleus' => 40],
            'met' => 3, 'movement_distance_cm' => 20, 'calories_per_1000kg' => 28, 'exercise_difficulty_score' => 2, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '4-5',
            'rep_range_strength' => '8-12', 'rep_range_hypertrophy' => '12-20', 'rep_range_endurance' => '20-30', 'rest_seconds' => 45, 'tempo' => '2-2-2',
            'short_description' => 'ساق ایستاده برای gastrocnemius و رشد ساق پا.',
            'target_area' => 'ساق پا',
        ],
        'rank_extra' => 'ساق پا پر و قوی.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-12',
        'slug' => 'دراز-و-نشست',
        'title' => 'دراز و نشست',
        'aliases' => ['Sit-Up', 'Abdominal Sit-Up', 'دراز نشست'],
        'intro' => '<strong>دراز و نشست</strong> حرکت فلکشن Core کلاسیک برای شکم و فلکسور لگن است. در تمرینات شکم خانه و سالن ایرانی هنوز بسیار رایج است.',
        'caption' => 'دراز و نشست — بالا آوردن تنه با شکم منقبض',
        'quick' => ['main' => 'شکم', 'secondary' => 'فلکسور لگن', 'difficulty' => 'مبتدی', 'equipment' => 'بدون تجهیزات (یا میله پا)', 'type' => 'حجمی / استقامتی'],
        'tips' => ['شکم منقبض در بالا.', 'بدون کشش گردن.', 'پایین کنترل‌شده.'],
        'setup' => ['درازکش، زانو خم.', 'پا ثابت (میله یا همکار).', 'دست پشت سر یا روی سینه.'],
        'execution' => ['منقبض شکم، تنه بالا.', 'تا نشستن کامل یا نزدیک.', 'پایین آهسته.', 'تکرار بدون استراحت کمر.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: rectus abdominis', 'کمکی: hip flexors', 'تثبیت: Core'],
        'mistakes' => [['کشش گردن', 'دست سبک'], ['تاب بدن', 'تمپو کنترل'], ['کمر درد', 'دامنه کوتاه‌تر یا کرانچ']],
        'program' => [['حجم', '۳–۴', '۱۵–۲۵', '۳۰–۴۵ث'], ['استقامت', '۳', '۲۵–۴۰', '۳۰ث'], ['سنگین', '۳', '۱۰–۱۵ با وزنه', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کرانچ', 'slug' => 'کرانچ']],
        'faqs' => [['q' => 'دراز نشست یا کرانچ؟', 'a' => 'کرانچ فشار کمتر کمر؛ دراز نشست hip flexor بیشتر.']],
        'summary' => 'دراز و نشست تمرین پایه شکم برای استقامت Core.',
        'summary_keys' => 'شکم منقبض | بدون کشش گردن | تمپو',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['hip_flexors'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'spinal_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'lying_supine', 'grip_type' => 'none', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'core_spine',
            'muscle_targets' => ['abs' => 85, 'hip_flexors' => 50, 'obliques' => 20],
            'met' => 3.5, 'movement_distance_cm' => 45, 'calories_per_1000kg' => 30, 'exercise_difficulty_score' => 3, 'typical_rpe' => 6.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'endurance', 'recommended_sets' => '3-4',
            'rep_range_strength' => '', 'rep_range_hypertrophy' => '15-25', 'rep_range_endurance' => '20-40', 'rest_seconds' => 45, 'tempo' => '2-1-2',
            'short_description' => 'دراز و نشست برای شکم و فلکسور لگن با دامنه کامل.',
            'target_area' => 'شکم',
        ],
        'rank_extra' => 'Core کلاسیک.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-13',
        'slug' => 'پلانک-جانبی',
        'title' => 'پلانک جانبی',
        'aliases' => ['Side Plank', 'Side Bridge', 'پلانک پهلو'],
        'intro' => '<strong>پلانک جانبی</strong> تمرین ایزومتریک برای مورب‌ها و Core پایدار است. مکمل پلانک جلو برای کمر سالم و فرم میان‌تنه در برنامه‌های ایرانی.',
        'caption' => 'پلانک جانبی — خط بدن از سر تا پا',
        'quick' => ['main' => 'مورب‌ها', 'secondary' => 'شکم، گلوت', 'difficulty' => 'مبتدی', 'equipment' => 'بدون تجهیزات', 'type' => 'Core / استقامتی'],
        'tips' => ['لگن بالا نگه دارید.', 'آرنج زیر شانه.', 'نفس عادی.'],
        'setup' => ['پهلو، آرنج زیر شانه.', 'پا روی هم یا جلو.', 'بدن صاف.'],
        'execution' => ['بالا بردن لگن.', 'خط سر تا پا.', 'نگه‌داشتن زمان.', 'تعویض پهلو.'],
        'breathing' => 'تنفس عادی — نفس حبس نکنید.',
        'muscles' => ['اصلی: obliques', 'کمکی: glutes، abs', 'تثبیت: shoulder'],
        'mistakes' => [['لگن افتاده', 'بالا بردن'], ['سر آویزان', 'گردن خنثی'], ['آرنج دور از شانه', 'تراز شانه-آرنج']],
        'program' => [['استقامت', '۳', '۳۰–۶۰ث', '۳۰ث'], ['حجم', '۳', '۴۵–۹۰ث', '۴۵ث'], ['پیشرفته', '۳', 'با بالا بردن پا', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کرانچ', 'slug' => 'کرانچ']],
        'faqs' => [['q' => 'روی آرنج یا دست؟', 'a' => 'آرنج راحت‌تر؛ دست سخت‌تر برای مچ.']],
        'summary' => 'پلانک جانبی برای Core پایدار و مورب‌ها.',
        'summary_keys' => 'لگن بالا | خط بدن صاف | تنفس عادی',
        'meta' => [
            'main_muscle' => 'obliques', 'secondary_muscle_keys' => ['abs', 'glutes'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'anti_lateral_flexion', 'body_engagement' => 'core_dominant',
            'mechanics_type' => 'isometric', 'force_type' => 'static', 'plane_of_motion' => 'frontal', 'laterality' => 'unilateral',
            'posture' => 'side_lying', 'grip_type' => 'none', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'core_spine',
            'muscle_targets' => ['obliques' => 90, 'abs' => 50, 'glutes' => 35, 'shoulder_lateral' => 25],
            'met' => 3, 'movement_distance_cm' => 0, 'calories_per_1000kg' => 25, 'exercise_difficulty_score' => 3, 'typical_rpe' => 6,
            'estimated_1rm_formula' => '', 'programming_goal' => 'endurance', 'recommended_sets' => '3',
            'rep_range_strength' => '', 'rep_range_hypertrophy' => '', 'rep_range_endurance' => '30-90 sec', 'rest_seconds' => 45, 'tempo' => 'isometric',
            'short_description' => 'پلانک جانبی ایزومتریک برای مورب‌ها و Core.',
            'target_area' => 'مورب‌ها',
        ],
        'rank_extra' => 'Core پایدار و کمر سالم.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-14',
        'slug' => 'پاروی-صورت',
        'title' => 'پاروی صورت',
        'aliases' => ['Face Pull', 'Cable Face Pull', 'Rope Face Pull', 'کابل به صورت'],
        'intro' => '<strong>پاروی صورت</strong> (Face Pull) کشش افقی با طناب برای سرشانه خلفی، ذوزنقه و سلامت شانه است. در سالن‌های ایرانی برای posture و prehab بسیار توصیه می‌شود.',
        'caption' => 'پاروی صورت — آرنج بالا و کشش به پیشانی',
        'quick' => ['main' => 'سرشانه خلفی، ذوزنقه', 'secondary' => 'رomboids', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش، طناب', 'type' => 'prehab / حجمی'],
        'tips' => ['آرنج بالا و باز.', 'کشش به پیشانی/کنار.', 'کتف جمع عقب.'],
        'setup' => ['پولی بالا، طناب.', 'گام عقب، کابل کشیده.', 'گرفتن انتهای طناب.'],
        'execution' => ['کشش طناب به صورت.', 'آرنج بالا و باز.', 'مکث عقب.', 'بازگشت کنترل.'],
        'breathing' => 'بازدم کشش — دم باز.',
        'muscles' => ['اصلی: shoulder posterior، traps', 'کمکی: rhomboids', 'تثبیت: Core'],
        'mistakes' => [['وزنه سنگین', 'سبک و کنترل'], ['آرنج پایین', 'آرنج بالا'], ['کمر قوس', 'تنه ثابت']],
        'program' => [['prehab', '۳–۴', '۱۵–۲۰', '۴۵ث'], ['حجم', '۳', '۱۲–۱۵', '۶۰ث'], ['گرم‌کردن', '۲', '۱۵', '۳۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'رویینگ سیمکش', 'slug' => 'رویینگ-سیمکش']],
        'faqs' => [['q' => 'چند بار در هفته؟', 'a' => '۲–۴ بار؛ عالی برای سلامت شانه.']],
        'summary' => 'Face Pull برای شانه سالم و posture.',
        'summary_keys' => 'آرنج بالا | کتف جمع | وزنه سبک',
        'meta' => [
            'main_muscle' => 'shoulder_posterior', 'secondary_muscle_keys' => ['traps_upper', 'rhomboids'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'transverse', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'shoulder',
            'muscle_targets' => ['shoulder_posterior' => 90, 'traps_upper' => 70, 'rhomboids' => 55],
            'met' => 3.5, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 32, 'exercise_difficulty_score' => 2, 'typical_rpe' => 6,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '', 'rep_range_hypertrophy' => '12-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پاروی صورت برای سرشانه خلفی، ذوزنقه و posture.',
            'target_area' => 'سرشانه خلفی',
        ],
        'rank_extra' => 'سلامت شانه و posture.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-15',
        'slug' => 'پرس-سینه-مایل-دمبل',
        'title' => 'پرس سینه مایل دمبل',
        'aliases' => ['Incline Dumbbell Press', 'Incline DB Press', 'پرس دمبل شیب دار'],
        'intro' => '<strong>پرس سینه مایل دمبل</strong> فشار افقی روی نیمکت شیب‌دار برای بالاسینه است. ترکیب دامنه دمبل و زاویه شیب آن را در سالن‌های ایرانی بسیار محبوب کرده است.',
        'caption' => 'پرس سینه مایل دمبل — شیب ۱۵–۳۰ درجه',
        'quick' => ['main' => 'سینه بالایی', 'secondary' => 'سرشانه قدامی، پشت بازو', 'difficulty' => 'متوسط', 'equipment' => 'دمبل، نیمکت شیب‌دار', 'type' => 'قدرتی / حجمی'],
        'tips' => ['شیب ۱۵–۳۰ درجه.', 'دمبل به خط بالای سینه.', 'کتف جمع.'],
        'setup' => ['نیمکت شیب‌دار.', 'دمبل کنار شانه.', 'پا ثابت.'],
        'execution' => ['پایین کنترل‌شده.', 'آرنج ۴۵–۶۰ درجه.', 'بازدم فشار بالا.', 'دمبل نزدیک در بالا.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: chest upper', 'کمکی: triceps، anterior deltoid', 'تثبیت: Core'],
        'mistakes' => [['شیب ۴۵°+', '۱۵–۳۰°'], ['دمبل برخورد', 'مسیر کنترل'], ['کتف شل', 'جمع قبل از تکرار']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۶۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'پرس سینه شیب دار', 'slug' => 'پرس-سینه-شیب-دار']],
        'faqs' => [['q' => 'دمبل یا هالتر؟', 'a' => 'دمبل دامنه بیشتر؛ هالتر بار سنگین‌تر.']],
        'summary' => 'پرس مایل دمبل برای بالاسینه پر و قوی.',
        'summary_keys' => 'شیب ملایم | کتف جمع | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest_upper', 'secondary_muscle_keys' => ['shoulder_anterior', 'triceps'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell', 'incline_bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'incline', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'shoulder_elbow',
            'muscle_targets' => ['chest_upper' => 95, 'chest_middle' => 65, 'shoulder_anterior' => 45, 'triceps' => 40],
            'met' => 6, 'movement_distance_cm' => 42, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '5-8', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پرس سینه مایل دمبل برای بالاسینه، سرشانه و پشت بازو.',
            'target_area' => 'سینه بالایی',
        ],
        'rank_extra' => 'بالاسینه با دامنه دمبل.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-16',
        'slug' => 'پول-اور',
        'title' => 'پول اور',
        'aliases' => ['Dumbbell Pullover', 'Pullover', 'DB Pullover', 'پول‌اور دمبل'],
        'intro' => '<strong>پول اور</strong> حرکت کششی برای سینه و زیربغل روی نیمکت است. در برنامه‌های سینه/پشت ایرانی به‌عنوان حرکت ترکیبی منحصربه‌فرد بسیار شناخته شده است.',
        'caption' => 'پول اور — آرنج نرم و کشش کنترل‌شده',
        'quick' => ['main' => 'سینه، زیربغل', 'secondary' => 'سرشانه، serratus', 'difficulty' => 'متوسط', 'equipment' => 'دمبل، نیمکت', 'type' => 'حجمی'],
        'tips' => ['آرنج کمی خم ثابت.', 'پایین تا کشش ملایم.', 'مسیر قوسی.'],
        'setup' => ['عرض نیمکت، سر و کتف پشتیبانی.', 'دمبل دو دست بالای سینه.', 'پا ثابت.'],
        'execution' => ['پایین دمبل پشت سر.', 'کشش سینه/لات.', 'بازگشت قوسی به بالا.', 'انقباض بالا.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: chest، lats', 'کمکی: triceps long head', 'تثبیت: Core'],
        'mistakes' => [['آرنج باز', 'آرنج ثابت'], ['کمر بیش از حد قوس', 'ثبات کتف'], ['وزنه سنگین', 'دامنه کنترل']],
        'program' => [['حجم', '۳', '۱۰–۱۵', '۶۰–۹۰ث'], ['کشش', '۳', '۱۲–۱۵', '۶۰ث'], ['فینشر', '۲', '۱۵', '۴۵ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'فلای دمبل', 'slug' => 'فلای-دمبل']],
        'faqs' => [['q' => 'سینه یا پشت؟', 'a' => 'هر دو؛ زاویه آرنج و ذهنیت تمرکز را تعیین می‌کند.']],
        'summary' => 'پول اور برای کشش سینه و زیربغل.',
        'summary_keys' => 'آرنج ثابت | کشش کنترل | قوس حرکت',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['back_lat', 'shoulder_anterior'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell', 'bench'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'shoulder_extension', 'body_engagement' => 'compound',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'lying_supine', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'shoulder',
            'muscle_targets' => ['chest' => 75, 'back_lat' => 70, 'chest_upper' => 50, 'triceps' => 30],
            'met' => 4, 'movement_distance_cm' => 55, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3',
            'rep_range_strength' => '8-10', 'rep_range_hypertrophy' => '10-15', 'rep_range_endurance' => '12-15', 'rest_seconds' => 75, 'tempo' => '3-1-2',
            'short_description' => 'پول اور کشش برای سینه، زیربغل و serratus.',
            'target_area' => 'سینه و زیربغل',
        ],
        'rank_extra' => 'کشش منحصربه‌فرد سینه/پشت.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-17',
        'slug' => 'جلو-بازو-سیمکش',
        'title' => 'جلو بازو سیمکش',
        'aliases' => ['Cable Curl', 'Straight Bar Cable Curl', 'کرل سیمکش'],
        'intro' => '<strong>جلو بازو سیمکش</strong> کرل با کابل برای تنش مداوم روی جلوبازو است. در Arms Day سالن‌های ایرانی جایگزین محبوب کرل هالتر برای پمپ است.',
        'caption' => 'جلو بازو سیمکش — آرنج ثابت، تنش مداوم',
        'quick' => ['main' => 'جلوبازو', 'secondary' => 'براکیالیس، ساعد', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'حجمی'],
        'tips' => ['آرنج کنار بدن.', 'پایین کامل.', 'بدون تاب.'],
        'setup' => ['پولی پایین، میله یا دستگیره.', 'ایستاده، آرنج ثابت.', 'Core سفت.'],
        'execution' => ['خم آرنج تا انقباض.', 'مکث کوتاه.', 'پایین آهسته.', 'تکرار.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: biceps', 'کمکی: brachialis، forearms', 'تثبیت: Core'],
        'mistakes' => [['تاب بدن', 'وزنه سبک'], ['آرنج جلو', 'ثابت'], ['نیمه دامنه', 'کامل']],
        'program' => [['حجم', '۳–۴', '۱۲–۱۵', '۴۵–۶۰ث'], ['پمپ', '۳', '۱۵–۲۰', '۳۰ث'], ['استقامت', '۳', '۱۵–۲۰', '۳۰ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'جلو بازو دمبل', 'slug' => 'جلو-بازو-دمبل']],
        'faqs' => [['q' => 'میله یا دستگیره؟', 'a' => 'میله هر دو دست؛ دستگیره تک دست تمرکز بیشتر.']],
        'summary' => 'کرل سیمکش برای پمپ جلوبازو.',
        'summary_keys' => 'تنش مداوم | آرنج ثابت | تمپو',
        'meta' => [
            'main_muscle' => 'biceps', 'secondary_muscle_keys' => ['brachialis', 'forearms'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'elbow_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'supinated', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'elbow',
            'muscle_targets' => ['biceps' => 95, 'brachialis' => 45, 'forearms' => 35],
            'met' => 3.5, 'movement_distance_cm' => 42, 'calories_per_1000kg' => 34, 'exercise_difficulty_score' => 2, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '8-10', 'rep_range_hypertrophy' => '12-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 45, 'tempo' => '2-1-2',
            'short_description' => 'جلو بازو سیمکش برای هایپرتروفی جلوبازو با تنش مداوم.',
            'target_area' => 'جلوبازو',
        ],
        'rank_extra' => 'پمپ جلوبازو با کابل.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-18',
        'slug' => 'پشت-بازو-کیک-بک',
        'title' => 'پشت بازو کیک بک',
        'aliases' => ['Triceps Kickback', 'DB Kickback', 'Dumbbell Kickback', 'کیک‌بک'],
        'intro' => '<strong>پشت بازو کیک بک</strong> حرکت ایزوله برای سه‌سر در حالت خم با تمرکز بر peak contraction است. در Arms Day ایرانی برای اتمام تمرین پشت بازو رایج است.',
        'caption' => 'پشت بازو کیک بک — آرنج ثابت، بازو موازی زمین',
        'quick' => ['main' => 'پشت بازو', 'secondary' => 'ساعد', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل', 'type' => 'حجمی'],
        'tips' => ['آرنج ثابت کنار بدن.', 'بازو موازی زمین.', 'بازگشت تا صاف پشت.'],
        'setup' => ['خم جلو، یک دست روی نیمکت.', 'دمبل در دست آزاد.', 'آرنج ۹۰°.'],
        'execution' => ['باز کردن آرنج عقب.', 'مکث در انقباض.', 'پایین کنترل.', 'تعویض دست.'],
        'breathing' => 'بازدم عقب — دم جلو.',
        'muscles' => ['اصلی: triceps', 'کمکی: forearms', 'تثبیت: Core، shoulder'],
        'mistakes' => [['آرنج حرکت', 'ثابت'], ['وزنه سنگین', 'سبک و کنترل'], ['کمر چرخش', 'تنه ثابت']],
        'program' => [['حجم', '۳–۴', '۱۲–۱۵', '۴۵ث'], ['فینشر', '۲–۳', '۱۵–۲۰', '۳۰ث'], ['تک دست', '۳', '۱۰–۱۲', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت بازو پشت سر', 'slug' => 'پشت-بازو-پشت-سر']],
        'faqs' => [['q' => 'کیک بک مؤثر است؟', 'a' => 'بله برای peak؛ با وزنه سبک و فرم درست.']],
        'summary' => 'کیک بک برای اتمام و فرم سه‌سر.',
        'summary_keys' => 'آرنج ثابت | انقباض peak | وزنه سبک',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell', 'bench'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'elbow_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'unilateral',
            'posture' => 'bent_over', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'elbow',
            'muscle_targets' => ['triceps' => 90, 'forearms' => 25],
            'met' => 3, 'movement_distance_cm' => 35, 'calories_per_1000kg' => 30, 'exercise_difficulty_score' => 2, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '', 'rep_range_hypertrophy' => '12-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 45, 'tempo' => '2-1-2',
            'short_description' => 'پشت بازو کیک بک ایزوله برای سه‌سر با peak contraction.',
            'target_area' => 'پشت بازو',
        ],
        'rank_extra' => 'peak contraction سه‌سر.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-19',
        'slug' => 'لانج-راه-رفتن',
        'title' => 'لانج راه رفتن',
        'aliases' => ['Walking Lunge', 'Forward Walking Lunge', 'لانج قدم‌زن'],
        'intro' => '<strong>لانج راه رفتن</strong> (Walking Lunge) حرکت تک‌پا پویا برای چهارسر، باسن و تعادل است. در تمرینات پا و چربی‌سوزی سالن‌های ایرانی بسیار محبوب است.',
        'caption' => 'لانج راه رفتن — قدم بلند و زانو ۹۰ درجه',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، همسترینگ', 'difficulty' => 'مبتدی', 'equipment' => 'بدون تجهیزات (یا دمبل)', 'type' => 'قدرتی / عملکردی'],
        'tips' => ['قدم بلند.', 'زانو جلو روی مچ.', 'تنه عمودی.'],
        'setup' => ['ایستاده، Core سفت.', 'دمبل اختیاری.', 'فضای کافی جلو.'],
        'execution' => ['قدم جلو و پایین.', 'زانو عقب نزدیک زمین.', 'فشار جلو، قدم بعدی.', 'ادامه راه رفتن.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: quadriceps', 'کمکی: glutes، hamstrings', 'تثبیت: Core'],
        'mistakes' => [['قدم کوتاه', 'قدم بلندتر'], ['زانو جلو زیاد', 'مچ پا'], ['تنه جلو', 'عمودی']],
        'program' => [['حجم', '۳', '۱۰–۱۲ هر پا', '۶۰ث'], ['استقامت', '۳', '۲۰ قدم', '۴۵ث'], ['قدرت', '۳', '۸', '۹۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'لانج', 'slug' => 'لانج']],
        'faqs' => [['q' => 'عقب یا جلو؟', 'a' => 'راه رفتن جلو؛ backward lunge ثبات بیشتر.']],
        'summary' => 'لانج راه رفتن برای پا، باسن و تعادل.',
        'summary_keys' => 'قدم بلند | تنه عمودی | حرکت پویا',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'hamstrings'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight', 'dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'lunge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'alternating',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'knee_hip',
            'muscle_targets' => ['quads' => 90, 'glutes' => 80, 'hamstrings' => 45, 'abs' => 30],
            'met' => 5, 'movement_distance_cm' => 55, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '10-12', 'rep_range_endurance' => '12-20', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'لانج راه رفتن تک‌پا پویا برای چهارسر، باسن و تعادل.',
            'target_area' => 'پا و باسن',
        ],
        'rank_extra' => 'تمرین پا پویا و عملکردی.',
    ]);

    $add([
        'image_key' => 'exercise-batch3-20',
        'slug' => 'هاک-اسکات',
        'title' => 'هاک اسکات',
        'aliases' => ['Hack Squat', 'Machine Hack Squat', 'اسکات هاک'],
        'intro' => '<strong>هاک اسکات</strong> اسکات روی دستگاه با پشتیبانی پشت برای تمرکز روی چهارسر است. در سالن‌های ایرانی جایگزین محبوب اسکات آزاد برای حجم پا محسوب می‌شود.',
        'caption' => 'هاک اسکات — پا جلو، عمق کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن', 'difficulty' => 'متوسط', 'equipment' => 'دستگاه Hack Squat', 'type' => 'قدرتی / حجمی'],
        'tips' => ['پا جلوتر برای چهارسر.', 'کمر به پد.', 'عمق تا ران موازی.'],
        'setup' => ['پشت به پد، شانه زیر پد.', 'پا روی پلتفرم.', 'گرفتن دستگیره.'],
        'execution' => ['پایین کنترل‌شده.', 'زانو هم‌راستا پا.', 'فشار پا برای بالا.', 'بدون قفل سخت.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: quadriceps', 'کمکی: glutes', 'تثبیت: Core'],
        'mistakes' => [['پا خیلی عقب', 'جلوتر برای quad'], ['کمر از پد', 'تماس کامل'], ['عمق ناقص', 'ران موازی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۹۰–۱۲۰ث'], ['قدرت', '۴', '۶–۸', '۱۵۰ث'], ['پمپ', '۳', '۱۲–۱۵', '۶۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'اسکات گابلت', 'slug' => 'اسکات-گابلت']],
        'faqs' => [['q' => 'هاک یا اسکات آزاد؟', 'a' => 'هاک quad بیشتر و امن‌تر؛ آزاد کل بدن.']],
        'summary' => 'هاک اسکات برای حجم چهارسر با ثبات.',
        'summary_keys' => 'پا جلو | کمر ثابت | عمق کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'squat', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'none', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'knee_hip',
            'muscle_targets' => ['quads' => 95, 'glutes' => 55, 'hamstrings' => 30],
            'met' => 5.5, 'movement_distance_cm' => 50, 'calories_per_1000kg' => 48, 'exercise_difficulty_score' => 4, 'typical_rpe' => 8,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-8', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 120, 'tempo' => '2-1-2',
            'short_description' => 'هاک اسکات دستگاه برای حجم چهارسر با ثبات پشت.',
            'target_area' => 'چهارسر',
        ],
        'rank_extra' => 'حجم چهارسر با دستگاه.',
    ]);


    return $defs;
}
}
