// GymAI Popular — BATCH 5 (20 حرکت)
// Code Snippets: Run everywhere | بدون تگ php

if (!function_exists('gymai_pop20_batch5_definitions')) {
function gymai_pop20_batch5_definitions() {
    $base_img = 'https://gymaipro.ir/wp-content/uploads/2026/06/';
    $defs = [];
    $add = function (array $row) use (&$defs, $base_img) {
        if (empty($row['image'])) {
            $key = !empty($row['image_key']) ? $row['image_key'] : ('exercise-batch5-' . str_pad((string) (count($defs) + 1), 2, '0', STR_PAD_LEFT));
            $row['image'] = $base_img . $key . '.jpg';
        }
        $defs[] = $row;
    };

    $add([
        'image_key' => 'exercise-batch5-01',
        'slug' => 'اسکات-اسمیت',
        'title' => 'اسکات اسمیت',
        'aliases' => ['Smith Squat', 'SmithSquat', 'اسکات اسمیت'],
        'intro' => '<strong>اسکات اسمیت</strong> (Smith Squat) اسکات با میله ثابت روی دستگاه اسمیت؛ در اکثر سالن‌های ایرانی برای یادگیری عمق اسکات و افزایش بار امن بسیار رایج است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'اسکات اسمیت — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، همسترینگ، Core', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن، همسترینگ، Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'اسکات گابلت', 'slug' => 'اسکات-گابلت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'اسکات اسمیت برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'hamstrings', 'abs'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'squat', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 90, 'glutes' => 80, 'hamstrings' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'اسکات با دستگاه اسمیت برای پا با ثبات بالا.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'ثبات بیشتر نسبت به اسکات آزاد.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-02',
        'slug' => 'پرس-سینه-شیب-منفی',
        'title' => 'پرس سینه شیب منفی',
        'aliases' => ['Decline Bench Press', 'DeclineBenchPress', 'پرس سینه شیب منفی'],
        'intro' => '<strong>پرس سینه شیب منفی</strong> (Decline Bench Press) فشار افقی روی نیمکت شیب منفی؛ در روز سینه برای تکمیل پرس تخت و شیب مثبت در بدنسازی ایران بسیار شناخته‌شده است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر و نیمکت اجرا می‌شود.',
        'caption' => 'پرس سینه شیب منفی — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'پشت بازو، سرشانه', 'difficulty' => 'متوسط', 'equipment' => 'هالتر و نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: پشت بازو، سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پرس سینه با هالتر', 'slug' => 'پرس-سینه-با-هالتر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'پرس سینه شیب منفی برای سینه پایین و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['triceps', 'shoulder_anterior'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest_lower' => 95, 'chest' => 85, 'triceps' => 50],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پرس سینه شیب منفی برای سینه پایین و پشت بازو.',
            'target_area' => 'سینه پایین',
        ],
        'rank_extra' => 'تمرکز روی سینه پایین.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-03',
        'slug' => 'فلای-سیمکش',
        'title' => 'فلای سیمکش',
        'aliases' => ['Cable Fly', 'CableFly', 'فلای سیمکش'],
        'intro' => '<strong>فلای سیمکش</strong> (Cable Fly) حرکت ایزوله سینه با سیم‌کش؛ کشش مداوم و کنترل تمپو آن را در سالن‌های ایرانی برای پمپ سینه محبوب کرده است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'فلای سیمکش — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'سرشانه', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کراس سیمکش', 'slug' => 'کراس-سیمکش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'فلای سیمکش برای سینه و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['shoulder_anterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest' => 90, 'chest_middle' => 85],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'فلای سیمکش برای کشش و انقباض سینه.',
            'target_area' => 'سینه',
        ],
        'rank_extra' => 'کشش مداوم کابل.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-04',
        'slug' => 'فلای-معکوس-سیمکش',
        'title' => 'فلای معکوس سیمکش',
        'aliases' => ['Reverse Cable Fly', 'ReverseCableFly', 'فلای معکوس سیمکش'],
        'intro' => '<strong>فلای معکوس سیمکش</strong> (Reverse Cable Fly) حرکت عقب‌انداز با سیم‌کش برای دلتوئید خلفی؛ اصلاح وضعیت شانه و تعادل شانه در برنامه‌های ایرانی ضروری است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'فلای معکوس سیمکش — سرشانه پشت، اجرای کنترل‌شده',
        'quick' => ['main' => 'سرشانه پشت', 'secondary' => 'ذوزنقه، پشت میانی', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی سرشانه پشت در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سرشانه پشت', 'کمکی: ذوزنقه، پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پاروی صورت', 'slug' => 'پاروی-صورت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'فلای معکوس سیمکش برای سرشانه پشت و سرشانه پشت در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سرشانه پشت | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_posterior', 'secondary_muscle_keys' => ['traps_middle', 'rhomboids'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_posterior' => 95, 'rhomboids' => 50],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'فلای معکوس برای سرشانه پشت و پشت میانی.',
            'target_area' => 'سرشانه پشت',
        ],
        'rank_extra' => 'سلامت شانه و پشت.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-05',
        'slug' => 'زیربغل-تی-بار',
        'title' => 'زیربغل تی‌بار',
        'aliases' => ['T-Bar Row', 'T-BarRow', 'زیربغل تی‌بار'],
        'intro' => '<strong>زیربغل تی‌بار</strong> (T-Bar Row) کشش افقی با بار تی یا دستگاه؛ یکی از حرکات کلاسیک روز پشت در باشگاه‌های ایرانی برای ضخامت زیربغل است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر و دستگاه اجرا می‌شود.',
        'caption' => 'زیربغل تی‌بار — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو، پشت میانی، ذوزنقه', 'difficulty' => 'متوسط', 'equipment' => 'هالتر و دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو، پشت میانی، ذوزنقه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'رویینگ هالتر', 'slug' => 'رویینگ-هالتر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'زیربغل تی‌بار برای زیربغل و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'rhomboids', 'traps_middle'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell', 'machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'bent_over', 'grip_type' => 'pronated', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 90, 'rhomboids' => 55, 'biceps' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'تی‌بار برای ضخامت وسط پشت.',
            'target_area' => 'زیربغل',
        ],
        'rank_extra' => 'ضخامت پشت.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-06',
        'slug' => 'بارفیکس-کمکی',
        'title' => 'بارفیکس کمکی',
        'aliases' => ['Assisted Pull-Up', 'AssistedPull-Up', 'بارفیکس کمکی'],
        'intro' => '<strong>بارفیکس کمکی</strong> (Assisted Pull-Up) بارفیکس با کمک وزنه دستگاه؛ بهترین گزینه مبتدی قبل از بارفیکس آزاد در سالن‌های ایرانی است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'بارفیکس کمکی — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو، پشت میانی', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو، پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'بارفیکس', 'slug' => 'بارفیکس']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'بارفیکس کمکی برای زیربغل و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'rhomboids'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 85, 'biceps' => 50],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'بارفیکس کمکی برای ساخت قدرت کشش عمودی.',
            'target_area' => 'زیربغل',
        ],
        'rank_extra' => 'مسیر یادگیری بارفیکس.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-07',
        'slug' => 'چین-آپ',
        'title' => 'چین آپ',
        'aliases' => ['Chin-Up', 'Chin-Up', 'چین آپ'],
        'intro' => '<strong>چین آپ</strong> (Chin-Up) کشش عمودی با کف دست رو به خود؛ در مقایسه با بارفیکس جلو بازو بیشتر درگیر می‌شود و در خانه و پارک ایران محبوب است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن و میله اجرا می‌شود.',
        'caption' => 'چین آپ — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن و میله', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و میله و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'بارفیکس', 'slug' => 'بارفیکس']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'چین آپ برای زیربغل و جلو بازو و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight', 'bar'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'hanging', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 85, 'biceps' => 70],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'چین آپ با دست معکوس برای زیربغل و جلو بازو.',
            'target_area' => 'زیربغل و جلو بازو',
        ],
        'rank_extra' => 'جلوبازو و زیربغل با هم.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-08',
        'slug' => 'رویینگ-پندلی',
        'title' => 'رویینگ پندلی',
        'aliases' => ['Pendlay Row', 'PendlayRow', 'رویینگ پندلی'],
        'intro' => '<strong>رویینگ پندلی</strong> (Pendlay Row) رویینگ از زمین با تنه افقی؛ حرکت قدرتی پشت محبوب در تمرین‌های هالتر ایرانی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'رویینگ پندلی — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو، پشت میانی، ذوزنقه', 'difficulty' => 'متوسط', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو، پشت میانی، ذوزنقه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'ددلیفت', 'slug' => 'ددلیفت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'رویینگ پندلی برای پشت و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'rhomboids', 'traps_middle'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'bent_over', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 88, 'rhomboids' => 60, 'traps_middle' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پندلی‌رو برای قدرت و ضخامت پشت.',
            'target_area' => 'پشت',
        ],
        'rank_extra' => 'قدرت کششی پشت.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-09',
        'slug' => 'پرس-زمین-هالتر',
        'title' => 'پرس زمین هالتر',
        'aliases' => ['Floor Press', 'FloorPress', 'پرس زمین هالتر'],
        'intro' => '<strong>پرس زمین هالتر</strong> (Floor Press) پرس هالتر روی زمین؛ برای قدرت قفل میانی و سینه بدون استرس شانه در سالن‌های ایرانی گزینه خوبی است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'پرس زمین هالتر — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'پشت بازو', 'difficulty' => 'متوسط', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: پشت بازو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پرس سینه با هالتر', 'slug' => 'پرس-سینه-با-هالتر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'پرس زمین هالتر برای سینه و پشت بازو و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['triceps'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest' => 85, 'triceps' => 55],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پرس زمین محدودیت دامنه برای شانه امن.',
            'target_area' => 'سینه و پشت بازو',
        ],
        'rank_extra' => 'فشار میانی امن.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-10',
        'slug' => 'پرس-آرنولد',
        'title' => 'پرس آرنولد',
        'aliases' => ['Arnold Press', 'ArnoldPress', 'پرس آرنولد'],
        'intro' => '<strong>پرس آرنولد</strong> (Arnold Press) پرس دمبل با چرخش کف دست؛ حرکت کلاسیک آرنولد شوارتزنگگر و محبوب برای سرشانه در بدنسازی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل اجرا می‌شود.',
        'caption' => 'پرس آرنولد — سرشانه قدامی، اجرای کنترل‌شده',
        'quick' => ['main' => 'سرشانه قدامی', 'secondary' => 'shoulder_lateral، پشت بازو', 'difficulty' => 'متوسط', 'equipment' => 'دمبل', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سرشانه قدامی در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سرشانه قدامی', 'کمکی: shoulder_lateral، پشت بازو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پرس سرشانه با دمبل', 'slug' => 'پرس-سرشانه-دمبل']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'پرس آرنولد برای سرشانه و سرشانه قدامی در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سرشانه قدامی | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_anterior', 'secondary_muscle_keys' => ['shoulder_lateral', 'triceps'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_anterior' => 90, 'shoulder_lateral' => 75, 'triceps' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پرس آرنولد برای حجم سرشانه از همه زوایا.',
            'target_area' => 'سرشانه',
        ],
        'rank_extra' => 'حجم سرشانه ۳ بعدی.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-11',
        'slug' => 'نشر-جانب-هالتر',
        'title' => 'نشر جانب با هالتر',
        'aliases' => ['Barbell Lateral Raise', 'BarbellLateralRaise', 'نشر جانب با هالتر'],
        'intro' => '<strong>نشر جانب با هالتر</strong> (Barbell Lateral Raise) بالا بردن هالتر به طرف برای دلتوئید میانی؛ کمتر رایج از دمبل ولی در برنامه‌های قدیمی سالن ایران دیده می‌شود. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'نشر جانب با هالتر — سرشانه جانب، اجرای کنترل‌شده',
        'quick' => ['main' => 'سرشانه جانب', 'secondary' => 'traps_upper', 'difficulty' => 'متوسط', 'equipment' => 'هالتر', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی سرشانه جانب در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سرشانه جانب', 'کمکی: traps_upper', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'نشر جانب سیمکش', 'slug' => 'نشر-جانب-سیمکش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'نشر جانب با هالتر برای سرشانه جانب و سرشانه جانب در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سرشانه جانب | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_lateral', 'secondary_muscle_keys' => ['traps_upper'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'lateral_raise', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_lateral' => 95],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'نشر جانب هالتر برای عرض سرشانه.',
            'target_area' => 'سرشانه جانب',
        ],
        'rank_extra' => 'عرض سرشانه.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-12',
        'slug' => 'نشر-پشت-دمبل',
        'title' => 'نشر پشت با دمبل',
        'aliases' => ['Rear Delt Fly', 'RearDeltFly', 'نشر پشت با دمبل'],
        'intro' => '<strong>نشر پشت با دمبل</strong> (Rear Delt Fly) فلای معکوس با دمبل خم شده؛ برای سلامت شانه و تعادل در کنار پرس‌های سنگین ضروری است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل اجرا می‌شود.',
        'caption' => 'نشر پشت با دمبل — سرشانه پشت، اجرای کنترل‌شده',
        'quick' => ['main' => 'سرشانه پشت', 'secondary' => 'پشت میانی', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی سرشانه پشت در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سرشانه پشت', 'کمکی: پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'فلای معکوس سیمکش', 'slug' => 'فلای-معکوس-سیمکش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'نشر پشت با دمبل برای سرشانه پشت و سرشانه پشت در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سرشانه پشت | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_posterior', 'secondary_muscle_keys' => ['rhomboids'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'bent_over', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_posterior' => 95, 'rhomboids' => 40],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'نشر پشت دمبل برای دلتوئید خلفی.',
            'target_area' => 'سرشانه پشت',
        ],
        'rank_extra' => 'تعادل شانه.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-13',
        'slug' => 'کیک-بک-باسن-سیمکش',
        'title' => 'کیک بک باسن سیمکش',
        'aliases' => ['Cable Glute Kickback', 'CableGluteKickback', 'کیک بک باسن سیمکش'],
        'intro' => '<strong>کیک بک باسن سیمکش</strong> (Cable Glute Kickback) اکستنشن لگ با سیم‌کش؛ برای پمپ و فعال‌سازی گلوت در روز پا بسیار پرطرفدار است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'کیک بک باسن سیمکش — باسن، اجرای کنترل‌شده',
        'quick' => ['main' => 'باسن', 'secondary' => 'همسترینگ', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی باسن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: باسن', 'کمکی: همسترینگ', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'هیپ تراست', 'slug' => 'هیپ-تراست']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'کیک بک باسن سیمکش برای باسن و باسن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'باسن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'glutes', 'secondary_muscle_keys' => ['hamstrings'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'hip_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['glutes' => 95],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'کیک بک سیمکش برای جداسازی باسن.',
            'target_area' => 'باسن',
        ],
        'rank_extra' => 'جداسازی باسن.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-14',
        'slug' => 'استپ-آپ',
        'title' => 'استپ آپ',
        'aliases' => ['Step-Up', 'Step-Up', 'استپ آپ'],
        'intro' => '<strong>استپ آپ</strong> (Step-Up) بالا رفتن روی باکس یا نیمکت با وزنه؛ حرکت عملکردی محبوب در تمرین خانگی و سالن. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل و نیمکت اجرا می‌شود.',
        'caption' => 'استپ آپ — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، همسترینگ', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل و نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن، همسترینگ', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'لانج', 'slug' => 'لانج']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'استپ آپ برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'hamstrings'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'lunge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 85, 'glutes' => 75],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'استپ آپ برای پا تک‌طرفه و تعادل.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'تعادل و پا تک‌طرفه.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-15',
        'slug' => 'ساق-نشسته',
        'title' => 'ساق نشسته',
        'aliases' => ['Seated Calf Raise', 'SeatedCalfRaise', 'ساق نشسته'],
        'intro' => '<strong>ساق نشسته</strong> (Seated Calf Raise) ساق نشسته روی دستگاه؛ برای سولئوس (ساق پایین) در پایان روز پا در ایران استاندارد است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'ساق نشسته — ساق پا، اجرای کنترل‌شده',
        'quick' => ['main' => 'ساق پا', 'secondary' => '—', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی ساق پا در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: ساق پا', 'کمکی: عضلات کمکی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'ساق ایستاده', 'slug' => 'ساق-ایستاده']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'ساق نشسته برای ساق پا و ساق پا در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'ساق پا | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'calves', 'secondary_muscle_keys' => [],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'calf_raise', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['calves' => 95, 'calves_soleus' => 90],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'ساق نشسته برای سولئوس.',
            'target_area' => 'ساق پا',
        ],
        'rank_extra' => 'سولئوس عمیق.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-16',
        'slug' => 'پرس-ساق',
        'title' => 'پرس ساق',
        'aliases' => ['Leg Press Calf Raise', 'LegPressCalfRaise', 'پرس ساق'],
        'intro' => '<strong>پرس ساق</strong> (Leg Press Calf Raise) ساق روی لگ پرس؛ برای بار سنگین‌تر روی گاستrocnemius محبوب است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'پرس ساق — ساق پا، اجرای کنترل‌شده',
        'quick' => ['main' => 'ساق پا', 'secondary' => '—', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی ساق پا در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: ساق پا', 'کمکی: عضلات کمکی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'ساق ایستاده', 'slug' => 'ساق-ایستاده']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پرس ساق برای ساق پا و ساق پا در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'ساق پا | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'calves', 'secondary_muscle_keys' => [],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'calf_raise', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['calves' => 90],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پرس ساق روی دستگاه پرس پا.',
            'target_area' => 'ساق پا',
        ],
        'rank_extra' => 'بار سنگین ساق.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-17',
        'slug' => 'گود-مورنینگ',
        'title' => 'گود مورنینگ',
        'aliases' => ['Good Morning', 'GoodMorning', 'گود مورنینگ'],
        'intro' => '<strong>گود مورنینگ</strong> (Good Morning) هیپ‌هینج با هالتر پشت گردن؛ حرکت پیشرفته برای همسترینگ و کمر در تمرین قدرتی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'گود مورنینگ — همسترینگ، اجرای کنترل‌شده',
        'quick' => ['main' => 'همسترینگ', 'secondary' => 'باسن، lower_back', 'difficulty' => 'پیشرفته', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی همسترینگ در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: همسترینگ', 'کمکی: باسن، lower_back', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'ددلیفت', 'slug' => 'ددلیفت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'گود مورنینگ برای پشت پا و کمر و همسترینگ در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'همسترینگ | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'hamstrings', 'secondary_muscle_keys' => ['glutes', 'lower_back'],
            'difficulty' => 'advanced', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'hip_hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['hamstrings' => 85, 'glutes' => 70, 'lower_back' => 55],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'گود مورنینگ برای هیپ‌هینج و پشت پا.',
            'target_area' => 'پشت پا و کمر',
        ],
        'rank_extra' => 'هیپ‌هینج پیشرفته.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-18',
        'slug' => 'چرخ-شکم',
        'title' => 'چرخ شکم',
        'aliases' => ['Ab Wheel Rollout', 'AbWheelRollout', 'چرخ شکم'],
        'intro' => '<strong>چرخ شکم</strong> (Ab Wheel Rollout) رول‌اوت با چرخ شکم؛ یکی از سخت‌ترین و مؤثرترین حرکات Core در خانه و سالن. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'چرخ شکم — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'سرشانه، زیربغل', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: سرشانه، زیربغل', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پلانک', 'slug' => 'پلانک-plank']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'چرخ شکم برای شکم و Core و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['shoulder_anterior', 'lats'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'anti_extension', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'kneeling', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 90, 'abs_lower' => 85],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'چرخ شکم برای Core قوی.',
            'target_area' => 'شکم و Core',
        ],
        'rank_extra' => 'Core عمیق.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-19',
        'slug' => 'کرانچ-دوچرخه',
        'title' => 'کرانچ دوچرخه',
        'aliases' => ['Bicycle Crunch', 'BicycleCrunch', 'کرانچ دوچرخه'],
        'intro' => '<strong>کرانچ دوچرخه</strong> (Bicycle Crunch) کرانچ چرخشی درازکش؛ برای تعریف شکم و پهلو در تمرین خانگی ایران بسیار رایج است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'کرانچ دوچرخه — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'پهلو', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: پهلو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کرانچ', 'slug' => 'کرانچ']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'کرانچ دوچرخه برای شکم و پهلو و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['obliques'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'rotation', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 85, 'obliques' => 75],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'کرانچ دوچرخه برای شکم و پهلو.',
            'target_area' => 'شکم و پهلو',
        ],
        'rank_extra' => 'شکم و پهلو.',
    ]);

    $add([
        'image_key' => 'exercise-batch5-20',
        'slug' => 'سوپرمن',
        'title' => 'سوپرمن',
        'aliases' => ['Superman', 'Superman', 'سوپرمن'],
        'intro' => '<strong>سوپرمن</strong> (Superman) بالا بردن همزمان دست و پا درازکش؛ حرکت اصلاحی و تقویتی کمر برای نشستن طولانی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'سوپرمن — کمر، اجرای کنترل‌شده',
        'quick' => ['main' => 'کمر', 'secondary' => 'باسن، همسترینگ', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی کمر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: کمر', 'کمکی: باسن، همسترینگ', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کوهنورد', 'slug' => 'کوهنورد']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'سوپرمن برای کمر و باسن و کمر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'کمر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'lower_back', 'secondary_muscle_keys' => ['glutes', 'hamstrings'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'back_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'prone', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['lower_back' => 85, 'glutes' => 50],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'سوپرمن برای تقویت کمر پایین.',
            'target_area' => 'کمر و باسن',
        ],
        'rank_extra' => 'کمر اصلاحی.',
    ]);

    return $defs;
}
}
