// GymAI Popular 20 — BATCH 2 (10 حرکت دوم)
// Code Snippets: Run everywhere | بدون تگ php

if (!function_exists('gymai_pop20_batch2_definitions')) {
function gymai_pop20_batch2_definitions() {
    $base_img = 'https://gymaipro.ir/wp-content/uploads/2026/06/';
    $defs = [];
    $add = function (array $row) use (&$defs, $base_img) {
        if (empty($row['image'])) {
            $key = !empty($row['image_key']) ? $row['image_key'] : ('exercise-' . (count($defs) + 11));
            $row['image'] = $base_img . $key . '.jpg';
        }
        $defs[] = $row;
    };

    $add([
        'slug' => 'جلو-بازو-دمبل',
        'title' => 'جلو بازو دمبل',
        'aliases' => ['Dumbbell Curl', 'Standing Dumbbell Curl', 'Alternating DB Curl', 'کرل دمبل'],
        'intro' => '<strong>جلو بازو دمبل</strong> (ایستاده) برای تمرین جداگانه هر دست و دامنه طبیعی‌تر مچ نسبت به نسخه نشسته.',
        'caption' => 'جلو بازو دمبل ایستاده',
        'quick' => ['main' => 'جلوبازو', 'secondary' => 'براکیالیس، ساعد', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل', 'type' => 'حجمی'],
        'tips' => ['آرنج ثابت.', 'چرخش neutral به supinated اختیاری.', 'کنترل پایین.'],
        'setup' => ['دمبل کنار بدن.', 'ایستاده متعادل.', 'شانه پایین.'],
        'execution' => ['خم آرنج تا انقباض.', 'پایین آهسته.', 'تناوبی یا همزمان.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: biceps', 'کمکی: brachialis', 'تثبیت: Core'],
        'mistakes' => [['تاب بدن', 'وزنه سبک‌تر'], ['آرنج جلو', 'کنار تنه'], ['کوتاه کردن دامنه', 'پایین کامل']],
        'program' => [['حجم', '۳–۴', '۱۰–۱۵', '۴۵–۶۰ث'], ['استقامت', '۳', '۱۵–۲۰', '۳۰ث'], ['قدرت', '۳', '۶–۱۰', '۷۵ث']],
        'combos' => [['label' => 'سوپرسِت: ', 'link_text' => 'جلو بازو هالتر', 'slug' => 'جلو-بازو-هالتر']],
        'faqs' => [['q' => 'فرق با نشسته؟', 'a' => 'نشسته تاب کمتر؛ ایستاده Core بیشتر و طبیعی‌تر.']],
        'summary' => 'کرل دمبل برای Arms متعادل و فرم خوب.',
        'summary_keys' => 'آرنج ثابت | تمپو کنترل | هر دست جدا',
        'meta' => [
            'main_muscle' => 'biceps', 'secondary_muscle_keys' => ['brachialis', 'forearms'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'elbow_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'alternating',
            'posture' => 'standing', 'grip_type' => 'supinated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'elbow',
            'muscle_targets' => ['biceps' => 95, 'brachialis' => 45, 'forearms' => 35],
            'met' => 3.5, 'movement_distance_cm' => 45, 'calories_per_1000kg' => 35, 'exercise_difficulty_score' => 2, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '10-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'جلو بازو دمبل ایستاده برای هایپرتروفی جلوبازو با دامنه طبیعی هر دست.',
            'target_area' => 'جلوبازو',
        ],
        'rank_extra' => 'فرم و حجم جلوبازو با دمبل.',
    ]);

    $add([
        'slug' => 'کرانچ',
        'title' => 'کرانچ',
        'aliases' => ['Crunch', 'Abdominal Crunch', 'دراز و نشست نیمه', 'شکم کرانچ'],
        'intro' => '<strong>کرانچ</strong> حرکت فلکشن ستون فقرات برای شکم راست؛ مناسب مبتدی تا متوسط.',
        'caption' => 'کرانچ — بالا آوردن شانه نه کل تنه',
        'quick' => ['main' => 'شکم راست', 'secondary' => 'مورب (کم)', 'difficulty' => 'مبتدی', 'equipment' => 'بدون تجهیزات', 'type' => 'حجمی'],
        'tips' => ['فقط شانه از زمین.', 'چانه به سینه نه به پا.', 'شکم منقبض در بالا.'],
        'setup' => ['پشت روی زمین، زانو خم.', 'دست پشت سر یا روی سینه.', 'کمر به زمین.'],
        'execution' => ['منقبض شکم، شانه بالا.', 'مکث کوتاه.', 'پایین بدون افتادن کامل.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: rectus abdominis', 'کمکی: hip flexors (کم)', 'تثبیت: Core'],
        'mistakes' => [['کشش گردن', 'دست فقط لمس سبک'], ['دراز نشست کامل', 'دامنه کوتاه کرانچ'], ['نفس حبس طولانی', 'تنفس منظم']],
        'program' => [['حجم', '۳–۴', '۱۵–۲۵', '۳۰–۴۵ث'], ['استقامت', '۳', '۲۵–۴۰', '۳۰ث'], ['سنگین', '۳', '۱۰–۱۵ با وزنه', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پلانک', 'slug' => 'پلانک-plank']],
        'faqs' => [['q' => 'کرانچ یا دراز نشست؟', 'a' => 'کرانچ فشار کمتر کمر؛ دراز نشست hip flexor بیشتر.']],
        'summary' => 'کرانچ پایه تمرین شکم برای مبتدی.',
        'summary_keys' => 'شانه بالا | شکم منقبض | بدون کشش گردن',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['obliques'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'spinal_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'lying_supine', 'grip_type' => 'none', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'core_spine',
            'muscle_targets' => ['abs' => 90, 'obliques' => 25, 'hip_flexors' => 20],
            'met' => 3, 'movement_distance_cm' => 25, 'calories_per_1000kg' => 25, 'exercise_difficulty_score' => 2, 'typical_rpe' => 6,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '', 'rep_range_hypertrophy' => '15-25', 'rep_range_endurance' => '20-40', 'rest_seconds' => 45, 'tempo' => '2-1-2',
            'short_description' => 'کرانچ حرکت فلکشن برای شکم راست با دامنه کنترل‌شده و فشار کمتر کمر.',
            'target_area' => 'شکم',
        ],
        'rank_extra' => 'تمرین پایه شکم برای همه سطوح.',
    ]);

    $add([
        'slug' => 'لانج',
        'title' => 'لانج',
        'aliases' => ['Lunge', 'Walking Lunge', 'Forward Lunge', 'حرکت قدم بلند'],
        'intro' => '<strong>لانج</strong> حرکت تک‌پا برای چهارسر، باسن و تعادل؛ با وزن بدن یا دمبل قابل پیشرفت.',
        'caption' => 'لانج — زانو جلو روی مچ پا',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، همسترینگ', 'difficulty' => 'مبتدی', 'equipment' => 'بدون تجهیزات (یا دمبل)', 'type' => 'قدرتی / حجمی'],
        'tips' => ['زانو جلو روی مچ، نه جلوتر.', 'تنه عمودی.', 'قدم کافی برای کشش.'],
        'setup' => ['ایستاده، Core سفت.', 'قدم بلند جلو.', 'پاشنه عقب بالا.'],
        'execution' => ['پایین تا زانو عقب نزدیک زمین.', 'فشار پا جلو برای بالا.', 'تناوب پاها.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: quadriceps', 'کمکی: glutes، hamstrings', 'تثبیت: Core'],
        'mistakes' => [['زانو جلو زیاد', 'قدم بلندتر'], ['تنه جلو', 'قامت عمودی'], ['قدم کوتاه', 'کشش کافی']],
        'program' => [['حجم', '۳', '۱۰–۱۲ هر پا', '۶۰ث'], ['استقامت', '۳', '۱۵–۲۰', '۴۵ث'], ['قدرت', '۳–۴', '۶–۸', '۹۰ث']],
        'combos' => [['label' => 'روز پا: ', 'link_text' => 'اسکات هالتر', 'slug' => 'اسکات-هالتر']],
        'faqs' => [['q' => 'جلو یا عقب؟', 'a' => 'جلو رایج‌تر؛ عقب فشار کمتر روی زانو جلو.']],
        'summary' => 'لانج برای پا، باسن و تعادل ضروری است.',
        'summary_keys' => 'زانو روی مچ | تنه عمودی | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'hamstrings'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'lunge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'unilateral',
            'posture' => 'standing', 'grip_type' => 'none', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'knee_hip',
            'muscle_targets' => ['quads' => 90, 'glutes' => 75, 'hamstrings' => 45, 'abs' => 25],
            'met' => 4.5, 'movement_distance_cm' => 50, 'calories_per_1000kg' => 42, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '10-12', 'rep_range_endurance' => '12-20', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'لانج حرکت تک‌پا برای چهارسر، باسن، همسترینگ و تعادل.',
            'target_area' => 'پا و باسن',
        ],
        'rank_extra' => 'تمرین تک‌پا برای پا و باسن.',
    ]);

    $add([
        'slug' => 'پشت-بازو-پشت-سر',
        'title' => 'پشت بازو پشت سر',
        'aliases' => ['Skull Crusher', 'Lying Triceps Extension', 'French Press', 'EZ Bar Skull Crusher', 'پشت بازو خوابیده'],
        'intro' => '<strong>پشت بازو پشت سر</strong> (اسکال کرشر) حرکت ایزوله برای سه‌سر بازو در حالت خوابیده.',
        'caption' => 'پشت بازو پشت سر — آرنج ثابت',
        'quick' => ['main' => 'پشت بازو', 'secondary' => 'ساعد', 'difficulty' => 'متوسط', 'equipment' => 'هالتر یا EZ، نیمکت', 'type' => 'حجمی'],
        'tips' => ['آرنج ثابت رو به سقف.', 'پایین تا پیشانی/کنار سر.', 'بازگشت با انقباض.'],
        'setup' => ['درازکش، هالتر بالای سینه.', 'آرنج جمع رو به بالا.', 'گرفتن بار.'],
        'execution' => ['خم آرنج پایین کنترل.', 'تا نزدیک پیشانی.', 'بازگشت تا آرنج تقریباً صاف.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: triceps (long head)', 'کمکی: forearms', 'تثبیت: Core'],
        'mistakes' => [['آرنج باز', 'ثابت رو به بالا'], ['کوبیدن پیشانی', 'تمپو آهسته'], ['کمر قوس', 'پا روی زمین']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث'], ['قدرت', '۳', '۶–۸', '۹۰ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت بازو سیمکش', 'slug' => 'پشت-بازو-سیمکش']],
        'faqs' => [['q' => 'EZ یا هالتر مستقیم؟', 'a' => 'EZ مچ راحت‌تر؛ هر دو مؤثرند.']],
        'summary' => 'اسکال کرشر کلاسیک برای سه‌سر.',
        'summary_keys' => 'آرنج ثابت | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell', 'bench'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'elbow_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'lying_supine', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'elbow',
            'muscle_targets' => ['triceps' => 95, 'forearms' => 30],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-8', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 75, 'tempo' => '2-1-2',
            'short_description' => 'پشت بازو پشت سر (اسکال کرشر) حرکت ایزوله برای سه‌سر بازو.',
            'target_area' => 'پشت بازو',
        ],
        'rank_extra' => 'حجم سه‌سر بازو.',
    ]);

    $add([
        'slug' => 'کول-هالتر',
        'title' => 'کول هالتر',
        'aliases' => ['Barbell Shrug', 'Shrug', 'Shrugs', 'شراگ هالتر', 'شراگ'],
        'intro' => '<strong>کول هالتر</strong> (شراگ) برای ذوزنقه بالایی و گردن/کتف قوی؛ حرکت کوتاه ولی مؤثر.',
        'caption' => 'کول هالتر — بالا بردن شانه مستقیم',
        'quick' => ['main' => 'ذوزنقه بالایی', 'secondary' => 'گردن (تثبیت)', 'difficulty' => 'مبتدی', 'equipment' => 'هالتر', 'type' => 'حجمی'],
        'tips' => ['فقط شانه بالا — نه چرخش.', 'مکث ۱ ثانیه بالا.', 'آرنج صاف.'],
        'setup' => ['هالتر جلو بدن یا پشت.', 'دست بازتر از لگن.', 'ایستاده صاف.'],
        'execution' => ['بالا بردن شانه به گوش.', 'مکث.', 'پایین آهسته.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: upper trapezius', 'کمکی: levator scapulae', 'تثبیت: Core'],
        'mistakes' => [['چرخش شانه', 'حرکت خطی بالا'], ['تاب سر', 'گردن خنثی'], ['وزنه بیش از حد', 'دامنه کامل']],
        'program' => [['حجم', '۳–۴', '۱۲–۱۵', '۴۵–۶۰ث'], ['قدرت', '۳', '۸–۱۰', '۹۰ث'], ['استقامت', '۳', '۱۵–۲۰', '۳۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'زیربغل هالتر', 'slug' => 'زیربغل-هالتر-خمیده']],
        'faqs' => [['q' => 'هالتر جلو یا پشت؟', 'a' => 'جلو رایج‌تر؛ پشت گرفتن متفاوت است.']],
        'summary' => 'شراگ برای ذوزنقه و ظاهر پشت بالاتنه.',
        'summary_keys' => 'حرکت خطی | مکث بالا | بدون چرخش',
        'meta' => [
            'main_muscle' => 'traps_upper', 'secondary_muscle_keys' => ['traps_middle'],
            'difficulty' => 'beginner', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'scapular_elevation', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'frontal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'shoulder',
            'muscle_targets' => ['traps_upper' => 95, 'traps_middle' => 70, 'traps_lower' => 30],
            'met' => 3.5, 'movement_distance_cm' => 15, 'calories_per_1000kg' => 30, 'exercise_difficulty_score' => 2, 'typical_rpe' => 6.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '12-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'کول هالتر (شراگ) برای ذوزنقه بالایی و تقویت کتف.',
            'target_area' => 'ذوزنقه',
        ],
        'rank_extra' => 'ذوزنقه بالایی و کتف.',
    ]);

    $add([
        'slug' => 'پشت-بازو-دمبل',
        'title' => 'پشت بازو دمبل',
        'aliases' => ['Dumbbell Triceps Extension', 'Overhead Triceps Extension', 'Single Arm Triceps Extension', 'اکستنشن پشت بازو'],
        'intro' => '<strong>پشت بازو دمبل</strong> (بالای سر) برای کشش long head سه‌سر؛ نشسته یا ایستاده.',
        'caption' => 'پشت بازو دمبل — آرنج رو به بالا',
        'quick' => ['main' => 'پشت بازو', 'secondary' => 'ساعد', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل', 'type' => 'حجمی'],
        'tips' => ['آرنج ثابت کنار سر.', 'پایین پشت سر.', 'کمر خنثی.'],
        'setup' => ['دمبل دو دست یا تک.', 'آرنج رو به بالا.', 'نشسته یا ایستاده.'],
        'execution' => ['خم آرنج پایین.', 'کشش سه‌سر.', 'بازگشت تا صاف.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: triceps long head', 'کمکی: forearms', 'تثبیت: Core'],
        'mistakes' => [['آرنج باز', 'ثابت'], ['قوس کمر', 'Core سفت'], ['دامنه کوتاه', 'پایین کامل']],
        'program' => [['حجم', '۳–۴', '۱۰–۱۵', '۴۵–۶۰ث'], ['استقامت', '۳', '۱۵–۲۰', '۳۰ث'], ['تک دست', '۳', '۱۰–۱۲', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت بازو سیمکش', 'slug' => 'پشت-بازو-سیمکش']],
        'faqs' => [['q' => 'بالای سر یا لickback؟', 'a' => 'بالای سر long head بیشتر؛ kickback برای peak contraction.']],
        'summary' => 'اکستنشن دمبل برای arms کامل.',
        'summary_keys' => 'آرنج ثابت | کشش long head | تمپو',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'elbow_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'elbow',
            'muscle_targets' => ['triceps' => 95, 'forearms' => 25],
            'met' => 3.5, 'movement_distance_cm' => 45, 'calories_per_1000kg' => 35, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '10-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پشت بازو دمبل (بالای سر) برای هایپرتروفی سه‌سر بازو.',
            'target_area' => 'پشت بازو',
        ],
        'rank_extra' => 'long head سه‌سر بازو.',
    ]);

    $add([
        'slug' => 'پای-آویزان',
        'title' => 'پای آویزان',
        'aliases' => ['Hanging Leg Raise', 'Hanging Knee Raise', 'Leg Raise', 'بالا آوردن پا آویزان'],
        'intro' => '<strong>پای آویزان</strong> حرکت پیشرفته Core با آویزان از بارفیکس؛ شکم و فلکسور لگن را هدف می‌گیرد.',
        'caption' => 'پای آویزان — بدون تاب',
        'quick' => ['main' => 'شکم', 'secondary' => 'فلکسور لگن', 'difficulty' => 'متوسط', 'equipment' => 'میله بارفیکس', 'type' => 'قدرتی Core'],
        'tips' => ['بدون تاب.', 'لگن کمی جلو برای شکم.', 'پایین کنترل‌شده.'],
        'setup' => ['آویزان فعال از بارفیکس.', 'کتف پایین.', 'پا کنار هم.'],
        'execution' => ['بالا بردن پا تا موازی زمین یا بالاتر.', 'مکث کوتاه.', 'پایین آهسته.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: rectus abdominis', 'کمکی: hip flexors', 'تثبیت: forearms، lats'],
        'mistakes' => [['تاب', 'کنترل تمپو'], ['فقط زانو بدون شکم', 'لگن posterior tilt'], ['گردن فشار', 'شانه ریلکس']],
        'program' => [['حجم', '۳–۴', '۸–۱۵', '۶۰ث'], ['استقامت', '۳', '۱۲–۲۰', '۴۵ث'], ['زانو (آسان‌تر)', '۳', '۱۵–۲۰', '۳۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'بارفیکس', 'slug' => 'بارفیکس']],
        'faqs' => [['q' => 'پا صاف یا زانو؟', 'a' => 'زانو برای مبتدی؛ پا صاف سخت‌تر و شکم بیشتر.']],
        'summary' => 'پای آویزان برای شکم قوی و Core پیشرفته.',
        'summary_keys' => 'بدون تاب | کنترل پایین | کتف فعال',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['hip_flexors', 'forearms'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['pullup_bar'],
            'exercise_type' => 'strength', 'movement_pattern' => 'spinal_flexion', 'body_engagement' => 'core_dominant',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'hanging', 'grip_type' => 'pronated', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'core_spine',
            'muscle_targets' => ['abs' => 90, 'hip_flexors' => 55, 'forearms' => 35, 'back_lat' => 25],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 35, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '10-15', 'rep_range_endurance' => '12-20', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پای آویزان حرکت Core برای شکم و فلکسور لگن با آویزان از بارفیکس.',
            'target_area' => 'شکم',
        ],
        'rank_extra' => 'Core پیشرفته و شکم.',
    ]);

    $add([
        'slug' => 'کتله-بل-سوینگ',
        'title' => 'کتله بل سوینگ',
        'aliases' => ['Kettlebell Swing', 'KB Swing', 'Russian Swing', 'سوینگ کتلبل'],
        'intro' => '<strong>کتله بل سوینگ</strong> حرکت هیپ‌هینج انفجاری برای باسن، همسترینگ، Core و استقامت.',
        'caption' => 'کتله بل سوینگ — قدرت از باسن',
        'quick' => ['main' => 'باسن', 'secondary' => 'همسترینگ، Core، کمر', 'difficulty' => 'متوسط', 'equipment' => 'کتل‌بل', 'type' => 'پاور / هوازی'],
        'tips' => ['قدرت از باسن نه دست.', 'کتل تا ارتفاع سینه (Russian).', 'کمر خنثی.'],
        'setup' => ['پا عرض شانه.', 'کتل جلو، خم با باسن عقب.', 'دو دست روی دسته.'],
        'execution' => ['باسن عقب، کتل بین پا.', 'انفجار باسن جلو — کتل تا سینه.', 'کنترل پایین.', 'ریتم ثابت.'],
        'breathing' => 'بازدم در بالا — دم در backswing.',
        'muscles' => ['اصلی: glutes، hamstrings', 'کمکی: erector، shoulders', 'تثبیت: Core'],
        'mistakes' => [['کشش با دست', 'هیپ هینج'], ['کمر گرد', 'قفسه بالا'], ['کتل خیلی بالا', 'تا سینه کافی']],
        'program' => [['پاور', '۵', '۱۵–۲۰', '۶۰ث'], ['HIIT', '۸', '۲۰ ثانیه', '۴۰ث'], ['استقامت', '۳', '۲۵–۳۰', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'ددلیفت رومانیایی', 'slug' => 'ددلیفت-رومانیایی']],
        'faqs' => [['q' => 'American vs Russian؟', 'a' => 'Russian تا سینه امن‌تر؛ American overhead سخت‌تر.']],
        'summary' => 'سوینگ برای باسن، چربی‌سوزی و پاور.',
        'summary_keys' => 'هیپ هینج | بازدم بالا | کمر خنثی',
        'meta' => [
            'main_muscle' => 'glutes', 'secondary_muscle_keys' => ['hamstrings', 'lower_back', 'abs'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['kettlebell'],
            'exercise_type' => 'power', 'movement_pattern' => 'hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'dynamic', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'hip',
            'muscle_targets' => ['glutes' => 90, 'hamstrings' => 80, 'lower_back' => 45, 'abs' => 40, 'shoulder_anterior' => 25],
            'met' => 9, 'movement_distance_cm' => 55, 'calories_per_1000kg' => 55, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'power', 'recommended_sets' => '3-5',
            'rep_range_strength' => '5-10', 'rep_range_hypertrophy' => '10-15', 'rep_range_endurance' => '15-25', 'rest_seconds' => 60, 'tempo' => 'dynamic',
            'short_description' => 'کتله بل سوینگ حرکت هیپ‌هینج انفجاری برای باسن، همسترینگ و Core.',
            'target_area' => 'باسن و پشت پا',
        ],
        'rank_extra' => 'پاور باسن و چربی‌سوزی.',
    ]);

    $add([
        'slug' => 'رویینگ-سیمکش',
        'title' => 'رویینگ سیمکش',
        'aliases' => ['Seated Cable Row', 'Cable Row', 'Low Row', 'قایقی سیمکش', 'Row'],
        'intro' => '<strong>رویینگ سیمکش</strong> کشش افقی نشسته برای ضخامت پشت، رomboid و لats.',
        'caption' => 'رویینگ سیمکش — کتف جمع در عقب',
        'quick' => ['main' => 'پشت (میانی)', 'secondary' => 'زیربغل، جلوبازو', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'قدرتی / حجمی'],
        'tips' => ['کتف جمع در عقب.', 'آرنج کنار بدن.', 'بدون تاب.'],
        'setup' => ['نشسته، پا روی پدال.', 'کمر خنثی.', 'گرفتن V یا دست صاف.'],
        'execution' => ['کشش به شکم/پایین سینه.', 'مکث عقب.', 'بازگشت آهسته.'],
        'breathing' => 'بازدم کشش — دم باز.',
        'muscles' => ['اصلی: mid traps، rhomboids، lats', 'کمکی: biceps', 'تثبیت: Core'],
        'mistakes' => [['کشش با بدن', 'ثابت تنه'], ['گردن جلو', 'خنثی'], ['نیمه دامنه', 'کشش کامل']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۶–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'بارفیکس', 'slug' => 'بارفیکس']],
        'faqs' => [['q' => 'V یا wide؟', 'a' => 'V ضخامت میانی؛ wide لats بیشتر.']],
        'summary' => 'رویینگ برای پشت ضخیم و posture بهتر.',
        'summary_keys' => 'کتف جمع | تنه ثابت | مکث عقب',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['rhomboids', 'traps_middle', 'biceps'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'transverse', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'shoulder_elbow',
            'muscle_targets' => ['back_lat' => 85, 'rhomboids' => 75, 'traps_middle' => 70, 'biceps' => 40],
            'met' => 5, 'movement_distance_cm' => 50, 'calories_per_1000kg' => 45, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-5',
            'rep_range_strength' => '4-8', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'رویینگ سیمکش کشش افقی برای ضخامت پشت، رomboid و زیربغل.',
            'target_area' => 'پشت',
        ],
        'rank_extra' => 'ضخامت پشت و وضعیت بدن.',
    ]);

    $add([
        'slug' => 'شنا-الماسی',
        'title' => 'شنا الماسی',
        'aliases' => ['Diamond Push-Up', 'Triangle Push-Up', 'Close Grip Push-Up', 'شنا دست جمع'],
        'intro' => '<strong>شنا الماسی</strong> شنا با دست جمع برای تأکید بر پشت بازو و درونی سینه.',
        'caption' => 'شنا الماسی — دست‌ها الماس',
        'quick' => ['main' => 'پشت بازو', 'secondary' => 'سینه داخلی، Core', 'difficulty' => 'متوسط', 'equipment' => 'بدون تجهیزات', 'type' => 'قدرتی'],
        'tips' => ['انگشتان الماس زیر سینه.', 'آرنج نزدیک بدن.', 'Core سفت.'],
        'setup' => ['شنا، دست الماس.', 'خط بدن صاف.', 'پا مناسب سطح.'],
        'execution' => ['پایین تا سینه نزدیک دست.', 'بازدم بالا.', 'کنترل تمپو.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: triceps', 'کمکی: chest inner، anterior deltoid', 'تثبیت: Core'],
        'mistakes' => [['کمر افتاده', 'Core'], ['آرنج باز', 'نزدیک بدن'], ['دست جلو صورت', 'زیر سینه']],
        'program' => [['حجم', '۳–۴', '۸–۱۵', '۴۵–۶۰ث'], ['استقامت', '۳', '۱۵–۲۵', '۳۰ث'], ['قدرت', '۴', '۵–۱۰', '۶۰ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت بازو سیمکش', 'slug' => 'پشت-بازو-سیمکش']],
        'faqs' => [['q' => 'سخت است؟', 'a' => 'روی زانو یا دست روی سکو شروع کنید.']],
        'summary' => 'شنا الماسی برای triceps بدون وسیله.',
        'summary_keys' => 'دست الماس | آرنج نزدیک | Core سفت',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => ['chest', 'shoulder_anterior', 'abs'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'lying_prone', 'grip_type' => 'narrow', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'elbow',
            'muscle_targets' => ['triceps' => 90, 'chest_middle' => 55, 'shoulder_anterior' => 35, 'abs' => 30],
            'met' => 4.5, 'movement_distance_cm' => 30, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '5-8', 'rep_range_hypertrophy' => '8-15', 'rep_range_endurance' => '15-25', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'شنا الماسی شنا دست جمع برای پشت بازو و سینه داخلی با وزن بدن.',
            'target_area' => 'پشت بازو',
        ],
        'rank_extra' => 'پشت بازو با وزن بدن.',
    ]);

    return $defs;
}
}

