// GymAI Popular — BATCH 11 (20 حرکت — حرکات 181 تا 200)
// Code Snippets: Run everywhere | بدون تگ php

if (!function_exists('gymai_pop20_batch11_definitions')) {
function gymai_pop20_batch11_definitions() {
    $base_img = 'https://gymaipro.ir/wp-content/uploads/2026/07/';
    $defs = [];
    $add = function (array $row) use (&$defs, $base_img) {
        if (empty($row['image'])) {
            $key = !empty($row['image_key']) ? $row['image_key'] : ('exercise-batch11-' . str_pad((string) (count($defs) + 1), 2, '0', STR_PAD_LEFT));
            $row['image'] = $base_img . $key . '.jpg';
        }
        $defs[] = $row;
    };

    $add([
        'image_key' => 'exercise-batch11-01',
        'slug' => 'پلانک-شانه-لمس',
        'title' => 'پلانک شانه لمس',
        'aliases' => ['Shoulder Tap Plank', 'ShoulderTapPlank', 'پلانک شانه لمس'],
        'intro' => '<strong>پلانک شانه لمس</strong> (Shoulder Tap Plank) پلانک با برداشتن دست و لمس شانه مخالف؛ Core پایدار. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'پلانک شانه لمس — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'سرشانه', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پلانک', 'slug' => 'پلانک-plank']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'پلانک شانه لمس برای Core و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['shoulder_anterior'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'anti_rotation', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'prone', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 85, 'obliques' => 65, 'shoulder_anterior' => 35],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پلانک لمس شانه برای ضدچرخش.',
            'target_area' => 'Core',
        ],
        'rank_extra' => 'ضدچرخش.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-02',
        'slug' => 'پلانک-خرس',
        'title' => 'پلانک خرس',
        'aliases' => ['Bear Plank', 'BearPlank', 'پلانک خرس'],
        'intro' => '<strong>پلانک خرس</strong> (Bear Plank) پلانک با زانو از زمین؛ چالش Core بدون فشار گردن. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'پلانک خرس — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'سرشانه', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'ددباگ', 'slug' => 'ددباگ']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پلانک خرس برای Core و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['shoulder_anterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'anti_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'prone', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 80, 'shoulder_anterior' => 40],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'Bear Plank برای Core.',
            'target_area' => 'Core',
        ],
        'rank_extra' => 'Core فعال.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-03',
        'slug' => 'پای-دراز-خوابیده',
        'title' => 'پای دراز خوابیده',
        'aliases' => ['Lying Leg Raise', 'LyingLegRaise', 'پای دراز خوابیده'],
        'intro' => '<strong>پای دراز خوابیده</strong> (Lying Leg Raise) بالا آوردن پا درازکش؛ تمرکز شکم پایین. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'پای دراز خوابیده — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'hip_flexors', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: hip_flexors', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پای آویزان', 'slug' => 'پای-آویزان']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پای دراز خوابیده برای شکم و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['hip_flexors'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'spinal_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 88, 'abs_lower' => 85],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پا دراز خوابیده برای شکم پایین.',
            'target_area' => 'شکم',
        ],
        'rank_extra' => 'شکم پایین.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-04',
        'slug' => 'وی-آپ',
        'title' => 'وی آپ',
        'aliases' => ['V-Up', 'V-Up', 'وی آپ'],
        'intro' => '<strong>وی آپ</strong> (V-Up) لمس دست به پا در V؛ حرکت ترکیبی شکم. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'وی آپ — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'hip_flexors', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: hip_flexors', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'دراز و نشست', 'slug' => 'دراز-و-نشست']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'وی آپ برای شکم و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['hip_flexors'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'spinal_flexion', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 90, 'abs_lower' => 80],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'V-Up برای شکم کامل.',
            'target_area' => 'شکم',
        ],
        'rank_extra' => 'شکم کامل.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-05',
        'slug' => 'هالو-بادی',
        'title' => 'هالو بادی',
        'aliases' => ['Hollow Body Hold', 'HollowBodyHold', 'هالو بادی'],
        'intro' => '<strong>هالو بادی</strong> (Hollow Body Hold) نگه‌داشتن موقعیت هالو؛ پایه حرکات ژیمناستیک. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'هالو بادی — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'hip_flexors', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: hip_flexors', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پلانک', 'slug' => 'پلانک-plank']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'هالو بادی برای Core و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['hip_flexors'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'anti_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 92, 'abs_lower' => 85],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'Hollow Body برای Core ژیمناستیک.',
            'target_area' => 'Core',
        ],
        'rank_extra' => 'Core ژیمناستیک.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-06',
        'slug' => 'چرخش-روسی-سیمکش',
        'title' => 'چرخش روسی سیمکش',
        'aliases' => ['Cable Russian Twist', 'CableRussianTwist', 'چرخش روسی سیمکش'],
        'intro' => '<strong>چرخش روسی سیمکش</strong> (Cable Russian Twist) چرخش تنه با مقاومت کابل؛ پهلو و Core. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'چرخش روسی سیمکش — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'پهلو', 'difficulty' => 'متوسط', 'equipment' => 'سیم‌کش', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: پهلو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'چرخش روسی', 'slug' => 'چرخش-روسی']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'چرخش روسی سیمکش برای شکم و پهلو و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['obliques'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'rotation', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['obliques' => 85, 'abs' => 70],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'چرخش روسی با سیمکش.',
            'target_area' => 'شکم و پهلو',
        ],
        'rank_extra' => 'پهلو با مقاومت.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-07',
        'slug' => 'خم-جانبی-دمبل',
        'title' => 'خم جانبی دمبل',
        'aliases' => ['Dumbbell Side Bend', 'DumbbellSideBend', 'خم جانبی دمبل'],
        'intro' => '<strong>خم جانبی دمبل</strong> (Dumbbell Side Bend) خم به طرف با دمبل؛ ساده برای پهلو. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل اجرا می‌شود.',
        'caption' => 'خم جانبی دمبل — پهلو، اجرای کنترل‌شده',
        'quick' => ['main' => 'پهلو', 'secondary' => 'Core', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی پهلو در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: پهلو', 'کمکی: Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پلانک جانبی', 'slug' => 'پلانک-جانبی']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'خم جانبی دمبل برای پهلو و پهلو در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'پهلو | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'obliques', 'secondary_muscle_keys' => ['abs'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'lateral_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['obliques' => 88, 'abs' => 45],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'خم جانبی برای oblique.',
            'target_area' => 'پهلو',
        ],
        'rank_extra' => 'پهلو.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-08',
        'slug' => 'هیز-چopper-سیمکش',
        'title' => 'هیز چopper سیمکش',
        'aliases' => ['Cable Woodchopper', 'CableWoodchopper', 'هیز چopper سیمکش'],
        'intro' => '<strong>هیز چopper سیمکش</strong> (Cable Woodchopper) چرخش قطعه‌چوب با سیمکش؛ Core عملکردی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'هیز چopper سیمکش — Core، اجرای کنترل‌شده',
        'quick' => ['main' => 'Core', 'secondary' => 'Core', 'difficulty' => 'متوسط', 'equipment' => 'سیم‌کش', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی Core در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: Core', 'کمکی: Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پالوف پرس', 'slug' => 'پالوف-پرس']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'هیز چopper سیمکش برای Core و Core در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'Core | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'obliques', 'secondary_muscle_keys' => ['abs'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'rotation', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['obliques' => 90, 'abs' => 65],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'Woodchopper برای چرخش قدرتمند.',
            'target_area' => 'Core',
        ],
        'rank_extra' => 'چرخش قدرتی.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-09',
        'slug' => 'پرش-پرنده',
        'title' => 'پرش پرنده',
        'aliases' => ['Jumping Jack', 'JumpingJack', 'پرش پرنده'],
        'intro' => '<strong>پرش پرنده</strong> (Jumping Jack) حرکت کلاسیک گرم‌کردن؛ در مدار و خانه. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'پرش پرنده — تمام بدن، اجرای کنترل‌شده',
        'quick' => ['main' => 'تمام بدن', 'secondary' => 'calves، سرشانه', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی تمام بدن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: تمام بدن', 'کمکی: calves، سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'بورپی', 'slug' => 'بورپی']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پرش پرنده برای کاردیو و تمام بدن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'تمام بدن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'full_body', 'secondary_muscle_keys' => ['calves', 'shoulder_anterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'conditioning', 'movement_pattern' => 'compound', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 45, 'shoulder_anterior' => 40, 'calves' => 35],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پرش پرنده برای گرم‌کردن و کاردیو.',
            'target_area' => 'کاردیو',
        ],
        'rank_extra' => 'گرم‌کردن.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-10',
        'slug' => 'طناب-نبرد',
        'title' => 'طناب نبرد',
        'aliases' => ['Battle Ropes', 'BattleRopes', 'طناب نبرد'],
        'intro' => '<strong>طناب نبرد</strong> (Battle Ropes) موج زدن طناب سنگین؛ کاردیو و Core و شانه. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'طناب نبرد — تمام بدن، اجرای کنترل‌شده',
        'quick' => ['main' => 'تمام بدن', 'secondary' => 'سرشانه، Core', 'difficulty' => 'متوسط', 'equipment' => 'سیم‌کش', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی تمام بدن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: تمام بدن', 'کمکی: سرشانه، Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کتله بل سوینگ', 'slug' => 'کتله-بل-سوینگ']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'طناب نبرد برای کاردیو و تمام بدن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'تمام بدن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'full_body', 'secondary_muscle_keys' => ['shoulder_anterior', 'abs'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['cable'],
            'exercise_type' => 'conditioning', 'movement_pattern' => 'compound', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_anterior' => 60, 'abs' => 55, 'forearms' => 50],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'طناب نبرد برای HIIT.',
            'target_area' => 'کاردیو',
        ],
        'rank_extra' => 'HIIT.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-11',
        'slug' => 'پرش-جعبه',
        'title' => 'پرش جعبه',
        'aliases' => ['Box Jump', 'BoxJump', 'پرش جعبه'],
        'intro' => '<strong>پرش جعبه</strong> (Box Jump) پریدن روی باکس؛ قدرت انفجاری پا. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با نیمکت اجرا می‌شود.',
        'caption' => 'پرش جعبه — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، calves', 'difficulty' => 'متوسط', 'equipment' => 'نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن، calves', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'اسکوات پرش', 'slug' => 'اسکوات-پرش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'پرش جعبه برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'calves'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'squat', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 75, 'glutes' => 65, 'calves' => 50],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پرش جعبه برای پلیومتریک.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'پلیومتریک.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-12',
        'slug' => 'کتل-کلین',
        'title' => 'کتل کلین',
        'aliases' => ['Kettlebell Clean', 'KettlebellClean', 'کتل کلین'],
        'intro' => '<strong>کتل کلین</strong> (Kettlebell Clean) بالا آوردن کتل‌بل به شانه؛ حرکت پایه کراس‌فیت. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با کتل‌بل اجرا می‌شود.',
        'caption' => 'کتل کلین — تمام بدن، اجرای کنترل‌شده',
        'quick' => ['main' => 'تمام بدن', 'secondary' => 'سرشانه، باسن', 'difficulty' => 'متوسط', 'equipment' => 'کتل‌بل', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی تمام بدن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم کتل‌بل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: تمام بدن', 'کمکی: سرشانه، باسن', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کتله بل سوینگ', 'slug' => 'کتله-بل-سوینگ']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'کتل کلین برای تمام بدن و تمام بدن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'تمام بدن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'full_body', 'secondary_muscle_keys' => ['shoulder_anterior', 'glutes'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['kettlebell'],
            'exercise_type' => 'conditioning', 'movement_pattern' => 'hip_hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['glutes' => 65, 'shoulder_anterior' => 55, 'quads' => 50, 'traps' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'کتل کلین برای قدرت کل بدن.',
            'target_area' => 'تمام بدن',
        ],
        'rank_extra' => 'قدرت انفجاری.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-13',
        'slug' => 'کتل-قاپ',
        'title' => 'کتل قاپ',
        'aliases' => ['Kettlebell Snatch', 'KettlebellSnatch', 'کتل قاپ'],
        'intro' => '<strong>کتل قاپ</strong> (Kettlebell Snatch) بالا بردن کتل‌بل بالای سر یک حرکت؛ قدرت و کاردیو. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با کتل‌بل اجرا می‌شود.',
        'caption' => 'کتل قاپ — تمام بدن، اجرای کنترل‌شده',
        'quick' => ['main' => 'تمام بدن', 'secondary' => 'سرشانه، باسن', 'difficulty' => 'پیشرفته', 'equipment' => 'کتل‌بل', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی تمام بدن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم کتل‌بل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: تمام بدن', 'کمکی: سرشانه، باسن', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کتل کلین', 'slug' => 'کتل-کلین']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'کتل قاپ برای تمام بدن و تمام بدن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'تمام بدن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'full_body', 'secondary_muscle_keys' => ['shoulder_anterior', 'glutes'],
            'difficulty' => 'advanced', 'equipment_keys' => ['kettlebell'],
            'exercise_type' => 'conditioning', 'movement_pattern' => 'hip_hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_anterior' => 70, 'glutes' => 60, 'quads' => 55],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'کتل قاپ حرکت پیشرفته.',
            'target_area' => 'تمام بدن',
        ],
        'rank_extra' => 'پیشرفته.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-14',
        'slug' => 'کتل-سوینگ-آمریکایی',
        'title' => 'کتل سوینگ آمریکایی',
        'aliases' => ['American Kettlebell Swing', 'AmericanKettlebellSwing', 'کتل سوینگ آمریکایی'],
        'intro' => '<strong>کتل سوینگ آمریکایی</strong> (American Kettlebell Swing) سوینگ کتل‌بل بالای سر؛ باسن و کاردیo. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با کتل‌بل اجرا می‌شود.',
        'caption' => 'کتل سوینگ آمریکایی — باسن، اجرای کنترل‌شده',
        'quick' => ['main' => 'باسن', 'secondary' => 'همسترینگ، سرشانه', 'difficulty' => 'متوسط', 'equipment' => 'کتل‌بل', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی باسن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم کتل‌بل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: باسن', 'کمکی: همسترینگ، سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کتله بل سوینگ', 'slug' => 'کتله-بل-سوینگ']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'کتل سوینگ آمریکایی برای باسن و باسن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'باسن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'glutes', 'secondary_muscle_keys' => ['hamstrings', 'shoulder_anterior'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['kettlebell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'hip_hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['glutes' => 85, 'hamstrings' => 60, 'shoulder_anterior' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'سوینگ آمریکایی تا بالای سر.',
            'target_area' => 'باسن',
        ],
        'rank_extra' => 'باسن + کاردیo.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-15',
        'slug' => 'پوش-پرس',
        'title' => 'پوش پرس',
        'aliases' => ['Push Press', 'PushPress', 'پوش پرس'],
        'intro' => '<strong>پوش پرس</strong> (Push Press) OHP با پوش پا؛ برای قدرت و وزنه بیشتر. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'پوش پرس — سرشانه قدامی، اجرای کنترل‌شده',
        'quick' => ['main' => 'سرشانه قدامی', 'secondary' => 'پشت بازو، quads', 'difficulty' => 'متوسط', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سرشانه قدامی در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سرشانه قدامی', 'کمکی: پشت بازو، quads', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پرس سرشانه با هالتر', 'slug' => 'پرس-سرشانه-با-هالتر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'پوش پرس برای سرشانه و سرشانه قدامی در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سرشانه قدامی | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_anterior', 'secondary_muscle_keys' => ['triceps', 'quads'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_anterior' => 85, 'triceps' => 55, 'quads' => 40],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'Push Press با کمک پا.',
            'target_area' => 'سرشانه',
        ],
        'rank_extra' => 'قدرت OHP.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-16',
        'slug' => 'تراستر',
        'title' => 'تراستر',
        'aliases' => ['Thruster', 'Thruster', 'تراستر'],
        'intro' => '<strong>تراستر</strong> (Thruster) فرانت اسکات + پرس سر یک حرکت؛ کاردیo و قدرت. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'تراستر — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'سرشانه، باسن', 'difficulty' => 'پیشرفته', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: سرشانه، باسن', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'اسکات فرانت', 'slug' => 'اسکات-فرانت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'تراستر برای تمام بدن و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['shoulder_anterior', 'glutes'],
            'difficulty' => 'advanced', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'squat', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 75, 'shoulder_anterior' => 70, 'glutes' => 65],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'تراستر کراس‌فیت کلاسیک.',
            'target_area' => 'تمام بدن',
        ],
        'rank_extra' => 'CrossFit.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-17',
        'slug' => 'کلین-و-پرس',
        'title' => 'کلین و پرس',
        'aliases' => ['Clean and Press', 'CleanandPress', 'کلین و پرس'],
        'intro' => '<strong>کلین و پرس</strong> (Clean and Press) پاک کردن هالتر به شانه + OHP؛ حرکت اولومپیک سبک. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'کلین و پرس — تمام بدن، اجرای کنترل‌شده',
        'quick' => ['main' => 'تمام بدن', 'secondary' => 'سرشانه، باسن', 'difficulty' => 'پیشرفته', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی تمام بدن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: تمام بدن', 'کمکی: سرشانه، باسن', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پوش پرس', 'slug' => 'پوش-پرس']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'کلین و پرس برای تمام بدن و تمام بدن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'تمام بدن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'full_body', 'secondary_muscle_keys' => ['shoulder_anterior', 'glutes'],
            'difficulty' => 'advanced', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'conditioning', 'movement_pattern' => 'hip_hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_anterior' => 65, 'glutes' => 60, 'quads' => 55, 'traps' => 50],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'کلین و پرس برای قدرت کامل.',
            'target_area' => 'تمام بدن',
        ],
        'rank_extra' => 'قدرت کامل.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-18',
        'slug' => 'توپ-پزشکی-ضربه',
        'title' => 'توپ پزشکی ضربه',
        'aliases' => ['Medicine Ball Slam', 'MedicineBallSlam', 'توپ پزشکی ضربه'],
        'intro' => '<strong>توپ پزشکی ضربه</strong> (Medicine Ball Slam) بالا بردن و کوبیدن توپ به زمین؛ تخلیه استرس و Core. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'توپ پزشکی ضربه — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'سرشانه، زیربغل', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: سرشانه، زیربغل', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'طناب نبرد', 'slug' => 'طناب-نبرد']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'توپ پزشکی ضربه برای Core و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['shoulder_anterior', 'lats'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'compound', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 70, 'shoulder_anterior' => 55, 'lats' => 40],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'ضربه توپ پزشکی برای Core و کاردیo.',
            'target_area' => 'Core',
        ],
        'rank_extra' => 'کاردیo Core.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-19',
        'slug' => 'اسکیپ-طناب',
        'title' => 'اسکیپ طناب',
        'aliases' => ['Jump Rope', 'JumpRope', 'اسکیپ طناب'],
        'intro' => '<strong>اسکیپ طناب</strong> (Jump Rope) اسکیپ کلاسیک؛ گرم‌کردن و چربی‌سوزی در همه جا. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'اسکیپ طناب — ساق پا، اجرای کنترل‌شده',
        'quick' => ['main' => 'ساق پا', 'secondary' => 'سرشانه، quads', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی ساق پا در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: ساق پا', 'کمکی: سرشانه، quads', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پرش پرنده', 'slug' => 'پرش-پرنده']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'اسکیپ طناب برای کاردیo و ساق پا در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'ساق پا | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'calves', 'secondary_muscle_keys' => ['shoulder_anterior', 'quads'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'compound', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['calves' => 70, 'shoulder_anterior' => 35, 'quads' => 30],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'طناب زدن برای کاردیo و چابکی.',
            'target_area' => 'کاردیo',
        ],
        'rank_extra' => 'کاردیo.',
    ]);

    $add([
        'image_key' => 'exercise-batch11-20',
        'slug' => 'فارمر-واک-سنگین',
        'title' => 'فارمر واک سنگین',
        'aliases' => ['Heavy Farmer Walk', 'HeavyFarmerWalk', 'فارمر واک سنگین'],
        'intro' => '<strong>فارمر واک سنگین</strong> (Heavy Farmer Walk) راه رفتن با دمبل سنگین؛ grip، تله و Core. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل اجرا می‌شود.',
        'caption' => 'فارمر واک سنگین — تمام بدن، اجرای کنترل‌شده',
        'quick' => ['main' => 'تمام بدن', 'secondary' => 'ساعد، Core', 'difficulty' => 'متوسط', 'equipment' => 'دمبل', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی تمام بدن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: تمام بدن', 'کمکی: ساعد، Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'فارمر واک', 'slug' => 'فارمر-واک']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'فارمر واک سنگین برای تمام بدن و تمام بدن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'تمام بدن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'traps', 'secondary_muscle_keys' => ['forearms', 'abs'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'carry', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['traps' => 75, 'forearms' => 85, 'abs' => 50],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'فارمر واک سنگین برای grip و Core.',
            'target_area' => 'تمام بدن',
        ],
        'rank_extra' => 'Grip قوی.',
    ]);

    return $defs;
}
}
