// GymAI Popular 20 — BATCH 1 (10 حرکت اول)
// Code Snippets: Run everywhere | بدون تگ php

if (!function_exists('gymai_pop20_batch1_definitions')) {
function gymai_pop20_batch1_definitions() {
    $base_img = 'https://gymaipro.ir/wp-content/uploads/2026/06/';
    $defs = [];
    $add = function (array $row) use (&$defs, $base_img) {
        if (empty($row['image'])) {
            $key = !empty($row['image_key']) ? $row['image_key'] : ('exercise-' . (count($defs) + 1));
            $row['image'] = $base_img . $key . '.jpg';
        }
        $defs[] = $row;
    };

    $add([
        'slug' => 'پرس-سینه-با-دمبل',
        'title' => 'پرس سینه با دمبل',
        'aliases' => ['Dumbbell Bench Press', 'DB Chest Press', 'Flat Dumbbell Press', 'پرس دمبل تخت'],
        'intro' => '<strong>پرس سینه با دمبل</strong> یک حرکت فشار افقی مرکب برای رشد سینه است. دامنه حرکت بیشتر از هالتر و تمرین جداگانه هر طرف از مزایای اصلی آن است.',
        'caption' => 'پرس سینه با دمبل — کتف جمع و کنترل دامنه',
        'quick' => ['main' => 'سینه میانی و بالایی', 'secondary' => 'پشت بازو، سرشانه قدامی', 'difficulty' => 'متوسط', 'equipment' => 'دمبل، نیمکت تخت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['کتف‌ها جمع و پایین.', 'آرنج حدود ۴۵–۶۰ درجه.', 'در بالا انقباض سینه؛ آرنج قفل نشود.'],
        'setup' => ['روی نیمکت تخت، پا روی زمین.', 'دمبل کنار سینه.', 'کتف جمع، شکم سفت.'],
        'execution' => ['با دم پایین آوردن کنترل‌شده.', 'تا کنار سینه.', 'با بازدم فشار به بالا.', 'دمبل‌ها نزدیک در بالا.'],
        'breathing' => 'دم در پایین — بازدم در بالا.',
        'muscles' => ['اصلی: سینه بزرگ (میانی/بالایی)', 'کمکی: تریسپس، دلتوئید قدامی', 'تثبیت: Core و ساعد'],
        'mistakes' => [['آرنج بیش از حد باز', 'زاویه ۴۵–۶۰°'], ['تاب دادن دمبل', 'کاهش وزنه'], ['کتف شل', 'جمع کردن قبل از هر تکرار']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴–۵', '۳–۶', '۹۰–۱۵۰ث'], ['استقامت', '۲–۳', '۱۲–۲۰', '۴۵–۶۰ث']],
        'combos' => [['label' => 'سوپرسِت: ', 'link_text' => 'پرس سینه دستگاه', 'slug' => 'پرس-سینه-دستگاه']],
        'faqs' => [['q' => 'دمبل بهتر است یا هالتر؟', 'a' => 'هر دو مفیدند؛ دمبل برای دامنه و تعادل، هالتر برای بار سنگین‌تر.']],
        'summary' => 'پرس سینه با دمبل ستون تمرین سینه برای حجم و تعادل عضلانی است.',
        'summary_keys' => 'کتف جمع | دامنه کنترل‌شده | انقباض در بالا',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['triceps', 'shoulder_anterior'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'lying_supine', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'shoulder_elbow',
            'muscle_targets' => ['chest_middle' => 90, 'chest' => 80, 'chest_upper' => 50, 'triceps' => 45, 'shoulder_anterior' => 40],
            'met' => 6, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 40, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '3-6', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-20', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پرس سینه با دمبل حرکت مرکب فشار افقی برای سینه، پشت بازو و سرشانه قدامی با دامنه حرکت بیشتر از هالتر.',
            'target_area' => 'سینه میانی و بالایی',
        ],
        'rank_extra' => 'مناسب هایپرتروفی و اصلاح عدم تقارن.',
    ]);

    $add([
        'slug' => 'پرس-سینه-با-هالتر',
        'title' => 'پرس سینه با هالتر',
        'aliases' => ['Barbell Bench Press', 'Bench Press', 'Flat Bench Press', 'بنچ پرس'],
        'intro' => '<strong>پرس سینه با هالتر</strong> (بنچ پرس) یکی از اصلی‌ترین حرکات بدنسازی برای قدرت و حجم سینه است و در پاورلیفتینگ نیز جزو حرکات پایه محسوب می‌شود.',
        'caption' => 'پرس سینه با هالتر روی نیمکت تخت',
        'quick' => ['main' => 'سینه', 'secondary' => 'پشت بازو، سرشانه قدامی', 'difficulty' => 'متوسط', 'equipment' => 'هالتر، نیمکت، رک', 'type' => 'قدرتی / حجمی'],
        'tips' => ['پا محکم روی زمین.', 'میله روی خط نیپل یا کمی پایین‌تر.', 'اسپاتر برای بار سنگین.'],
        'setup' => ['درازکش روی نیمکت، چشمان زیر میله.', 'گرفتن میله عرض شانه یا کمی بازتر.', 'کتف جمع، قوس طبیعی کمر.'],
        'execution' => ['با دم میله به سینه.', 'لمس سبک یا نزدیک سینه.', 'با بازدم فشار به بالا.', 'آرنج نرم در بالا.'],
        'breathing' => 'دم پایین — بازدم بالا؛ قبل از تکرار سنگین نفس حبس کوتاه مجاز است.',
        'muscles' => ['اصلی: سینه بزرگ', 'کمکی: تریسپس، دلتوئید قدامی', 'تثبیت: پا، Core، کتف'],
        'mistakes' => [['پا روی نیمکت', 'پا روی زمین'], ['میله روی گردن', 'خط سینه/نیپل'], ['بouncing روی سینه', 'کنترل تمپو']],
        'program' => [['حجم', '۳–۵', '۶–۱۲', '۹۰ث'], ['قدرت', '۴–۶', '۱–۵', '۱۸۰–۳۰۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۶۰ث']],
        'combos' => [['label' => 'بعد از بنچ: ', 'link_text' => 'فلای دمبل', 'slug' => 'فلای-دمبل']],
        'faqs' => [['q' => 'عرض گرفتن میله؟', 'a' => 'معمولاً کمی بازتر از شانه؛ گریپ باریک‌تر پشت بازو بیشتر درگیر می‌کند.']],
        'summary' => 'بنچ پرس برای قدرت مطلق بالاتنه و حجم سینه بی‌نظیر است.',
        'summary_keys' => 'کتف پایین | خط میله صحیح | اسپات امن',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['triceps', 'shoulder_anterior'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'lying_supine', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'shoulder_elbow',
            'muscle_targets' => ['chest_middle' => 95, 'chest' => 90, 'triceps' => 50, 'shoulder_anterior' => 45, 'chest_lower' => 40],
            'met' => 6, 'movement_distance_cm' => 45, 'calories_per_1000kg' => 45, 'exercise_difficulty_score' => 5, 'typical_rpe' => 8,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'strength', 'recommended_sets' => '3-5',
            'rep_range_strength' => '3-6', 'rep_range_hypertrophy' => '6-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 120, 'tempo' => '2-1-2',
            'short_description' => 'پرس سینه با هالتر (بنچ پرس) حرکت پایه برای قدرت و حجم سینه، پشت بازو و سرشانه قدامی.',
            'target_area' => 'سینه',
        ],
        'rank_extra' => 'حرکت پایه پاورلیفتینگ و بدنسازی.',
    ]);

    $add([
        'slug' => 'پرس-سرشانه-با-هالتر',
        'title' => 'پرس سرشانه با هالتر',
        'aliases' => ['Overhead Press', 'Military Press', 'OHP', 'Barbell Shoulder Press', 'پرس نظامی'],
        'intro' => '<strong>پرس سرشانه با هالتر</strong> بهترین حرکت compound برای قدرت و حجم سرشانه و پشت بازو است؛ ایستاده یا نشسته قابل اجراست.',
        'caption' => 'پرس سرشانه با هالتر — Core سفت و میله عمودی',
        'quick' => ['main' => 'سرشانه (قدامی/میانی)', 'secondary' => 'پشت بازو، ذوزنقه', 'difficulty' => 'متوسط', 'equipment' => 'هالتر', 'type' => 'قدرتی'],
        'tips' => ['کمر و Core سفت.', 'سر میله زیر چانه، سپس بالای سر.', 'چانه عقب در مسیر میله.'],
        'setup' => ['هالتر روی کلاویکل یا جلو سرشانه.', 'گرفتن کمی بازتر از شانه.', 'پا عرض لگن، زانو نرم.'],
        'execution' => ['با بازدم فشار عمودی.', 'سر کمی عقب برای عبور میله.', 'بالای سر، میله روی خط گوش.', 'با دم پایین کنترل‌شده.'],
        'breathing' => 'بازدم در فشار — دم در پایین.',
        'muscles' => ['اصلی: دلتوئید قدامی و میانی', 'کمکی: تریسپس، تراپس بالایی', 'تثبیت: Core و باسن'],
        'mistakes' => [['قوس بیش از حد کمر', 'سفت کردن Core'], ['پرس جلو بدن', 'مسیر عمودی'], ['قفل سخت آرنج', 'آرنج نرم']],
        'program' => [['حجم', '۳–۴', '۶–۱۰', '۹۰–۱۲۰ث'], ['قدرت', '۴–۵', '۳–۵', '۱۵۰–۱۸۰ث'], ['استقامت', '۳', '۱۰–۱۵', '۶۰ث']],
        'combos' => [['label' => 'بعد از OHP: ', 'link_text' => 'نشر جانب دمبل', 'slug' => 'نشر-جانب-دمبل']],
        'faqs' => [['q' => 'ایستاده یا نشسته؟', 'a' => 'ایستاده Core بیشتر؛ نشسته تمرکز روی سرشانه با ثبات بیشتر.']],
        'summary' => 'پرس سرشانه با هالتر ستون تمرین سرشانه برای قدرت واقعی.',
        'summary_keys' => 'Core سفت | مسیر عمودی | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_anterior', 'secondary_muscle_keys' => ['shoulder_lateral', 'triceps', 'traps_upper'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'shoulder_elbow',
            'muscle_targets' => ['shoulder_anterior' => 90, 'shoulder_lateral' => 75, 'triceps' => 50, 'traps_upper' => 35, 'abs' => 25],
            'met' => 5.5, 'movement_distance_cm' => 50, 'calories_per_1000kg' => 48, 'exercise_difficulty_score' => 6, 'typical_rpe' => 8,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'strength', 'recommended_sets' => '3-5',
            'rep_range_strength' => '3-6', 'rep_range_hypertrophy' => '6-10', 'rep_range_endurance' => '10-15', 'rest_seconds' => 120, 'tempo' => '2-0-2',
            'short_description' => 'پرس سرشانه با هالتر حرکت مرکب فشار عمودی برای سرشانه، پشت بازو و Core.',
            'target_area' => 'سرشانه',
        ],
        'rank_extra' => 'قدرت واقعی سرشانه و بالاتنه.',
    ]);

    $add([
        'slug' => 'بارفیکس',
        'title' => 'بارفیکس',
        'aliases' => ['Pull-Up', 'Chin-Up', 'Wide Grip Pull-Up', 'بارفیکس دست باز', 'کشش عمودی'],
        'intro' => '<strong>بارفیکس</strong> یک حرکت کشش عمودی با وزن بدن برای ساخت پشت پهن، قدرت گرفتن و جلوبازو است.',
        'caption' => 'بارفیکس — کتف پایین و چانه بالای میله',
        'quick' => ['main' => 'زیربغل (لات)', 'secondary' => 'جلوبازو، ذوزنقه، پشت بازو', 'difficulty' => 'متوسط', 'equipment' => 'میله بارفیکس', 'type' => 'قدرتی / حجمی'],
        'tips' => ['کتف را پایین و جمع کنید.', 'شروع از آویزان فعال.', 'بدون تاب بدن.'],
        'setup' => ['گرفتن میله کمی بازتر از شانه.', 'آویزان با شانه فعال.', 'Core سفت.'],
        'execution' => ['کشش با آرنج به پایین.', 'چانه بالای میله یا سینه نزدیک.', 'بازگشت آهسته تا آویزان کامل.'],
        'breathing' => 'بازدم در بالا — دم در پایین.',
        'muscles' => ['اصلی: لاتسیموس dorsi', 'کمکی: بiceps، رomboids، ترaps', 'تثبیت: Core و ساعد'],
        'mistakes' => [['تاب خوردن', 'کنترل تمپو'], ['شانه به گوش', 'کتف پایین'], ['نیمه دامنه', 'آویزان کامل']],
        'program' => [['حجم', '۳–۴', '۶–۱۲', '۹۰ث'], ['قدرت', '۴–۵', '۳–۶', '۱۲۰–۱۸۰ث'], ['استقامت', '۳', 'تا ناتوانی', '۶۰ث']],
        'combos' => [['label' => 'بعد از بارفیکس: ', 'link_text' => 'زیربغل سیمکش', 'slug' => 'زیربغل-سیمکش-دست-باز']],
        'faqs' => [['q' => 'بارفیکس سخت است؛ چه کنم؟', 'a' => 'کش کمکی، بارفیکس منفی یا دستگاه گرavity تا قدرت کافی.']],
        'summary' => 'بارفیکس یکی از بهترین حرکات وزن بدن برای پشت است.',
        'summary_keys' => 'کتف فعال | بدون تاب | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'traps', 'shoulder_posterior'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['pullup_bar'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'hanging', 'grip_type' => 'pronated', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'shoulder_elbow',
            'muscle_targets' => ['back_lat' => 95, 'biceps' => 45, 'traps_upper' => 40, 'shoulder_posterior' => 30, 'forearms' => 35],
            'met' => 5, 'movement_distance_cm' => 55, 'calories_per_1000kg' => 50, 'exercise_difficulty_score' => 6, 'typical_rpe' => 8,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-5',
            'rep_range_strength' => '3-6', 'rep_range_hypertrophy' => '6-12', 'rep_range_endurance' => '10-20', 'rest_seconds' => 120, 'tempo' => '2-1-2',
            'short_description' => 'بارفیکس حرکت کشش عمودی با وزن بدن برای زیربغل، جلوبازو و پشت.',
            'target_area' => 'زیربغل و پشت',
        ],
        'rank_extra' => 'ساخت پشت پهن با وزن بدن.',
    ]);

    $add([
        'slug' => 'شنا-سوئدی',
        'title' => 'شنا سوئدی',
        'aliases' => ['Push-Up', 'Press-Up', 'شنا', 'شنا روی زمین'],
        'intro' => '<strong>شنا سوئدی</strong> حرکت فشار افقی با وزن بدن برای سینه، پشت بازو و Core؛ در هر جایی قابل اجراست.',
        'caption' => 'شنا سوئدی با خط بدن صاف',
        'quick' => ['main' => 'سینه', 'secondary' => 'پشت بازو، سرشانه، Core', 'difficulty' => 'مبتدی', 'equipment' => 'بدون تجهیزات', 'type' => 'قدرتی / استقامتی'],
        'tips' => ['خط بدن از سر تا پاشنه.', 'کتف جمع.', 'آرنج ۴۵ درجه نسبت به بدن.'],
        'setup' => ['دست‌ها کمی بازتر از شانه.', 'انگشتان جلو.', 'Core و باسن سفت.'],
        'execution' => ['با دم پایین تا سینه نزدیک زمین.', 'با بازدم بالا.', 'بدون افتادگی کمر.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: سینه', 'کمکی: تریسپس، دلتوئید قدامی', 'تثبیت: شکم و باسن'],
        'mistakes' => [['کمر افتاده', 'سفت کردن Core'], ['آرنج باز ۹۰°', 'زاویه ۴۵°'], ['سر آویزان', 'گردن خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۲۰', '۴۵–۶۰ث'], ['استقامت', '۳–۵', '۱۵–۳۰', '۳۰–۴۵ث'], ['قدرت', '۴', '۵–۱۰', '۶۰–۹۰ث']],
        'combos' => [['label' => 'سوپرسِت: ', 'link_text' => 'دیپ پارالل', 'slug' => 'دیپ-پارالل']],
        'faqs' => [['q' => 'چند بار در هفته؟', 'a' => '۲–۴ بار بسته به شدت؛ برای مبتدی هر روز سبک هم ممکن است.']],
        'summary' => 'شنا پایه‌ای‌ترین حرکت فشار برای سینه بدون تجهیزات.',
        'summary_keys' => 'خط بدن صاف | Core سفت | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['triceps', 'shoulder_anterior', 'abs'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'lying_prone', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'shoulder_elbow',
            'muscle_targets' => ['chest_middle' => 85, 'chest' => 80, 'triceps' => 50, 'shoulder_anterior' => 40, 'abs' => 35],
            'met' => 4, 'movement_distance_cm' => 35, 'calories_per_1000kg' => 35, 'exercise_difficulty_score' => 3, 'typical_rpe' => 6,
            'estimated_1rm_formula' => '', 'programming_goal' => 'endurance', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-15', 'rep_range_endurance' => '15-30', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'شنا سوئدی حرکت فشار افقی با وزن بدن برای سینه، پشت بازو و Core.',
            'target_area' => 'سینه',
        ],
        'rank_extra' => 'تمرین سینه در خانه بدون وسیله.',
    ]);

    $add([
        'slug' => 'ددلیفت',
        'title' => 'ددلیفت',
        'aliases' => ['Deadlift', 'Conventional Deadlift', 'Barbell Deadlift', 'ددلیفت کلاسیک'],
        'intro' => '<strong>ددلیفت</strong> حرکت هیپ‌هینج با هالتر برای قدرت کل بدن؛ همسترینگ، باسن، کمر و Core به‌شدت درگیر می‌شوند.',
        'caption' => 'ددلیفت — کمر خنثی و میله نزدیک پا',
        'quick' => ['main' => 'همسترینگ و باسن', 'secondary' => 'کمر، ساعد، چهارسر', 'difficulty' => 'پیشرفته', 'equipment' => 'هالتر', 'type' => 'قدرتی'],
        'tips' => ['میله روی پا نزدیک ساق.', 'کمر خنثی؛ قفسه بالا.', 'فشار از زمین با پا، نه کمر.'],
        'setup' => ['پا عرض لگن، میله روی میانی پا.', 'گرفتن mixed یا دوبل اورهند.', 'کتف روی میله، Core سفت.'],
        'execution' => ['باسن عقب، زانو خم.', 'کشش میله کنار پا.', 'ایستادن کامل با باسن جلو.', 'پایین با کنترل همان مسیر.'],
        'breathing' => 'نفس حبس قبل از کشش — بازدم در بالا یا بعد از عبور زانو.',
        'muscles' => ['اصلی: همسترینگ، گلوت', 'کمکی: erector spinae، تراپس', 'تثبیت: Core، ساعد'],
        'mistakes' => [['گرد شدن کمر', 'کتف جمع، میله نزدیک'], ['میله دور از پا', 'کشش عمودی نزدیک ساق'], ['کشش با کمر', 'فشار پا به زمین']],
        'program' => [['قدرت', '۳–۵', '۱–۵', '۳–۵ دقیقه'], ['حجم', '۳–۴', '۵–۸', '۱۸۰–۲۴۰ث'], ['تکنیک', '۳', '۵', '۱۲۰ث']],
        'combos' => [['label' => 'روز پا: بعد از ', 'link_text' => 'اسکات هالتر', 'slug' => 'اسکات-هالتر']],
        'faqs' => [['q' => 'RDL با ددلیفت فرق؟', 'a' => 'ددلیفت از زمین با زانوی بیشتر؛ RDL از ایستاده با زانوی ثابت‌تر و تمرکز همسترینگ.']],
        'summary' => 'ددلیفت پادشاه حرکات قدرتی برای کل زنجیره خلفی.',
        'summary_keys' => 'کمر خنثی | میله نزدیک | فشار پا',
        'meta' => [
            'main_muscle' => 'hamstrings', 'secondary_muscle_keys' => ['glutes', 'lower_back', 'forearms', 'quads'],
            'difficulty' => 'advanced', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'mixed', 'resistance_profile' => 'free_weight', 'joint_focus' => 'hip',
            'muscle_targets' => ['hamstrings' => 90, 'glutes' => 85, 'lower_back' => 70, 'forearms' => 45, 'quads' => 40, 'traps_upper' => 35],
            'met' => 6.5, 'movement_distance_cm' => 65, 'calories_per_1000kg' => 60, 'exercise_difficulty_score' => 8, 'typical_rpe' => 8.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'strength', 'recommended_sets' => '3-5',
            'rep_range_strength' => '1-5', 'rep_range_hypertrophy' => '5-8', 'rep_range_endurance' => '8-12', 'rest_seconds' => 180, 'tempo' => '2-0-1',
            'short_description' => 'ددلیفت حرکت هیپ‌هینج با هالتر برای قدرت همسترینگ، باسن، کمر و کل زنجیره خلفی.',
            'target_area' => 'پشت پا و باسن',
        ],
        'rank_extra' => 'قدرت کل بدن و زنجیره خلفی.',
    ]);

    $add([
        'slug' => 'فلای-دمبل',
        'title' => 'فلای دمبل',
        'aliases' => ['Dumbbell Fly', 'Chest Fly', 'DB Fly', 'قفسه دمبل', 'فلای سینه'],
        'intro' => '<strong>فلای دمبل</strong> حرکت ایزوله کششی برای سینه با دامنه افقی؛ مکمل عالی بعد از پرس‌ها.',
        'caption' => 'فلای دمبل — آرنج ثابت و کشش سینه',
        'quick' => ['main' => 'سینه', 'secondary' => 'سرشانه قدامی', 'difficulty' => 'متوسط', 'equipment' => 'دمبل، نیمکت', 'type' => 'حجمی'],
        'tips' => ['آرنج زاویه ثابت (~۱۵–۲۰° خم).', 'پایین تا کشش ملایم.', 'بالا مثل بستن درب.'],
        'setup' => ['درازکش روی نیمکت تخت.', 'دمبل بالای سینه، کف دست رو به هم.', 'کتف جمع.'],
        'execution' => ['با دم باز کردن دست‌ها کنار.', 'تا احساس کشش سینه.', 'با بازدم جمع کردن دمبل بالا.', 'انقباض ۱ ثانیه.'],
        'breathing' => 'دم باز — بازدم جمع.',
        'muscles' => ['اصلی: سینه (میانی)', 'کمکی: دلتوئید قدامی', 'تثبیت: Core'],
        'mistakes' => [['خم و باز کردن آرنج', 'آرنج ثابت'], ['وزنه سنگین', 'کاهش بار برای فرم'], ['پایین بیش از حد', 'دامنه تا کشش امن']],
        'program' => [['حجم', '۳–۴', '۱۰–۱۵', '۶۰ث'], ['فینشر', '۲–۳', '۱۲–۲۰', '۴۵ث'], ['پمپ', '۲', '۱۵–۲۰', '۳۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'پرس سینه با هالتر', 'slug' => 'پرس-سینه-با-هالتر']],
        'faqs' => [['q' => 'فلای یا کراس سیمکش؟', 'a' => 'هر دو عالی؛ فلای دمبل آزاد، کراس تنش ثابت کابل.']],
        'summary' => 'فلای دمبل برای کشش و فرم‌دهی سینه ضروری است.',
        'summary_keys' => 'آرنج ثابت | کشش کنترل‌شده | انقباض',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['shoulder_anterior'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell', 'bench'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'chest_fly', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'transverse', 'laterality' => 'bilateral',
            'posture' => 'lying_supine', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'shoulder',
            'muscle_targets' => ['chest_middle' => 95, 'chest' => 85, 'chest_upper' => 45, 'shoulder_anterior' => 30],
            'met' => 4, 'movement_distance_cm' => 50, 'calories_per_1000kg' => 35, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '8-10', 'rep_range_hypertrophy' => '10-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 60, 'tempo' => '3-1-2',
            'short_description' => 'فلای دمبل حرکت ایزوله برای کشش و هایپرتروفی سینه با دامنه افقی.',
            'target_area' => 'سینه',
        ],
        'rank_extra' => 'فرم‌دهی و کشش سینه.',
    ]);

    $add([
        'slug' => 'کراس-سیمکش',
        'title' => 'کراس سیمکش',
        'aliases' => ['Cable Crossover', 'Cable Fly', 'کراس اور', 'فلای سیمکش'],
        'intro' => '<strong>کراس سیمکش</strong> فلای با کابل برای تنش مداوم روی سینه؛ از بالا، وسط یا پایین قابل تنظیم است.',
        'caption' => 'کراس سیمکش — قوس حرکت و انقباض سینه',
        'quick' => ['main' => 'سینه', 'secondary' => 'سرشانه قدامی', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'حجمی'],
        'tips' => ['قدم کوچک جلو.', 'آرنج کمی خم ثابت.', 'کتف پایین.'],
        'setup' => ['تنظیم پولی (معمولاً بالا برای پایین سینه).', 'گرفتن دستگیره‌ها.', 'تنه کمی مایل.'],
        'execution' => ['باز کردن دست‌ها کنار.', 'قوس به جلو و پایین (یا بالا).', 'انقباض سینه جلو.', 'بازگشت کنترل‌شده.'],
        'breathing' => 'بازدم در جلو — دم در باز.',
        'muscles' => ['اصلی: سینه', 'کمکی: دلتوئید قدامی', 'تثبیت: Core'],
        'mistakes' => [['فشار با شانه', 'تمرکز سینه'], ['کمر قوس زیاد', 'ثبات تنه'], ['وزنه زیاد', 'تمپو کنترل']],
        'program' => [['حجم', '۳–۴', '۱۲–۱۵', '۴۵–۶۰ث'], ['فینشر', '۲', '۱۵–۲۰', '۳۰ث'], ['پمپ', '۳', '۱۵', '۳۰ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پرس سینه دستگاه', 'slug' => 'پرس-سینه-دستگاه']],
        'faqs' => [['q' => 'ارتفاع پولی؟', 'a' => 'بالا→پایین سینه؛ پایین→بالا سینه؛ وسط→میانی.']],
        'summary' => 'کراس سیمکش برای پمپ و فرم سینه بی‌نظیر است.',
        'summary_keys' => 'تنش مداوم | قوس کنترل | انقباض',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['shoulder_anterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'chest_fly', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'transverse', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'shoulder',
            'muscle_targets' => ['chest_middle' => 90, 'chest_lower' => 55, 'chest_upper' => 50, 'shoulder_anterior' => 25],
            'met' => 4, 'movement_distance_cm' => 45, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '8-12', 'rep_range_hypertrophy' => '12-15', 'rep_range_endurance' => '15-20', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'کراس سیمکش فلای کابلی با تنش مداوم برای هایپرتروفی و فرم سینه.',
            'target_area' => 'سینه',
        ],
        'rank_extra' => 'پمپ و فرم سینه با کابل.',
    ]);

    $add([
        'slug' => 'پرس-سینه-شیب-دار',
        'title' => 'پرس سینه شیب دار',
        'aliases' => ['Incline Bench Press', 'Incline Barbell Press', 'Incline Dumbbell Press', 'پرس بالاسینه'],
        'intro' => '<strong>پرس سینه شیب دار</strong> (بالاسینه) برای تأکید روی fibers بالایی سینه و سرشانه قدامی است؛ معمولاً ۱۵–۳۰ درجه.',
        'caption' => 'پرس سینه شیب دار — زاویه ملایم نیمکت',
        'quick' => ['main' => 'سینه بالایی', 'secondary' => 'سرشانه قدامی، پشت بازو', 'difficulty' => 'متوسط', 'equipment' => 'هالتر یا دمبل، نیمکت شیب‌دار', 'type' => 'قدرتی / حجمی'],
        'tips' => ['زاویه ۱۵–۳۰° کافی است.', 'میله/دمبل به بالای سینه.', 'کتف جمع.'],
        'setup' => ['نیمکت ۱۵–۳۰ درجه.', 'پا ثابت.', 'گرفتن وزنه خط بالای سینه.'],
        'execution' => ['پایین کنترل‌شده به خط بالای سینه.', 'بازدم فشار بالا.', 'آرنج نرم.'],
        'breathing' => 'دم پایین — بازدم بالا.',
        'muscles' => ['اصلی: سینه بالایی (clavicular)', 'کمکی: دلتوئید قدامی، تریسپس', 'تثبیت: Core'],
        'mistakes' => [['زاویه ۴۵°+', 'شیب ملایم ۱۵–۳۰°'], ['میله روی گردن', 'خط بالای سینه'], ['کتف شل', 'جمع قبل از تکرار']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۹۰ث'], ['قدرت', '۴', '۴–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۶۰ث']],
        'combos' => [['label' => 'بعد از ', 'link_text' => 'پرس سینه با هالتر', 'slug' => 'پرس-سینه-با-هالتر']],
        'faqs' => [['q' => 'هالتر یا دمبل؟', 'a' => 'هالتر برای بار بیشتر؛ دمبل برای دامنه و تعادل.']],
        'summary' => 'پرس شیب‌دار کلید سینه‌ی «پر» و بالاتنه قوی.',
        'summary_keys' => 'شیب ۱۵–۳۰° | خط بالای سینه | کتف جمع',
        'meta' => [
            'main_muscle' => 'chest_upper', 'secondary_muscle_keys' => ['shoulder_anterior', 'triceps'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell', 'incline_bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'incline', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'shoulder_elbow',
            'muscle_targets' => ['chest_upper' => 95, 'chest_middle' => 70, 'shoulder_anterior' => 50, 'triceps' => 45],
            'met' => 6, 'movement_distance_cm' => 42, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '4-8', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پرس سینه شیب دار برای بالاسینه، سرشانه قدامی و پشت بازو با نیمکت ۱۵–۳۰ درجه.',
            'target_area' => 'سینه بالایی',
        ],
        'rank_extra' => 'برجسته‌سازی بالاسینه.',
    ]);

    $add([
        'slug' => 'جلو-بازو-هالتر',
        'title' => 'جلو بازو هالتر',
        'aliases' => ['Barbell Curl', 'BB Curl', 'Standing Barbell Curl', 'کرل هالتر'],
        'intro' => '<strong>جلو بازو هالتر</strong> حرکت پایه برای ضخامت و قدرت جلوبازو با بار مشترک.',
        'caption' => 'جلو بازو هالتر ایستاده',
        'quick' => ['main' => 'جلوبازو', 'secondary' => 'براکیالیس، ساعد', 'difficulty' => 'مبتدی', 'equipment' => 'هالتر', 'type' => 'حجمی'],
        'tips' => ['آرنج کنار بدن.', 'بدون تاب بدن.', 'پایین کامل بدون قفل.'],
        'setup' => ['ایستاده، هالتر underhand.', 'آرنج ثابت کنار تنه.', 'Core سفت.'],
        'execution' => ['خم کردن آرنج تا جلو بازو منقبض.', 'پایین آهسته.', 'تکرار بدون تاب.'],
        'breathing' => 'بازدم بالا — دم پایین.',
        'muscles' => ['اصلی: biceps brachii', 'کمکی: brachialis، forearms', 'تثبیت: Core'],
        'mistakes' => [['تاب بدن', 'کاهش وزنه'], ['آرنج جلو', 'ثابت کنار بدن'], ['نیمه دامنه', 'پایین و بالا کامل']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث'], ['قدرت', '۳', '۶–۸', '۹۰ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'جلو بازو دمبل', 'slug' => 'جلو-بازو-دمبل']],
        'faqs' => [['q' => 'میله EZ بهتر است؟', 'a' => 'EZ مچ راحت‌تر؛ هالتر مستقیم بار بیشتر روی biceps.']],
        'summary' => 'کرل هالتر کلاسیک‌ترین حرکت جلوبازو.',
        'summary_keys' => 'آرنج ثابت | بدون تاب | دامنه کامل',
        'meta' => [
            'main_muscle' => 'biceps', 'secondary_muscle_keys' => ['brachialis', 'forearms'],
            'difficulty' => 'beginner', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'hypertrophy', 'movement_pattern' => 'elbow_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'supinated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'elbow',
            'muscle_targets' => ['biceps' => 95, 'brachialis' => 50, 'forearms' => 40],
            'met' => 3.5, 'movement_distance_cm' => 45, 'calories_per_1000kg' => 35, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-8', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'جلو بازو هالتر حرکت پایه ایزوله برای هایپرتروفی جلوبازو و ساعد.',
            'target_area' => 'جلوبازو',
        ],
        'rank_extra' => 'ضخامت جلوبازو با هالتر.',
    ]);

    return $defs;
}
}

