// GymAI Popular — BATCH 6 (20 حرکت)
// Code Snippets: Run everywhere | بدون تگ php

if (!function_exists('gymai_pop20_batch6_definitions')) {
function gymai_pop20_batch6_definitions() {
    $base_img = 'https://gymaipro.ir/wp-content/uploads/2026/06/';
    $defs = [];
    $add = function (array $row) use (&$defs, $base_img) {
        if (empty($row['image'])) {
            $key = !empty($row['image_key']) ? $row['image_key'] : ('exercise-batch6-' . str_pad((string) (count($defs) + 1), 2, '0', STR_PAD_LEFT));
            $row['image'] = $base_img . $key . '.jpg';
        }
        $defs[] = $row;
    };

    $add([
        'image_key' => 'exercise-batch6-01',
        'slug' => 'شنا-با-زانو',
        'title' => 'شنا با زانو',
        'aliases' => ['Knee Push-Up', 'KneePush-Up', 'شنا با زانو'],
        'intro' => '<strong>شنا با زانو</strong> (Knee Push-Up) شنا سوئدی با زانو روی زمین؛ نقطه شروع محبوب قبل از شنا کامل در خانه و سالن. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'شنا با زانو — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'پشت بازو، سرشانه', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: پشت بازو، سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'شنا سوئدی', 'slug' => 'شنا-سوئدی']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'شنا با زانو برای سینه و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['triceps', 'shoulder_anterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'prone', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest' => 80, 'triceps' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'شنا با زانو برای مبتدی.',
            'target_area' => 'سینه',
        ],
        'rank_extra' => 'مسیر یادگیری شنا.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-02',
        'slug' => 'پرس-سینه-اسمیت',
        'title' => 'پرس سینه اسمیت',
        'aliases' => ['Smith Machine Bench Press', 'SmithMachineBenchPress', 'پرس سینه اسمیت'],
        'intro' => '<strong>پرس سینه اسمیت</strong> (Smith Machine Bench Press) پرس سینه روی اسمیت؛ برای مبتدی و تمرین تا ناتوانی امن‌تر از هالتر آزاد. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه و نیمکت اجرا می‌شود.',
        'caption' => 'پرس سینه اسمیت — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'پشت بازو، سرشانه', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه و نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: پشت بازو، سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پرس سینه با دمبل', 'slug' => 'پرس-سینه-با-دمبل']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پرس سینه اسمیت برای سینه و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['triceps', 'shoulder_anterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest' => 90, 'triceps' => 50],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پرس سینه اسمیت با ثبات بالا.',
            'target_area' => 'سینه',
        ],
        'rank_extra' => 'ثبات و ایمنی.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-03',
        'slug' => 'لگ-پرس',
        'title' => 'لگ پرس',
        'aliases' => ['Leg Press', 'LegPress', 'لگ پرس'],
        'intro' => '<strong>لگ پرس</strong> (Leg Press) پرس پا روی دستگاه ۴۵ یا افقی؛ یکی از پرکاربردترین حرکات پا در سالن‌های ایرانی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'لگ پرس — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، همسترینگ', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن، همسترینگ', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'اسکات گابلت', 'slug' => 'اسکات-گابلت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'لگ پرس برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'hamstrings'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'squat', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 90, 'glutes' => 70],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'لگ پرس برای پا با بار بالا.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'بار سنگین پا.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-04',
        'slug' => 'جلو-بازو-اینکلاین-دمبل',
        'title' => 'جلو بازو اینکلاین دمبل',
        'aliases' => ['Incline Dumbbell Curl', 'InclineDumbbellCurl', 'جلو بازو اینکلاین دمبل'],
        'intro' => '<strong>جلو بازو اینکلاین دمبل</strong> (Incline Dumbbell Curl) جلو بازو روی نیمکت شیب مثبت؛ برای کشش طولانی دوبی و حجم بازو محبوب است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل و نیمکت اجرا می‌شود.',
        'caption' => 'جلو بازو اینکلاین دمبل — جلوبازو، اجرای کنترل‌شده',
        'quick' => ['main' => 'جلوبازو', 'secondary' => 'ساعد', 'difficulty' => 'متوسط', 'equipment' => 'دمبل و نیمکت', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی جلوبازو در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: جلوبازو', 'کمکی: ساعد', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'جلو بازو دمبل', 'slug' => 'جلو-بازو-دمبل']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'جلو بازو اینکلاین دمبل برای جلوبازو و جلوبازو در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'جلوبازو | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'biceps', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'elbow_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'incline_seated', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['biceps' => 95],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'جلو بازو اینکلاین برای کشش بیشتر.',
            'target_area' => 'جلوبازو',
        ],
        'rank_extra' => 'کشش طولانی دوبی.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-05',
        'slug' => 'پشت-بازو-خرچنگ-سیمکش',
        'title' => 'پشت بازو خرچنگ سیمکش',
        'aliases' => ['Rope Tricep Pushdown', 'RopeTricepPushdown', 'پشت بازو خرچنگ سیمکش'],
        'intro' => '<strong>پشت بازو خرچنگ سیمکش</strong> (Rope Tricep Pushdown) پشت بازو با طناب سیم‌کش؛ انقباض کامل در پایین محبوب‌ترین حرکت پشت بازو در سالن. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'پشت بازو خرچنگ سیمکش — پشت بازو، اجرای کنترل‌شده',
        'quick' => ['main' => 'پشت بازو', 'secondary' => '—', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی پشت بازو در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: پشت بازو', 'کمکی: عضلات کمکی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت بازو سیمکش', 'slug' => 'پشت-بازو-سیمکش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پشت بازو خرچنگ سیمکش برای پشت بازو و پشت بازو در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'پشت بازو | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => [],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'elbow_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['triceps' => 95],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'فشار خرچنگ برای پمپ پشت بازو.',
            'target_area' => 'پشت بازو',
        ],
        'rank_extra' => 'انقباض کامل.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-06',
        'slug' => 'فشار-پشت-بازو-هالتر',
        'title' => 'فشار پشت بازو هالتر',
        'aliases' => ['Skull Crusher', 'SkullCrusher', 'فشار پشت بازو هالتر'],
        'intro' => '<strong>فشار پشت بازو هالتر</strong> (Skull Crusher) لایینگ تریسپس اکستنشن با هالتر EZ یا مستقیم؛ کلاسیک روز بازو. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر و نیمکت اجرا می‌شود.',
        'caption' => 'فشار پشت بازو هالتر — پشت بازو، اجرای کنترل‌شده',
        'quick' => ['main' => 'پشت بازو', 'secondary' => '—', 'difficulty' => 'متوسط', 'equipment' => 'هالتر و نیمکت', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی پشت بازو در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: پشت بازو', 'کمکی: عضلات کمکی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت بازو دمبل خوابیده', 'slug' => 'پشت-بازو-دمبل-خوابیده']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'فشار پشت بازو هالتر برای پشت بازو و پشت بازو در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'پشت بازو | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => [],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'elbow_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['triceps' => 95],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'فشار پشت بازو هالتر خوابیده.',
            'target_area' => 'پشت بازو',
        ],
        'rank_extra' => 'حجم پشت بازو.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-07',
        'slug' => 'کرانچ-سیمکش',
        'title' => 'کرانچ سیمکش',
        'aliases' => ['Cable Crunch', 'CableCrunch', 'کرانچ سیمکش'],
        'intro' => '<strong>کرانچ سیمکش</strong> (Cable Crunch) جمع شدن تنه با سیم‌کش زانو زده؛ جایگزین وزنه برای شکم در سالن. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'کرانچ سیمکش — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'پهلو', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: پهلو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کرانچ', 'slug' => 'کرانچ']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'کرانچ سیمکش برای شکم و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['obliques'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'spinal_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'kneeling', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 90],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'کرانچ سیمکش با مقاومت قابل تنظیم.',
            'target_area' => 'شکم',
        ],
        'rank_extra' => 'مقاومت پیشرونده.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-08',
        'slug' => 'زیربغل-تک-بازو-سیمکش',
        'title' => 'زیربغل تک بازو سیمکش',
        'aliases' => ['Single Arm Lat Pulldown', 'SingleArmLatPulldown', 'زیربغل تک بازو سیمکش'],
        'intro' => '<strong>زیربغل تک بازو سیمکش</strong> (Single Arm Lat Pulldown) کشش عمودی یک دست؛ رفع عدم تقارن زیربغل. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'زیربغل تک بازو سیمکش — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو', 'difficulty' => 'متوسط', 'equipment' => 'سیم‌کش', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'زیربغل سیمکش', 'slug' => 'زیربغل-سیمکش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'زیربغل تک بازو سیمکش برای زیربغل و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'kneeling', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 90],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پول‌داون تک‌بازو برای تعادل پشت.',
            'target_area' => 'زیربغل',
        ],
        'rank_extra' => 'تعادل چپ و راست.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-09',
        'slug' => 'فلای-پک-دستگاه',
        'title' => 'فلای پک دستگاه',
        'aliases' => ['Pec Deck Fly', 'PecDeckFly', 'فلای پک دستگاه'],
        'intro' => '<strong>فلای پک دستگاه</strong> (Pec Deck Fly) دستگاه پک دک؛ برای مبتدی و پمپ سینه بدون نیاز به تعادل دمبل. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'فلای پک دستگاه — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'سرشانه', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'فلای دمبل', 'slug' => 'فلای-دمبل']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'فلای پک دستگاه برای سینه و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['shoulder_anterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest' => 92],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'فلای پک برای ایزوله سینه.',
            'target_area' => 'سینه',
        ],
        'rank_extra' => 'ایزوله امن سینه.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-10',
        'slug' => 'دیپ-وزن-بدن',
        'title' => 'دیپ وزن بدن',
        'aliases' => ['Bodyweight Dip', 'BodyweightDip', 'دیپ وزن بدن'],
        'intro' => '<strong>دیپ وزن بدن</strong> (Bodyweight Dip) دیپ با وزن بدن روی نیمکت؛ در خانه و سالن بدون پارالل محبوب است. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن و نیمکت اجرا می‌شود.',
        'caption' => 'دیپ وزن بدن — پشت بازو، اجرای کنترل‌شده',
        'quick' => ['main' => 'پشت بازو', 'secondary' => 'chest، سرشانه', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن و نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی پشت بازو در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: پشت بازو', 'کمکی: chest، سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'دیپ نیمکت', 'slug' => 'دیپ-نیمکت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'دیپ وزن بدن برای پشت بازو و سینه و پشت بازو در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'پشت بازو | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => ['chest', 'shoulder_anterior'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'support', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['triceps' => 85, 'chest' => 55],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'دیپ بین دو نیمکت برای پشت بازو.',
            'target_area' => 'پشت بازو و سینه',
        ],
        'rank_extra' => 'پشت بازو در خانه.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-11',
        'slug' => 'اسکات-با-مکث',
        'title' => 'اسکات با مکث',
        'aliases' => ['Pause Squat', 'PauseSquat', 'اسکات با مکث'],
        'intro' => '<strong>اسکات با مکث</strong> (Pause Squat) اسکات با توقف ۲–۳ ثانیه در پایین‌ترین نقطه؛ برای قدرت از نقطه مرده. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'اسکات با مکث — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، همسترینگ', 'difficulty' => 'پیشرفته', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن، همسترینگ', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'اسکات هالتر', 'slug' => 'اسکات-هالتر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'اسکات با مکث برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'hamstrings'],
            'difficulty' => 'advanced', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'squat', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 90, 'glutes' => 75],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'اسکات با مکث در پایین برای قدرت.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'قدرت از عمق.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-12',
        'slug' => 'بورپی',
        'title' => 'بورپی',
        'aliases' => ['Burpee', 'Burpee', 'بورپی'],
        'intro' => '<strong>بورپی</strong> (Burpee) حرکت ترکیبی پرش و شنا؛ برای چربی‌سوزی و آمادگی در تمرین‌های فانکشنال ایران. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'بورپی — تمام بدن، اجرای کنترل‌شده',
        'quick' => ['main' => 'تمام بدن', 'secondary' => 'chest، quads، Core', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی تمام بدن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: تمام بدن', 'کمکی: chest، quads، Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کوهنورد', 'slug' => 'کوهنورد']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'بورپی برای تمام بدن و تمام بدن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'تمام بدن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'full_body', 'secondary_muscle_keys' => ['chest', 'quads', 'abs'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'conditioning', 'movement_pattern' => 'compound', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 60, 'chest' => 50, 'abs' => 55],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'بورپی برای کاردیو و قدرت عملکردی.',
            'target_area' => 'تمام بدن',
        ],
        'rank_extra' => 'کاردیو شدید.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-13',
        'slug' => 'ددباگ',
        'title' => 'ددباگ',
        'aliases' => ['Dead Bug', 'DeadBug', 'ددباگ'],
        'intro' => '<strong>ددباگ</strong> (Dead Bug) حرکت اصلاحی درازکش؛ برای Core بدون فشار گردن محبوب فیزیوتراپی و بدنسازی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'ددباگ — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'hip_flexors', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: hip_flexors', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پلانک', 'slug' => 'پلانک-plank']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'ددباگ برای Core و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['hip_flexors'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'anti_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 85],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'ددباگ برای Core پایدار.',
            'target_area' => 'Core',
        ],
        'rank_extra' => 'Core امن.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-14',
        'slug' => 'پالوف-پرس',
        'title' => 'پالوف پرس',
        'aliases' => ['Pallof Press', 'PallofPress', 'پالوف پرس'],
        'intro' => '<strong>پالوف پرس</strong> (Pallof Press) فشار افقی سیم‌کش مقابل کشش؛ برای پایداری Core و کمر. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'پالوف پرس — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'پهلو', 'difficulty' => 'متوسط', 'equipment' => 'سیم‌کش', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: پهلو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پلانک جانبی', 'slug' => 'پلانک-جانبی']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'پالوف پرس برای Core و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['obliques'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'anti_rotation', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 80, 'obliques' => 70],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پالوف ضد چرخش برای Core.',
            'target_area' => 'Core',
        ],
        'rank_extra' => 'ضد چرخش.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-15',
        'slug' => 'پرس-سینه-دمبل-تک-دست',
        'title' => 'پرس سینه دمبل تک دست',
        'aliases' => ['Single Arm Dumbbell Press', 'SingleArmDumbbellPress', 'پرس سینه دمبل تک دست'],
        'intro' => '<strong>پرس سینه دمبل تک دست</strong> (Single Arm Dumbbell Press) پرس سینه یک دست؛ ضدچرخش Core و رفع عدم تقارن. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل و نیمکت اجرا می‌شود.',
        'caption' => 'پرس سینه دمبل تک دست — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'پشت بازو، Core', 'difficulty' => 'متوسط', 'equipment' => 'دمبل و نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: پشت بازو، Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پرس سینه با دمبل', 'slug' => 'پرس-سینه-با-دمبل']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'پرس سینه دمبل تک دست برای سینه و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['triceps', 'abs'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest' => 85, 'abs' => 40],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پرس تک‌دست برای Core و تعادل.',
            'target_area' => 'سینه',
        ],
        'rank_extra' => 'تعادل و Core.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-16',
        'slug' => 'زیربغل-نشسته-سیمکش',
        'title' => 'زیربغل نشسته سیمکش',
        'aliases' => ['Seated Cable Row', 'SeatedCableRow', 'زیربغل نشسته سیمکش'],
        'intro' => '<strong>زیربغل نشسته سیمکش</strong> (Seated Cable Row) کشش افقی نشسته؛ یکی از پرتکرارترین حرکات پشت در سالن ایرانی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'زیربغل نشسته سیمکش — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو، پشت میانی', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو، پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'رویینگ سیمکش', 'slug' => 'رویینگ-سیمکش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'زیربغل نشسته سیمکش برای پشت و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'rhomboids'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 88, 'rhomboids' => 55, 'biceps' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'رویینگ نشسته سیمکش کلاسیک.',
            'target_area' => 'پشت',
        ],
        'rank_extra' => 'پشت پهن و ضخیم.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-17',
        'slug' => 'لانج-هالتر',
        'title' => 'لانج با هالتر',
        'aliases' => ['Barbell Lunge', 'BarbellLunge', 'لانج با هالتر'],
        'intro' => '<strong>لانج با هالتر</strong> (Barbell Lunge) لانج با هالتر پشت یا جلو؛ قدرت پا تک‌طرفه در روز پا. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'لانج با هالتر — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، همسترینگ', 'difficulty' => 'متوسط', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن، همسترینگ', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'لانج', 'slug' => 'لانج']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'لانج با هالتر برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'hamstrings'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'lunge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 85, 'glutes' => 75],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'لانج هالتر برای پا و تعادل.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'قدرت تک‌پا.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-18',
        'slug' => 'لانج-عقب',
        'title' => 'لانج عقب',
        'aliases' => ['Reverse Lunge', 'ReverseLunge', 'لانج عقب'],
        'intro' => '<strong>لانج عقب</strong> (Reverse Lunge) قدم به عقب با دمبل؛ برای مبتدی و زانو حساس مناسب‌تر از لانج جلو. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل اجرا می‌شود.',
        'caption' => 'لانج عقب — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'لانج راه رفتن', 'slug' => 'لانج-راه-رفتن']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'لانج عقب برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'lunge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 80, 'glutes' => 75],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'لانج عقب فشار کمتر روی زانو.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'زانو دوست‌دار.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-19',
        'slug' => 'پشت-بازو-سیمکش-معکوس',
        'title' => 'پشت بازو سیمکش معکوس',
        'aliases' => ['Reverse Grip Pushdown', 'ReverseGripPushdown', 'پشت بازو سیمکش معکوس'],
        'intro' => '<strong>پشت بازو سیمکش معکوس</strong> (Reverse Grip Pushdown) فشار پایین با کف دست رو به بالا؛ تاکید روی سر دراز تریسپس. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'پشت بازو سیمکش معکوس — پشت بازو، اجرای کنترل‌شده',
        'quick' => ['main' => 'پشت بازو', 'secondary' => '—', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی پشت بازو در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: پشت بازو', 'کمکی: عضلات کمکی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پشت بازو خرچنگ سیمکش', 'slug' => 'پشت-بازو-خرچنگ-سیمکش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پشت بازو سیمکش معکوس برای پشت بازو و پشت بازو در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'پشت بازو | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'triceps', 'secondary_muscle_keys' => [],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'elbow_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['triceps' => 90],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پشت بازو دست معکوس برای سر دراز.',
            'target_area' => 'پشت بازو',
        ],
        'rank_extra' => 'سر دراز تریسپس.',
    ]);

    $add([
        'image_key' => 'exercise-batch6-20',
        'slug' => 'وال-سیت',
        'title' => 'وال سیت',
        'aliases' => ['Wall Sit', 'WallSit', 'وال سیت'],
        'intro' => '<strong>وال سیت</strong> (Wall Sit) نشستن imaginary روی دیوار؛ برای استقامت چهارسر در خانه و گرم‌کردن فوتبال محبوب ایران. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'وال سیت — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'اسکات گابلت', 'slug' => 'اسکات-گابلت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'وال سیت برای پا و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'isometric', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 85, 'glutes' => 50],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'وال سیت ایزومتریک برای استقامت پا.',
            'target_area' => 'پا',
        ],
        'rank_extra' => 'استقامت چهارسر.',
    ]);

    return $defs;
}
}
