// GymAI Popular — BATCH 15 (20 حرکت — حرکات 261 تا 280)
// Code Snippets: Run everywhere | بدون تگ php

if (!function_exists('gymai_pop20_batch15_definitions')) {
function gymai_pop20_batch15_definitions() {
    $base_img = 'https://gymaipro.ir/wp-content/uploads/2026/08/';
    $defs = [];
    $add = function (array $row) use (&$defs, $base_img) {
        if (empty($row['image'])) {
            $key = !empty($row['image_key']) ? $row['image_key'] : ('exercise-batch15-' . str_pad((string) (count($defs) + 1), 2, '0', STR_PAD_LEFT));
            $row['image'] = $base_img . $key . '.jpg';
        }
        $defs[] = $row;
    };

    $add([
        'image_key' => 'exercise-batch15-01',
        'slug' => 'برپی',
        'title' => 'برپی',
        'aliases' => ['Burpee', 'Burpee', 'برپی', 'برپی پوش‌آپ', 'برپی کامل'],
        'intro' => '<strong>برپی</strong> (Burpee) اسکات، شنا، پرش؛ حرکت استاندارد HIIT و کراس‌فیت. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'برپی — تمام بدن، اجرای کنترل‌شده',
        'quick' => ['main' => 'تمام بدن', 'secondary' => 'chest، quads', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی تمام بدن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: تمام بدن', 'کمکی: chest، quads', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'بورپی', 'slug' => 'بورپی']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'برپی برای کاردیو و تمام بدن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'تمام بدن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'full_body', 'secondary_muscle_keys' => ['chest', 'quads'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'conditioning', 'movement_pattern' => 'compound', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 55, 'chest' => 45, 'abs' => 50, 'shoulder_anterior' => 40],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'برپی برای کاردیو و قدرت کل بدن.',
            'target_area' => 'کاردیو',
        ],
        'rank_extra' => 'HIIT کلاسیک.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-02',
        'slug' => 'مانتین-کلایمبر',
        'title' => 'مانتین کلایمبر',
        'aliases' => ['Mountain Climber', 'MountainClimber', 'مانتین کلایمبر', 'کوه نورد', 'مانتین کلایمبر سریع'],
        'intro' => '<strong>مانتین کلایمبر</strong> (Mountain Climber) در پلانک زانو به سینه سریع؛ کاردیو و شکم. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'مانتین کلایمبر — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'quads، سرشانه', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: quads، سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کوهنورد', 'slug' => 'کوهنورد']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'مانتین کلایمبر برای Core و کاردیو و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['quads', 'shoulder_anterior'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'anti_extension', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'prone', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 80, 'quads' => 45, 'shoulder_anterior' => 35],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'کوهنورد برای Core و ضربان.',
            'target_area' => 'Core و کاردیو',
        ],
        'rank_extra' => 'کاردیو Core.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-03',
        'slug' => 'توئیست-روسی',
        'title' => 'توئیست روسی',
        'aliases' => ['Russian Twist', 'RussianTwist', 'توئیست روسی', 'چرخش روسی دمبل', 'توئیست شکم'],
        'intro' => '<strong>توئیست روسی</strong> (Russian Twist) چرخش تنه نشسته؛ نام رایج‌تر از چرخش روسی در باشگاه. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن و دمبل اجرا می‌شود.',
        'caption' => 'توئیست روسی — پهلو، اجرای کنترل‌شده',
        'quick' => ['main' => 'پهلو', 'secondary' => 'Core', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن و دمبل', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی پهلو در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: پهلو', 'کمکی: Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'چرخش روسی', 'slug' => 'چرخش-روسی']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'توئیست روسی برای پهلو و پهلو در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'پهلو | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'obliques', 'secondary_muscle_keys' => ['abs'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight', 'dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'rotation', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['obliques' => 90, 'abs' => 65],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'توئیست روسی برای پهلو.',
            'target_area' => 'پهلو',
        ],
        'rank_extra' => 'پهلو.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-04',
        'slug' => 'هانگینگ-لگ-ریز',
        'title' => 'هانگینگ لگ ریز',
        'aliases' => ['Hanging Leg Raise', 'HangingLegRaise', 'هانگینگ لگ ریز', 'لگ ریز آویزان', 'پای آویزان کنترل'],
        'intro' => '<strong>هانگینگ لگ ریز</strong> (Hanging Leg Raise) بالا آوردن پا آویزان؛ نسخه دقیق‌تر پای آویزان با تاکید شکم. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن و میله اجرا می‌شود.',
        'caption' => 'هانگینگ لگ ریز — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'hip_flexors، ساعد', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن و میله', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و میله و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: hip_flexors، ساعد', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پای آویزان', 'slug' => 'پای-آویزان']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'هانگینگ لگ ریز برای شکم پایین و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['hip_flexors', 'forearms'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight', 'bar'],
            'exercise_type' => 'strength', 'movement_pattern' => 'spinal_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'hanging', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 90, 'abs_lower' => 92],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پای آویزان کنترل‌شده برای شکم.',
            'target_area' => 'شکم پایین',
        ],
        'rank_extra' => 'شکم پایین.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-05',
        'slug' => 'اب-ویل-ایستاده',
        'title' => 'اب ویل ایستاده',
        'aliases' => ['Standing Ab Wheel', 'StandingAbWheel', 'اب ویل ایستاده', 'Standing Rollout', 'رولاوت ایستاده'],
        'intro' => '<strong>اب ویل ایستاده</strong> (Standing Ab Wheel) غلتاندن چرخ از ایستاده؛ چالش پیشرفته‌تر از زانو. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'اب ویل ایستاده — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'سرشانه، زیربغل', 'difficulty' => 'پیشرفته', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: سرشانه، زیربغل', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'چرخ شکم', 'slug' => 'چرخ-شکم']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'اب ویل ایستاده برای Core و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['shoulder_anterior', 'lats'],
            'difficulty' => 'advanced', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'anti_extension', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 95, 'shoulder_anterior' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'چرخ شکم از حالت ایستاده.',
            'target_area' => 'Core',
        ],
        'rank_extra' => 'Core پیشرفته.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-06',
        'slug' => 'کرانچ-ماشین',
        'title' => 'کرانچ ماشین',
        'aliases' => ['Machine Crunch', 'MachineCrunch', 'کرانچ ماشین', 'Ab Crunch Machine', 'کرانچ دستگاه'],
        'intro' => '<strong>کرانچ ماشین</strong> (Machine Crunch) کرانچ روی دستگاه با صفحه وزنه؛ کنترل آسان برای شکم. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'کرانچ ماشین — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => '—', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: عضلات کمکی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کرانچ', 'slug' => 'کرانچ']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'کرانچ ماشین برای شکم و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => [],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'spinal_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 90],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'کرانچ دستگاه برای مبتدی.',
            'target_area' => 'شکم',
        ],
        'rank_extra' => 'شکم دستگاه.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-07',
        'slug' => 'ساید-کرانچ',
        'title' => 'ساید کرانچ',
        'aliases' => ['Side Crunch', 'SideCrunch', 'ساید کرانچ'],
        'intro' => '<strong>ساید کرانچ</strong> (Side Crunch) کرانچ به طرف؛ ساده برای پهلو در خانه. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'ساید کرانچ — پهلو، اجرای کنترل‌شده',
        'quick' => ['main' => 'پهلو', 'secondary' => 'Core', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی پهلو در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: پهلو', 'کمکی: Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پلانک جانبی', 'slug' => 'پلانک-جانبی']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'ساید کرانچ برای پهلو و پهلو در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'پهلو | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'obliques', 'secondary_muscle_keys' => ['abs'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'lateral_flexion', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['obliques' => 88, 'abs' => 50],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'ساید کرانچ برای oblique.',
            'target_area' => 'پهلو',
        ],
        'rank_extra' => 'پهلو ساده.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-08',
        'slug' => 'دبل-کرانچ',
        'title' => 'دبل کرانچ',
        'aliases' => ['Double Crunch', 'DoubleCrunch', 'دبل کرانچ'],
        'intro' => '<strong>دبل کرانچ</strong> (Double Crunch) بالا آوردن شانه و زانو با هم؛ شکم کامل. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'دبل کرانچ — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'hip_flexors', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: hip_flexors', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کرانچ', 'slug' => 'کرانچ']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'دبل کرانچ برای شکم و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['hip_flexors'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'spinal_flexion', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 92, 'abs_lower' => 85],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'دبل کرانچ بالا و پایین همزمان.',
            'target_area' => 'شکم',
        ],
        'rank_extra' => 'شکم کامل.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-09',
        'slug' => 'ترکیش-گت-آپ',
        'title' => 'ترکیش گت آپ',
        'aliases' => ['Turkish Get-Up', 'TurkishGet-Up', 'ترکیش گت آپ', 'Turkish Get Up', 'TGU', 'گت آپ ترکیش'],
        'intro' => '<strong>ترکیش گت آپ</strong> (Turkish Get-Up) از خوابیده تا ایستاده با کتل‌بل بالای سر؛ مهارت و قدرت. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با کتل‌بل اجرا می‌شود.',
        'caption' => 'ترکیش گت آپ — تمام بدن، اجرای کنترل‌شده',
        'quick' => ['main' => 'تمام بدن', 'secondary' => 'سرشانه، Core، باسن', 'difficulty' => 'پیشرفته', 'equipment' => 'کتل‌بل', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی تمام بدن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم کتل‌بل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: تمام بدن', 'کمکی: سرشانه، Core، باسن', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کتل کلین', 'slug' => 'کتل-کلین']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'ترکیش گت آپ برای تمام بدن و تمام بدن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'تمام بدن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'full_body', 'secondary_muscle_keys' => ['shoulder_anterior', 'abs', 'glutes'],
            'difficulty' => 'advanced', 'equipment_keys' => ['kettlebell'],
            'exercise_type' => 'conditioning', 'movement_pattern' => 'compound', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 70, 'shoulder_anterior' => 65, 'glutes' => 55],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'ترکیش گت‌آپ برای ثبات کل بدن.',
            'target_area' => 'تمام بدن',
        ],
        'rank_extra' => 'ثبات کل بدن.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-10',
        'slug' => 'پاور-کلین',
        'title' => 'پاور کلین',
        'aliases' => ['Power Clean', 'PowerClean', 'پاور کلین', 'کلین قدرتی'],
        'intro' => '<strong>پاور کلین</strong> (Power Clean) کشیدن هالتر به شانه بدون اسکات کامل؛ پایه وزنه‌برداری. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'پاور کلین — تمام بدن، اجرای کنترل‌شده',
        'quick' => ['main' => 'تمام بدن', 'secondary' => 'باسن، traps، quads', 'difficulty' => 'پیشرفته', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی تمام بدن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: تمام بدن', 'کمکی: باسن، traps، quads', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کلین و پرس', 'slug' => 'کلین-و-پرس']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'پاور کلین برای تمام بدن و تمام بدن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'تمام بدن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'full_body', 'secondary_muscle_keys' => ['glutes', 'traps', 'quads'],
            'difficulty' => 'advanced', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'conditioning', 'movement_pattern' => 'hip_hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['glutes' => 70, 'traps' => 65, 'quads' => 60, 'hamstrings' => 55],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پاور کلین برای قدرت انفجاری.',
            'target_area' => 'تمام بدن',
        ],
        'rank_extra' => 'قدرت انفجاری.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-11',
        'slug' => 'هنگ-کلین',
        'title' => 'هنگ کلین',
        'aliases' => ['Hang Clean', 'HangClean', 'هنگ کلین', 'کلین هنگ'],
        'intro' => '<strong>هنگ کلین</strong> (Hang Clean) کلین از وضعیت هنگ؛ یادگیری تکنیک اولمپیک. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'هنگ کلین — تمام بدن، اجرای کنترل‌شده',
        'quick' => ['main' => 'تمام بدن', 'secondary' => 'باسن، traps', 'difficulty' => 'پیشرفته', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی تمام بدن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: تمام بدن', 'کمکی: باسن، traps', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پاور کلین', 'slug' => 'پاور-کلین']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'هنگ کلین برای تمام بدن و تمام بدن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'تمام بدن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'full_body', 'secondary_muscle_keys' => ['glutes', 'traps'],
            'difficulty' => 'advanced', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'conditioning', 'movement_pattern' => 'hip_hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['glutes' => 68, 'traps' => 62, 'quads' => 55],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'هنگ کلین از بالای زانو.',
            'target_area' => 'تمام بدن',
        ],
        'rank_extra' => 'تکنیک کلین.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-12',
        'slug' => 'پوش-جرک',
        'title' => 'پوش جرک',
        'aliases' => ['Push Jerk', 'PushJerk', 'پوش جرک', 'جرک'],
        'intro' => '<strong>پوش جرک</strong> (Push Jerk) پرش و تقسیم یا دیپ زیر میله؛ وزنه بیشتر از پوش پرس. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'پوش جرک — سرشانه قدامی، اجرای کنترل‌شده',
        'quick' => ['main' => 'سرشانه قدامی', 'secondary' => 'پشت بازو، quads', 'difficulty' => 'پیشرفته', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سرشانه قدامی در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سرشانه قدامی', 'کمکی: پشت بازو، quads', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پوش پرس', 'slug' => 'پوش-پرس']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'پوش جرک برای سرشانه و سرشانه قدامی در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سرشانه قدامی | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'shoulder_anterior', 'secondary_muscle_keys' => ['triceps', 'quads'],
            'difficulty' => 'advanced', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['shoulder_anterior' => 80, 'triceps' => 55, 'quads' => 50],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پوش جرک برای پرس سنگین بالای سر.',
            'target_area' => 'سرشانه',
        ],
        'rank_extra' => 'جرک قدرتی.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-13',
        'slug' => 'وال-بال',
        'title' => 'وال بال',
        'aliases' => ['Wall Ball', 'WallBall', 'وال بال', 'Wall Ball Shot', 'توپ دیوار'],
        'intro' => '<strong>وال بال</strong> (Wall Ball) اسکات + پرتاب توپ به دیوار؛ کاردیو و پا و شانه. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'وال بال — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'سرشانه، باسن', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: سرشانه، باسن', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'تراستر', 'slug' => 'تراستر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'وال بال برای تمام بدن و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['shoulder_anterior', 'glutes'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'squat', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 70, 'shoulder_anterior' => 60, 'glutes' => 55],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'وال بال کراس‌فیت کلاسیک.',
            'target_area' => 'تمام بدن',
        ],
        'rank_extra' => 'کراس‌فیت.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-14',
        'slug' => 'مدیسن-بال-پاس',
        'title' => 'مدیسن بال چست پاس',
        'aliases' => ['Medicine Ball Chest Pass', 'MedicineBallChestPass', 'مدیسن بال چست پاس'],
        'intro' => '<strong>مدیسن بال چست پاس</strong> (Medicine Ball Chest Pass) پرتاب انفجاری از سینه؛ قدرت و توان بالاتنه. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'مدیسن بال چست پاس — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'پشت بازو، Core', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: پشت بازو، Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'توپ پزشکی ضربه', 'slug' => 'توپ-پزشکی-ضربه']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'مدیسن بال چست پاس برای سینه و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['triceps', 'abs'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_push', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest' => 75, 'triceps' => 50, 'abs' => 35],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پاس سینه‌ای توپ پزشکی.',
            'target_area' => 'سینه',
        ],
        'rank_extra' => 'توان سینه.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-15',
        'slug' => 'روئینگ-ارگ',
        'title' => 'روئینگ ارگ',
        'aliases' => ['Rowing Ergometer', 'RowingErgometer', 'روئینگ ارگ', 'Concept2', 'روئینگ دستگاه', 'RowErg', 'اسکی روئینگ'],
        'intro' => '<strong>روئینگ ارگ</strong> (Rowing Ergometer) پارو زدن روی ارگ؛ کاردیو کم‌ضربه با درگیری پشت و پا. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'روئینگ ارگ — تمام بدن، اجرای کنترل‌شده',
        'quick' => ['main' => 'تمام بدن', 'secondary' => 'back_lat، quads، همسترینگ', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی تمام بدن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: تمام بدن', 'کمکی: back_lat، quads، همسترینگ', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'رویینگ سیمکش', 'slug' => 'رویینگ-سیمکش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'روئینگ ارگ برای کاردیو و تمام بدن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'تمام بدن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'full_body', 'secondary_muscle_keys' => ['back_lat', 'quads', 'hamstrings'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'conditioning', 'movement_pattern' => 'compound', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 55, 'back_lat' => 60, 'hamstrings' => 50, 'abs' => 40],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'روئینگ دستگاه برای کاردیو کامل.',
            'target_area' => 'کاردیو',
        ],
        'rank_extra' => 'کاردیو کامل.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-16',
        'slug' => 'اسالت-بایک',
        'title' => 'اسالت بایک',
        'aliases' => ['Assault Bike', 'AssaultBike', 'اسالت بایک', 'Air Bike', 'ایربایک', 'Assault Air Bike'],
        'intro' => '<strong>اسالت بایک</strong> (Assault Bike) دوچرخه دست و پا؛ یکی از سخت‌ترین ابزارهای کاردیو سالن. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'اسالت بایک — تمام بدن، اجرای کنترل‌شده',
        'quick' => ['main' => 'تمام بدن', 'secondary' => 'quads، سرشانه', 'difficulty' => 'متوسط', 'equipment' => 'دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی تمام بدن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: تمام بدن', 'کمکی: quads، سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'اسکیپ طناب', 'slug' => 'اسکیپ-طناب']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'اسالت بایک برای کاردیو و تمام بدن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'تمام بدن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'full_body', 'secondary_muscle_keys' => ['quads', 'shoulder_anterior'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['machine'],
            'exercise_type' => 'conditioning', 'movement_pattern' => 'compound', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 60, 'shoulder_anterior' => 55, 'abs' => 40],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'اسالت بایک برای HIIT شدید.',
            'target_area' => 'کاردیو',
        ],
        'rank_extra' => 'HIIT شدید.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-17',
        'slug' => 'اسکی-ارگ',
        'title' => 'اسکی ارگ',
        'aliases' => ['SkiErg', 'SkiErg', 'اسکی ارگ', 'Ski Erg', 'اسکی ارگومتر'],
        'intro' => '<strong>اسکی ارگ</strong> (SkiErg) کشش دوطرفه شبیه اسکی؛ پشت و Core بدون فشار زانو. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'اسکی ارگ — تمام بدن، اجرای کنترل‌شده',
        'quick' => ['main' => 'تمام بدن', 'secondary' => 'back_lat، Core، سرشانه', 'difficulty' => 'متوسط', 'equipment' => 'دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی تمام بدن در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: تمام بدن', 'کمکی: back_lat، Core، سرشانه', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'روئینگ ارگ', 'slug' => 'روئینگ-ارگ']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'اسکی ارگ برای کاردیو و تمام بدن در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'تمام بدن | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'full_body', 'secondary_muscle_keys' => ['back_lat', 'abs', 'shoulder_anterior'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['machine'],
            'exercise_type' => 'conditioning', 'movement_pattern' => 'compound', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 65, 'abs' => 55, 'shoulder_anterior' => 50],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'اسکی ارگ برای بالاتنه و کاردیو.',
            'target_area' => 'کاردیو',
        ],
        'rank_extra' => 'کاردیو بالاتنه.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-18',
        'slug' => 'اسلد-پوش',
        'title' => 'اسلد پوش',
        'aliases' => ['Sled Push', 'SledPush', 'اسلد پوش', 'پروالر پوش', 'هل دادن سورتمه'],
        'intro' => '<strong>اسلد پوش</strong> (Sled Push) پوش سورتمه وزنه‌دار؛ قدرت پا بدون اکسنتریک سنگین. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'اسلد پوش — چهارسر، اجرای کنترل‌شده',
        'quick' => ['main' => 'چهارسر', 'secondary' => 'باسن، calves', 'difficulty' => 'متوسط', 'equipment' => 'دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی چهارسر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: چهارسر', 'کمکی: باسن، calves', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'فارمر واک', 'slug' => 'فارمر-واک']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'اسلد پوش برای پا و کاردیو و چهارسر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'چهارسر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'quads', 'secondary_muscle_keys' => ['glutes', 'calves'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'compound', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'push', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['quads' => 80, 'glutes' => 70, 'calves' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'هل دادن اسلد برای قدرت و کاردیو.',
            'target_area' => 'پا و کاردیو',
        ],
        'rank_extra' => 'قدرت پا.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-19',
        'slug' => 'اسلد-درگ',
        'title' => 'اسلد درگ',
        'aliases' => ['Sled Drag', 'SledDrag', 'اسلد درگ', 'Sled Pull', 'کشیدن سورتمه'],
        'intro' => '<strong>اسلد درگ</strong> (Sled Drag) درگ به عقب یا جلو؛ قدرت posterior chain. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'اسلد درگ — همسترینگ، اجرای کنترل‌شده',
        'quick' => ['main' => 'همسترینگ', 'secondary' => 'باسن، Core', 'difficulty' => 'متوسط', 'equipment' => 'دستگاه', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی همسترینگ در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: همسترینگ', 'کمکی: باسن، Core', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'اسلد پوش', 'slug' => 'اسلد-پوش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'اسلد درگ برای پشت پا و همسترینگ در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'همسترینگ | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'hamstrings', 'secondary_muscle_keys' => ['glutes', 'abs'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'compound', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['hamstrings' => 80, 'glutes' => 75, 'abs' => 40],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'کشیدن اسلد برای همسترینگ.',
            'target_area' => 'پشت پا',
        ],
        'rank_extra' => 'پشت زنجیره.',
    ]);

    $add([
        'image_key' => 'exercise-batch15-20',
        'slug' => 'سوئیتکیس-کرری',
        'title' => 'سوئیت‌کیس کرری',
        'aliases' => ['Suitcase Carry', 'SuitcaseCarry', 'سوئیت‌کیس کرری', 'حمل چمدانی', 'فارمر تک‌دست'],
        'intro' => '<strong>سوئیت‌کیس کرری</strong> (Suitcase Carry) راه رفتن با دمبل یک طرف؛ Core و grip یک‌طرفه. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل اجرا می‌شود.',
        'caption' => 'سوئیت‌کیس کرری — Core و grip، اجرای کنترل‌شده',
        'quick' => ['main' => 'Core و grip', 'secondary' => 'ساعد، traps', 'difficulty' => 'متوسط', 'equipment' => 'دمبل', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی Core و grip در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: Core و grip', 'کمکی: ساعد، traps', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'فارمر واک', 'slug' => 'فارمر-واک']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'سوئیت‌کیس کرری برای Core و grip و Core و grip در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'Core و grip | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'obliques', 'secondary_muscle_keys' => ['forearms', 'traps'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'carry', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['obliques' => 85, 'forearms' => 70, 'traps' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'حمل چمدانی برای ضدخمش جانبی.',
            'target_area' => 'Core و grip',
        ],
        'rank_extra' => 'ضدخمش.',
    ]);

    return $defs;
}
}
