// GymAI Popular — BATCH 8 (20 حرکت — حرکات 121 تا 140)
// Code Snippets: Run everywhere | بدون تگ php

if (!function_exists('gymai_pop20_batch8_definitions')) {
function gymai_pop20_batch8_definitions() {
    $base_img = 'https://gymaipro.ir/wp-content/uploads/2026/07/';
    $defs = [];
    $add = function (array $row) use (&$defs, $base_img) {
        if (empty($row['image'])) {
            $key = !empty($row['image_key']) ? $row['image_key'] : ('exercise-batch8-' . str_pad((string) (count($defs) + 1), 2, '0', STR_PAD_LEFT));
            $row['image'] = $base_img . $key . '.jpg';
        }
        $defs[] = $row;
    };

    $add([
        'image_key' => 'exercise-batch8-01',
        'slug' => 'زیربغل-مدوز',
        'title' => 'زیربغل مدوز',
        'aliases' => ['Meadows Row', 'MeadowsRow', 'زیربغل مدوز'],
        'intro' => '<strong>زیربغل مدوز</strong> (Meadows Row) رویینگ تک‌بازو با هالتر لندماین؛ حرکت جان میدوز برای پهن کردن پشت. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'زیربغل مدوز — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو، پشت میانی', 'difficulty' => 'متوسط', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو، پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'زیربغل تی‌بار', 'slug' => 'زیربغل-تی-بار']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'زیربغل مدوز برای زیربغل و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'rhomboids'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'bent_over', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 92, 'rhomboids' => 50, 'biceps' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'مدوز رو برای ضخامت زیربغل.',
            'target_area' => 'زیربغل',
        ],
        'rank_extra' => 'ضخامت لات.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-02',
        'slug' => 'زیربغل-سینه-روی-نیمکت',
        'title' => 'زیربغل سینه روی نیمکت',
        'aliases' => ['Chest Supported Row', 'ChestSupportedRow', 'زیربغل سینه روی نیمکت'],
        'intro' => '<strong>زیربغل سینه روی نیمکت</strong> (Chest Supported Row) کشش افقی با سینه روی نیمکت؛ بدون فشار اضافه روی کمر پایین. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل و نیمکت اجرا می‌شود.',
        'caption' => 'زیربغل سینه روی نیمکت — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو، پشت میانی', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل و نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو، پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'رویینگ دمبل', 'slug' => 'رویینگ-دمبل']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'زیربغل سینه روی نیمکت برای زیربغل و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'rhomboids'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'incline_seated', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 88, 'rhomboids' => 55, 'biceps' => 40],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'رویینگ با تکیه سینه برای کمر امن.',
            'target_area' => 'زیربغل',
        ],
        'rank_extra' => 'کمر امن.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-03',
        'slug' => 'زیربغل-دست-صاف',
        'title' => 'زیربغل دست صاف',
        'aliases' => ['Straight Arm Pulldown', 'StraightArmPulldown', 'زیربغل دست صاف'],
        'intro' => '<strong>زیربغل دست صاف</strong> (Straight Arm Pulldown) کشش با آرنج صاف؛ برای آموزش فعال‌سازی زیربغل قبل از بارفیکس. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'زیربغل دست صاف — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'پشت بازو', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: پشت بازو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'زیربغل سیمکش', 'slug' => 'زیربغل-سیمکش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'زیربغل دست صاف برای زیربغل و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['triceps'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 90, 'triceps' => 25],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'پول‌داون دست صاف برای جداسازی لات.',
            'target_area' => 'زیربغل',
        ],
        'rank_extra' => 'جداسازی لات.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-04',
        'slug' => 'بارفیکس-دست-باز',
        'title' => 'بارفیکس دست باز',
        'aliases' => ['Wide Grip Pull-Up', 'WideGripPull-Up', 'بارفیکس دست باز'],
        'intro' => '<strong>بارفیکس دست باز</strong> (Wide Grip Pull-Up) کشش عمودی با گرفتن باز؛ تاکید بیشتر روی عرض زیربغل. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن و میله اجرا می‌شود.',
        'caption' => 'بارفیکس دست باز — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو، پشت میانی', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن و میله', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و میله و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو، پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'بارفیکس', 'slug' => 'بارفیکس']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'بارفیکس دست باز برای زیربغل و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'rhomboids'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight', 'bar'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'hanging', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 92, 'biceps' => 45, 'rhomboids' => 35],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'بارفیکس دست باز برای پهن‌تر شدن پشت.',
            'target_area' => 'زیربغل',
        ],
        'rank_extra' => 'عرض پشت.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-05',
        'slug' => 'بارفیکس-آرچر',
        'title' => 'بارفیکس آرچر',
        'aliases' => ['Archer Pull-Up', 'ArcherPull-Up', 'بارفیکس آرچر'],
        'intro' => '<strong>بارفیکس آرچر</strong> (Archer Pull-Up) بارفیکس با انتقال وزن به یک دست؛ مرحله پیشرفته قبل از one arm pull up. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن و میله اجرا می‌شود.',
        'caption' => 'بارفیکس آرچر — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو', 'difficulty' => 'پیشرفته', 'equipment' => 'وزن بدن و میله', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و میله و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'چین آپ', 'slug' => 'چین-آپ']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'بارفیکس آرچر برای زیربغل و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps'],
            'difficulty' => 'advanced', 'equipment_keys' => ['bodyweight', 'bar'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'hanging', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 90, 'biceps' => 55],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'بارفیکس آرچر برای قدرت تک‌بازو.',
            'target_area' => 'زیربغل',
        ],
        'rank_extra' => 'قدرت تک‌بازو.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-06',
        'slug' => 'رویینگ-هالتر-معکوس',
        'title' => 'رویینگ هالتر معکوس',
        'aliases' => ['Underhand Barbell Row', 'UnderhandBarbellRow', 'رویینگ هالتر معکوس'],
        'intro' => '<strong>رویینگ هالتر معکوس</strong> (Underhand Barbell Row) قایقی هالتر با کف دست رو به بالا؛ جلو بازو و زیربغل با هم درگیر می‌شوند. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'رویینگ هالتر معکوس — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو', 'difficulty' => 'متوسط', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'رویینگ هالتر', 'slug' => 'رویینگ-هالتر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'رویینگ هالتر معکوس برای پشت و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'bent_over', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 85, 'biceps' => 65, 'rhomboids' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'رویینگ دست معکوس برای جلو بازو بیشتر.',
            'target_area' => 'پشت',
        ],
        'rank_extra' => 'جلوبازو + پشت.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-07',
        'slug' => 'رویینگ-معکوس',
        'title' => 'رویینگ معکوس',
        'aliases' => ['Inverted Row', 'InvertedRow', 'رویینگ معکوس'],
        'intro' => '<strong>رویینگ معکوس</strong> (Inverted Row) قایقی با بدن زیر میله؛ برای مبتدی قبل از رویینگ هالتر در خانه و پارک. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن و میله اجرا می‌شود.',
        'caption' => 'رویینگ معکوس — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو، پشت میانی', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن و میله', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و میله و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو، پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'بارفیکس کمکی', 'slug' => 'بارفیکس-کمکی']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'رویینگ معکوس برای پشت و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'rhomboids'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight', 'bar'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 80, 'biceps' => 50, 'rhomboids' => 40],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'رویینگ معکوس با وزن بدن.',
            'target_area' => 'پشت',
        ],
        'rank_extra' => 'مسیر یادگیری.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-08',
        'slug' => 'لندماین-رویینگ',
        'title' => 'لندماین رویینگ',
        'aliases' => ['Landmine Row', 'LandmineRow', 'لندماین رویینگ'],
        'intro' => '<strong>لندماین رویینگ</strong> (Landmine Row) رویینگ با هالتر لندماین؛ زاویه طبیعی و فشار کمتر روی کمر. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'لندماین رویینگ — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو، پشت میانی', 'difficulty' => 'متوسط', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو، پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'زیربغل مدوز', 'slug' => 'زیربغل-مدوز']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'لندماین رویینگ برای پشت و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'rhomboids'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'bent_over', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 88, 'rhomboids' => 55, 'biceps' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'لندماین رو برای ضخامت پشت.',
            'target_area' => 'پشت',
        ],
        'rank_extra' => 'زاویه طبیعی.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-09',
        'slug' => 'پول-اور-دمبل',
        'title' => 'پول اور دمبل',
        'aliases' => ['Dumbbell Pullover', 'DumbbellPullover', 'پول اور دمبل'],
        'intro' => '<strong>پول اور دمبل</strong> (Dumbbell Pullover) حرکت قوسی با دمبل بالای سر؛ در بدنسازی کلاسیک برای سینه و پشت. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل و نیمکت اجرا می‌شود.',
        'caption' => 'پول اور دمبل — سینه، اجرای کنترل‌شده',
        'quick' => ['main' => 'سینه', 'secondary' => 'back_lat، پشت بازو', 'difficulty' => 'متوسط', 'equipment' => 'دمبل و نیمکت', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی سینه در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و نیمکت و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: سینه', 'کمکی: back_lat، پشت بازو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'پول اور', 'slug' => 'پول-اور']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'پول اور دمبل برای سینه و زیربغل و سینه در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'سینه | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'chest', 'secondary_muscle_keys' => ['back_lat', 'triceps'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['dumbbell', 'bench'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['chest' => 75, 'back_lat' => 60, 'triceps' => 35],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پول‌اور دمبل کلاسیک برای سینه و rib cage.',
            'target_area' => 'سینه و زیربغل',
        ],
        'rank_extra' => 'سینه و قفسه.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-10',
        'slug' => 'زیربغل-وی-بار',
        'title' => 'زیربغل وی بار',
        'aliases' => ['V-Bar Lat Pulldown', 'V-BarLatPulldown', 'زیربغل وی بار'],
        'intro' => '<strong>زیربغل وی بار</strong> (V-Bar Lat Pulldown) کشش عمودی با دستگیره V؛ احساس کشش متمرکز روی زیربغل. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'زیربغل وی بار — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'زیربغل سیمکش', 'slug' => 'زیربغل-سیمکش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'زیربغل وی بار برای زیربغل و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 90, 'biceps' => 50],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پول‌داون وی‌بار برای ضخامت لات.',
            'target_area' => 'زیربغل',
        ],
        'rank_extra' => 'کشش متمرکز.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-11',
        'slug' => 'زیربغل-پشت-گردن',
        'title' => 'زیربغل پشت گردن',
        'aliases' => ['Behind Neck Pulldown', 'BehindNeckPulldown', 'زیربغل پشت گردن'],
        'intro' => '<strong>زیربغل پشت گردن</strong> (Behind Neck Pulldown) کشش میله پشت سر؛ حرکت قدیمی برای عرض پشت — با احتیاط و دامنه کنترل‌شده. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'زیربغل پشت گردن — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو، traps', 'difficulty' => 'پیشرفته', 'equipment' => 'سیم‌کش', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو، traps', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'زیربغل وی بار', 'slug' => 'زیربغل-وی-بار']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'زیربغل پشت گردن برای زیربغل و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'traps'],
            'difficulty' => 'advanced', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 85, 'traps' => 45, 'biceps' => 40],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'پول‌داون پشت گردن — فقط با شانه سالم.',
            'target_area' => 'زیربغل',
        ],
        'rank_extra' => 'عرض پشت — احتیاط.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-12',
        'slug' => 'بارفیکس-استرالیایی',
        'title' => 'بارفیکس استرالیایی',
        'aliases' => ['Australian Pull-Up', 'AustralianPull-Up', 'بارفیکس استرالیایی'],
        'intro' => '<strong>بارفیکس استرالیایی</strong> (Australian Pull-Up) رویینگ افقی با پا روی زمین؛ برای خانه و پارک بسیار کاربردی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن و میله اجرا می‌شود.',
        'caption' => 'بارفیکس استرالیایی — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو، پشت میانی', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن و میله', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و میله و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو، پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'رویینگ معکوس', 'slug' => 'رویینگ-معکوس']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'بارفیکس استرالیایی برای پشت و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'rhomboids'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight', 'bar'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 78, 'biceps' => 48, 'rhomboids' => 42],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'بارفیکس استرالیایی در ارتفاع کم.',
            'target_area' => 'پشت',
        ],
        'rank_extra' => 'تمرین خانگی.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-13',
        'slug' => 'رویینگ-کابل-ایستاده',
        'title' => 'رویینگ کابل ایستاده',
        'aliases' => ['Standing Cable Row', 'StandingCableRow', 'رویینگ کابل ایستاده'],
        'intro' => '<strong>رویینگ کابل ایستاده</strong> (Standing Cable Row) کشش افقی ایستاده؛ برای پشت و وضعیت ایستاده در تمرین عملکردی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با سیم‌کش اجرا می‌شود.',
        'caption' => 'رویینگ کابل ایستاده — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو، پشت میانی', 'difficulty' => 'مبتدی', 'equipment' => 'سیم‌کش', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم سیم‌کش و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو، پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'زیربغل نشسته سیمکش', 'slug' => 'زیربغل-نشسته-سیمکش']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'رویینگ کابل ایستاده برای پشت و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'rhomboids'],
            'difficulty' => 'beginner', 'equipment_keys' => ['cable'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'cable_constant', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 85, 'rhomboids' => 50, 'biceps' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'رویینگ ایستاده سیمکش.',
            'target_area' => 'پشت',
        ],
        'rank_extra' => 'ایستاده.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-14',
        'slug' => 'شنا-حلقه',
        'title' => 'شنا حلقه',
        'aliases' => ['Ring Row', 'RingRow', 'شنا حلقه'],
        'intro' => '<strong>شنا حلقه</strong> (Ring Row) قایقی ناپایدار با TRX یا حلقه؛ Core و پشت با هم. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'شنا حلقه — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'جلوبازو، پشت میانی', 'difficulty' => 'متوسط', 'equipment' => 'وزن بدن', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: جلوبازو، پشت میانی', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'رویینگ معکوس', 'slug' => 'رویینگ-معکوس']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'شنا حلقه برای پشت و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['biceps', 'rhomboids'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'horizontal_pull', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'supine', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 82, 'biceps' => 48, 'abs' => 35],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'رویینگ با حلقه ژیمناستیک.',
            'target_area' => 'پشت',
        ],
        'rank_extra' => 'ناپایداری.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-15',
        'slug' => 'رومانیایی-هالتر',
        'title' => 'رومانیایی هالتر',
        'aliases' => ['Barbell Romanian Deadlift', 'BarbellRomanianDeadlift', 'رومانیایی هالتر'],
        'intro' => '<strong>رومانیایی هالتر</strong> (Barbell Romanian Deadlift) هیپ‌هینج با هالتر و زانو نرم؛ یکی از اصلی‌ترین حرکات پشت پا در بدنسازی. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'رومانیایی هالتر — همسترینگ، اجرای کنترل‌شده',
        'quick' => ['main' => 'همسترینگ', 'secondary' => 'باسن، lower_back', 'difficulty' => 'متوسط', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی همسترینگ در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: همسترینگ', 'کمکی: باسن، lower_back', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'ددلیفت', 'slug' => 'ددلیفت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'رومانیایی هالتر برای پشت پا و همسترینگ در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'همسترینگ | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'hamstrings', 'secondary_muscle_keys' => ['glutes', 'lower_back'],
            'difficulty' => 'intermediate', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'hip_hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['hamstrings' => 90, 'glutes' => 80, 'lower_back' => 45],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 4, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'RDL هالتر برای پشت پا و باسن.',
            'target_area' => 'پشت پا',
        ],
        'rank_extra' => 'پشت پا کلاسیک.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-16',
        'slug' => 'ددلیفت-قاپ-باز',
        'title' => 'ددلیفت قاپ باز',
        'aliases' => ['Snatch Grip Deadlift', 'SnatchGripDeadlift', 'ددلیفت قاپ باز'],
        'intro' => '<strong>ددلیفت قاپ باز</strong> (Snatch Grip Deadlift) ددلیفت با دست خیلی باز؛ برای تله و زیربغل و انعطاف. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با هالتر اجرا می‌شود.',
        'caption' => 'ددلیفت قاپ باز — زیربغل، اجرای کنترل‌شده',
        'quick' => ['main' => 'زیربغل', 'secondary' => 'همسترینگ، باسن، traps', 'difficulty' => 'پیشرفته', 'equipment' => 'هالتر', 'type' => 'قدرتی / حجمی'],
        'tips' => ['تمرکز روی زیربغل در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم هالتر و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: زیربغل', 'کمکی: همسترینگ، باسن، traps', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'ددلیفت', 'slug' => 'ددلیفت']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'نیاز به تسلط پایه دارد؛ با وزنه سبک شروع کن.']],
        'summary' => 'ددلیفت قاپ باز برای پشت و زیربغل در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'زیربغل | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'back_lat', 'secondary_muscle_keys' => ['hamstrings', 'glutes', 'traps'],
            'difficulty' => 'advanced', 'equipment_keys' => ['barbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'hip_hinge', 'body_engagement' => 'compound',
            'mechanics_type' => 'compound', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'pronated', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['back_lat' => 75, 'traps' => 80, 'hamstrings' => 70, 'glutes' => 65],
            'met' => 5.5, 'movement_distance_cm' => 48, 'calories_per_1000kg' => 44, 'exercise_difficulty_score' => 5, 'typical_rpe' => 7.5,
            'estimated_1rm_formula' => 'brzycki', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 90, 'tempo' => '2-1-2',
            'short_description' => 'ددلیفت گرفتن قاپ باز برای پشت پهن.',
            'target_area' => 'پشت',
        ],
        'rank_extra' => 'پشت پهن.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-17',
        'slug' => 'شراگ-اسمیت',
        'title' => 'شراگ اسمیت',
        'aliases' => ['Smith Machine Shrug', 'SmithMachineShrug', 'شراگ اسمیت'],
        'intro' => '<strong>شراگ اسمیت</strong> (Smith Machine Shrug) بالا بردن شانه با میله اسمیت؛ برای تله بالا در روز پشت یا شانه. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'شراگ اسمیت — کول، اجرای کنترل‌شده',
        'quick' => ['main' => 'کول', 'secondary' => 'ساعد', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی کول در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: کول', 'کمکی: ساعد', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'کول هالتر', 'slug' => 'کول-هالتر']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'شراگ اسمیت برای کول و کول در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'کول | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'traps', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['traps' => 95, 'forearms' => 40],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'شراگ اسمیت برای ذوزنقه.',
            'target_area' => 'کول',
        ],
        'rank_extra' => 'تله بالا.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-18',
        'slug' => 'خیز-بالا-پرچم',
        'title' => 'خیز بالا پرچم',
        'aliases' => ['Bird Dog', 'BirdDog', 'خیز بالا پرچم'],
        'intro' => '<strong>خیز بالا پرچم</strong> (Bird Dog) دراز کشیدن دست و پای مخالف؛ حرکت اصلاحی فیزیوتراپی برای Core. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با وزن بدن اجرا می‌شود.',
        'caption' => 'خیز بالا پرچم — شکم، اجرای کنترل‌شده',
        'quick' => ['main' => 'شکم', 'secondary' => 'lower_back، باسن', 'difficulty' => 'مبتدی', 'equipment' => 'وزن بدن', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی شکم در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم وزن بدن و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: شکم', 'کمکی: lower_back، باسن', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'ددباگ', 'slug' => 'ددباگ']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'خیز بالا پرچم برای Core و شکم در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'شکم | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'abs', 'secondary_muscle_keys' => ['lower_back', 'glutes'],
            'difficulty' => 'beginner', 'equipment_keys' => ['bodyweight'],
            'exercise_type' => 'strength', 'movement_pattern' => 'anti_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'prone', 'grip_type' => 'neutral', 'resistance_profile' => 'bodyweight', 'joint_focus' => 'multi',
            'muscle_targets' => ['abs' => 70, 'lower_back' => 55, 'glutes' => 40],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'Bird Dog برای Core و کمر پایدار.',
            'target_area' => 'Core',
        ],
        'rank_extra' => 'Core اصلاحی.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-19',
        'slug' => 'پشت-کمر-دستگاه',
        'title' => 'پشت کمر دستگاه',
        'aliases' => ['Back Extension Machine', 'BackExtensionMachine', 'پشت کمر دستگاه'],
        'intro' => '<strong>پشت کمر دستگاه</strong> (Back Extension Machine) خم و باز کردن تنه روی دستگاه؛ برای کمر پایین و پیشگیری درد. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دستگاه اجرا می‌شود.',
        'caption' => 'پشت کمر دستگاه — کمر، اجرای کنترل‌شده',
        'quick' => ['main' => 'کمر', 'secondary' => 'باسن، همسترینگ', 'difficulty' => 'مبتدی', 'equipment' => 'دستگاه', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی کمر در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دستگاه و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: کمر', 'کمکی: باسن، همسترینگ', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'سوپرمن', 'slug' => 'سوپرمن']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'پشت کمر دستگاه برای کمر و کمر در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'کمر | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'lower_back', 'secondary_muscle_keys' => ['glutes', 'hamstrings'],
            'difficulty' => 'beginner', 'equipment_keys' => ['machine'],
            'exercise_type' => 'strength', 'movement_pattern' => 'back_extension', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'seated', 'grip_type' => 'neutral', 'resistance_profile' => 'machine_stack', 'joint_focus' => 'multi',
            'muscle_targets' => ['lower_back' => 90, 'glutes' => 45, 'hamstrings' => 35],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'اکستنشن کمر دستگاه برای تقویت ارکتور.',
            'target_area' => 'کمر',
        ],
        'rank_extra' => 'کمر قوی.',
    ]);

    $add([
        'image_key' => 'exercise-batch8-20',
        'slug' => 'کول-دمبل',
        'title' => 'کول دمبل',
        'aliases' => ['Dumbbell Shrug', 'DumbbellShrug', 'کول دمبل'],
        'intro' => '<strong>کول دمبل</strong> (Dumbbell Shrug) بالا بردن شانه با دمبل؛ ساده و مؤثر برای ذوزنقه. در برنامه‌های بدنسازی و فیتنس ایران نام آشنایی است و معمولاً با دمبل اجرا می‌شود.',
        'caption' => 'کول دمبل — کول، اجرای کنترل‌شده',
        'quick' => ['main' => 'کول', 'secondary' => 'ساعد', 'difficulty' => 'مبتدی', 'equipment' => 'دمبل', 'type' => 'ایزوله'],
        'tips' => ['تمرکز روی کول در تمام دامنه حرکت.', 'تمپو کنترل‌شده؛ بدون پرتاب یا قلدری.', 'گرم‌کردن مفصل و عضله قبل از ست سنگین.'],
        'setup' => ['تنظیم دمبل و وضعیت بدن.', 'وضعیت خنثی کمر و Core سفت.', 'دامنه مفصل بدون درد.', 'تنفس آماده قبل از شروع.'],
        'execution' => ['شروع کنترل‌شده از وضعیت اولیه.', 'حرکت در مسیر صحیح بدون قفل اجباری مفصل.', 'مکث کوتاه در نقطه انقباض (در صورت نیاز).', 'بازگشت آهسته به وضعیت شروع.'],
        'breathing' => 'بازدم در فاز سخت — دم در فاز بازگشت.',
        'muscles' => ['اصلی: کول', 'کمکی: ساعد', 'تثبیت: Core و مفاصل اطراف'],
        'mistakes' => [['پرتاب وزنه یا بدن', 'تمپو ۲-۱-۲'], ['دامنه ناقص', 'دامنه کامل بدون درد'], ['کمر یا شانه گرد', 'وضعیت خنثی']],
        'program' => [['حجم', '۳–۴', '۸–۱۲', '۶۰–۹۰ث'], ['قدرت', '۴', '۵–۸', '۱۲۰ث'], ['استقامت', '۳', '۱۲–۱۵', '۴۵ث']],
        'combos' => [['label' => 'با ', 'link_text' => 'شراگ دمبل', 'slug' => 'شراگ-دمبل']],
        'faqs' => [['چند ست و تکرار؟', '۳–۴ ست × ۸–۱۲ برای حجم؛ ۴–۵ ست × ۵–۸ برای قدرت.'], ['برای مبتدی مناسب است؟', 'بله با وزنه سبک و تمرکز روی فرم.']],
        'summary' => 'کول دمبل برای کول و کول در برنامه منظم نتیجه خوب می‌دهد.',
        'summary_keys' => 'کول | تمپو کنترل | دامنه کامل',
        'meta' => [
            'main_muscle' => 'traps', 'secondary_muscle_keys' => ['forearms'],
            'difficulty' => 'beginner', 'equipment_keys' => ['dumbbell'],
            'exercise_type' => 'strength', 'movement_pattern' => 'vertical_pull', 'body_engagement' => 'isolation',
            'mechanics_type' => 'isolation', 'force_type' => 'pull', 'plane_of_motion' => 'sagittal', 'laterality' => 'bilateral',
            'posture' => 'standing', 'grip_type' => 'neutral', 'resistance_profile' => 'free_weight', 'joint_focus' => 'multi',
            'muscle_targets' => ['traps' => 92, 'forearms' => 35],
            'met' => 4, 'movement_distance_cm' => 40, 'calories_per_1000kg' => 38, 'exercise_difficulty_score' => 3, 'typical_rpe' => 7,
            'estimated_1rm_formula' => '', 'programming_goal' => 'hypertrophy', 'recommended_sets' => '3-4',
            'rep_range_strength' => '6-10', 'rep_range_hypertrophy' => '8-12', 'rep_range_endurance' => '12-15', 'rest_seconds' => 60, 'tempo' => '2-1-2',
            'short_description' => 'شراگ دمبل برای تله.',
            'target_area' => 'کول',
        ],
        'rank_extra' => 'تله ساده.',
    ]);

    return $defs;
}
}
